#include "TEventTree.h"

TEventTree::TEventTree(TTree *tree)
{
   Init(tree);
}

TEventTree::~TEventTree()
{
   if (!fChain) return;
   //delete fChain->GetCurrentFile();
}

void TEventTree::GetEntryNeededBranchesOnly(Long64_t entry)
{
   b_run->GetEntry(entry);
   b_event->GetEntry(entry);
   b_isData->GetEntry(entry);
   b_nHLT->GetEntry(entry);
   b_HLT->GetEntry(entry);
   b_HLTIndex->GetEntry(entry);
   b_IsVtxGood->GetEntry(entry);
   b_pfMET->GetEntry(entry);
   b_pfMETPhi->GetEntry(entry);
   b_metFilters->GetEntry(entry);
   b_nEle->GetEntry(entry);
   b_elePt->GetEntry(entry);
   b_nPho->GetEntry(entry);
   b_phoEt->GetEntry(entry);
   b_phoEta->GetEntry(entry);
   b_phoPhi->GetEntry(entry);
   b_phoR9->GetEntry(entry);
   b_phoHoverE12->GetEntry(entry);
   b_phoEleVeto->GetEntry(entry);
   b_phoSigmaIEtaIEta->GetEntry(entry);
   b_phoPFChIso->GetEntry(entry);
   b_phoPFPhoIso->GetEntry(entry);
   b_phoPFNeuIso->GetEntry(entry);
   b_phoSCEt->GetEntry(entry);
   b_phoSCEta->GetEntry(entry);
   b_phoSCPhi->GetEntry(entry);
   b_nMu->GetEntry(entry);
   b_muTrg->GetEntry(entry);
   b_muEta->GetEntry(entry);
   b_muPhi->GetEntry(entry);
   b_muPt->GetEntry(entry);
   b_muChi2NDF->GetEntry(entry);
   b_muPFIsoR04_CH->GetEntry(entry);
   b_muPFIsoR04_NH->GetEntry(entry);
   b_muPFIsoR04_Pho->GetEntry(entry);
   b_muPFIsoR04_PU->GetEntry(entry);
   b_muD0->GetEntry(entry);
   b_muDz->GetEntry(entry);
   b_muNumberOfValidTrkLayers->GetEntry(entry);
   b_muNumberOfValidTrkHits->GetEntry(entry);
   b_muNumberOfValidPixelHits->GetEntry(entry);
   b_muNumberOfValidMuonHits->GetEntry(entry);
   b_muStations->GetEntry(entry);
   b_rho2012->GetEntry(entry);
   b_nJet->GetEntry(entry);
   b_jetRawPt->GetEntry(entry);
   b_jetRawEn->GetEntry(entry);
   b_jetPt->GetEntry(entry);
   b_jetEta->GetEntry(entry);
   b_jetPhi->GetEntry(entry);
   b_nLowPtJet->GetEntry(entry);
   b_jetLowPtRawPt->GetEntry(entry);
   b_jetLowPtRawEn->GetEntry(entry);
   b_jetLowPtPt->GetEntry(entry);
   b_jetLowPtEta->GetEntry(entry);
   b_jetLowPtPhi->GetEntry(entry);
}

void TEventTree::GetEntryMCSpecific(Long64_t entry)
{
   b_nMC->GetEntry(entry); 
   b_mcPID->GetEntry(entry); 
   b_mcE->GetEntry(entry);
   b_mcEt->GetEntry(entry);
   b_mcPt->GetEntry(entry);
   b_mcEta->GetEntry(entry);
   b_mcIndex->GetEntry(entry);
   b_muGenIndex->GetEntry(entry);
   b_phoGenIndex->GetEntry(entry);
   b_puTrue->GetEntry(entry);

//   b_jetGenJetPt->GetEntry(entry);
//   b_jetGenJetEta->GetEntry(entry);
//   b_jetGenJetPhi->GetEntry(entry);
//   b_jetLowPtGenJetPt->GetEntry(entry);
//   b_jetLowPtGenJetEta->GetEntry(entry);
//   b_jetLowPtGenJetPhi->GetEntry(entry);

}

void TEventTree::Init(TTree *tree)
{
   // The Init() function is called when the selector needs to initialize
   // a new tree or chain. Typically here the branch addresses and branch
   // pointers of the tree will be set.
   // It is normally not necessary to make changes to the generated
   // code, but the routine can be extended by the user if needed.
   // Init() will be called many times when running on PROOF
   // (once per file to be processed).

   // Set branch addresses and branch pointers
   if (!tree) return;
   fChain = tree;
   fCurrent = -1;
   fChain->SetMakeClass(1);

   fChain->SetBranchAddress("run", &treeLeaf.run, &b_run);
   fChain->SetBranchAddress("event", &treeLeaf.event, &b_event);
   fChain->SetBranchAddress("lumis", &treeLeaf.lumis, &b_lumis);
   fChain->SetBranchAddress("isData", &treeLeaf.isData, &b_isData);
   fChain->SetBranchAddress("nHLT", &treeLeaf.nHLT, &b_nHLT);
   fChain->SetBranchAddress("HLT", treeLeaf.HLT, &b_HLT);
   fChain->SetBranchAddress("HLTIndex", treeLeaf.HLTIndex, &b_HLTIndex);
   fChain->SetBranchAddress("bspotPos", treeLeaf.bspotPos, &b_bspotPos);
   fChain->SetBranchAddress("nVtx", &treeLeaf.nVtx, &b_nVtx);
   fChain->SetBranchAddress("vtx", treeLeaf.vtx, &b_vtx);
   fChain->SetBranchAddress("IsVtxGood", &treeLeaf.IsVtxGood, &b_IsVtxGood);
   fChain->SetBranchAddress("nVtxBS", &treeLeaf.nVtxBS, &b_nVtxBS);
   fChain->SetBranchAddress("vtxbs", treeLeaf.vtxbs, &b_vtxbs);
   fChain->SetBranchAddress("pdf", treeLeaf.pdf, &b_pdf);
   fChain->SetBranchAddress("pthat", &treeLeaf.pthat, &b_pthat);
   fChain->SetBranchAddress("processID", &treeLeaf.processID, &b_processID);
   fChain->SetBranchAddress("nMC", &treeLeaf.nMC, &b_nMC);
   fChain->SetBranchAddress("mcPID", treeLeaf.mcPID, &b_mcPID);
   fChain->SetBranchAddress("mcVtx", treeLeaf.mcVtx, &b_mcVtx);
   fChain->SetBranchAddress("mcPt", treeLeaf.mcPt, &b_mcPt);
   fChain->SetBranchAddress("mcMass", treeLeaf.mcMass, &b_mcMass);
   fChain->SetBranchAddress("mcEta", treeLeaf.mcEta, &b_mcEta);
   fChain->SetBranchAddress("mcPhi", treeLeaf.mcPhi, &b_mcPhi);
   fChain->SetBranchAddress("mcE", treeLeaf.mcE, &b_mcE);
   fChain->SetBranchAddress("mcEt", treeLeaf.mcEt, &b_mcEt);
   fChain->SetBranchAddress("mcGMomPID", treeLeaf.mcGMomPID, &b_mcGMomPID);
   fChain->SetBranchAddress("mcMomPID", treeLeaf.mcMomPID, &b_mcMomPID);
   fChain->SetBranchAddress("mcMomPt", treeLeaf.mcMomPt, &b_mcMomPt);
   fChain->SetBranchAddress("mcMomMass", treeLeaf.mcMomMass, &b_mcMomMass);
   fChain->SetBranchAddress("mcMomEta", treeLeaf.mcMomEta, &b_mcMomEta);
   fChain->SetBranchAddress("mcMomPhi", treeLeaf.mcMomPhi, &b_mcMomPhi);
   fChain->SetBranchAddress("mcIndex", treeLeaf.mcIndex, &b_mcIndex);
   fChain->SetBranchAddress("mcDecayType", treeLeaf.mcDecayType, &b_mcDecayType);
   fChain->SetBranchAddress("genMET", &treeLeaf.genMET, &b_genMET);
   fChain->SetBranchAddress("genMETPhi", &treeLeaf.genMETPhi, &b_genMETPhi);
   fChain->SetBranchAddress("nPUInfo", &treeLeaf.nPUInfo, &b_nPUInfo);
   fChain->SetBranchAddress("nPU", treeLeaf.nPU, &b_nPU);
   fChain->SetBranchAddress("puBX", treeLeaf.puBX, &b_puBX);
   fChain->SetBranchAddress("puTrue", treeLeaf.puTrue, &b_puTrue);
   fChain->SetBranchAddress("MET", &treeLeaf.MET, &b_MET);
   fChain->SetBranchAddress("METPhi", &treeLeaf.METPhi, &b_METPhi);
   fChain->SetBranchAddress("METsumEt", &treeLeaf.METsumEt, &b_METsumEt);
   fChain->SetBranchAddress("pfMET", &treeLeaf.pfMET, &b_pfMET);
   fChain->SetBranchAddress("pfMETPhi", &treeLeaf.pfMETPhi, &b_pfMETPhi);
   fChain->SetBranchAddress("pfMETsumEt", &treeLeaf.pfMETsumEt, &b_pfMETsumEt);
   fChain->SetBranchAddress("pfMETmEtSig", &treeLeaf.pfMETmEtSig, &b_pfMETmEtSig);
   fChain->SetBranchAddress("pfMETSig", &treeLeaf.pfMETSig, &b_pfMETSig);
   fChain->SetBranchAddress("recoPfMET", &treeLeaf.recoPfMET, &b_recoPfMET);
   fChain->SetBranchAddress("recoPfMETPhi", &treeLeaf.recoPfMETPhi, &b_recoPfMETPhi);
   fChain->SetBranchAddress("recoPfMETsumEt", &treeLeaf.recoPfMETsumEt, &b_recoPfMETsumEt);
   fChain->SetBranchAddress("recoPfMETmEtSig", &treeLeaf.recoPfMETmEtSig, &b_recoPfMETmEtSig);
   fChain->SetBranchAddress("recoPfMETSig", &treeLeaf.recoPfMETSig, &b_recoPfMETSig);
   fChain->SetBranchAddress("metFilters", treeLeaf.metFilters, &b_metFilters);
   fChain->SetBranchAddress("nEle", &treeLeaf.nEle, &b_nEle);
   fChain->SetBranchAddress("eleTrg", treeLeaf.eleTrg, &b_eleTrg);
   fChain->SetBranchAddress("eleClass", treeLeaf.eleClass, &b_eleClass);
   fChain->SetBranchAddress("eleIsEcalDriven", treeLeaf.eleIsEcalDriven, &b_eleIsEcalDriven);
   fChain->SetBranchAddress("eleCharge", treeLeaf.eleCharge, &b_eleCharge);
   fChain->SetBranchAddress("eleEn", treeLeaf.eleEn, &b_eleEn);
   fChain->SetBranchAddress("eleEcalEn", treeLeaf.eleEcalEn, &b_eleEcalEn);
   fChain->SetBranchAddress("eleSCRawEn", treeLeaf.eleSCRawEn, &b_eleSCRawEn);
   fChain->SetBranchAddress("eleSCEn", treeLeaf.eleSCEn, &b_eleSCEn);
   fChain->SetBranchAddress("eleESEn", treeLeaf.eleESEn, &b_eleESEn);
   fChain->SetBranchAddress("elePt", treeLeaf.elePt, &b_elePt);
   fChain->SetBranchAddress("eleEta", treeLeaf.eleEta, &b_eleEta);
   fChain->SetBranchAddress("elePhi", treeLeaf.elePhi, &b_elePhi);
   fChain->SetBranchAddress("eleEtaVtx", treeLeaf.eleEtaVtx, &b_eleEtaVtx);
   fChain->SetBranchAddress("elePhiVtx", treeLeaf.elePhiVtx, &b_elePhiVtx);
   fChain->SetBranchAddress("eleEtVtx", treeLeaf.eleEtVtx, &b_eleEtVtx);
   fChain->SetBranchAddress("eleSCEta", treeLeaf.eleSCEta, &b_eleSCEta);
   fChain->SetBranchAddress("eleSCPhi", treeLeaf.eleSCPhi, &b_eleSCPhi);
   fChain->SetBranchAddress("eleSCEtaWidth", treeLeaf.eleSCEtaWidth, &b_eleSCEtaWidth);
   fChain->SetBranchAddress("eleSCPhiWidth", treeLeaf.eleSCPhiWidth, &b_eleSCPhiWidth);
   fChain->SetBranchAddress("eleVtx", treeLeaf.eleVtx, &b_eleVtx);
   fChain->SetBranchAddress("eleD0", treeLeaf.eleD0, &b_eleD0);
   fChain->SetBranchAddress("eleDz", treeLeaf.eleDz, &b_eleDz);
   fChain->SetBranchAddress("eleD0GV", treeLeaf.eleD0GV, &b_eleD0GV);
   fChain->SetBranchAddress("eleDzGV", treeLeaf.eleDzGV, &b_eleDzGV);
   fChain->SetBranchAddress("eleD0Vtx", treeLeaf.eleD0Vtx, &b_eleD0Vtx);
   fChain->SetBranchAddress("eleDzVtx", treeLeaf.eleDzVtx, &b_eleDzVtx);
   fChain->SetBranchAddress("eleHoverE", treeLeaf.eleHoverE, &b_eleHoverE);
   fChain->SetBranchAddress("eleHoverE12", treeLeaf.eleHoverE12, &b_eleHoverE12);
   fChain->SetBranchAddress("eleEoverP", treeLeaf.eleEoverP, &b_eleEoverP);
   fChain->SetBranchAddress("elePin", treeLeaf.elePin, &b_elePin);
   fChain->SetBranchAddress("elePout", treeLeaf.elePout, &b_elePout);
   fChain->SetBranchAddress("eleTrkMomErr", treeLeaf.eleTrkMomErr, &b_eleTrkMomErr);
   fChain->SetBranchAddress("eleBrem", treeLeaf.eleBrem, &b_eleBrem);
   fChain->SetBranchAddress("eledEtaAtVtx", treeLeaf.eledEtaAtVtx, &b_eledEtaAtVtx);
   fChain->SetBranchAddress("eledPhiAtVtx", treeLeaf.eledPhiAtVtx, &b_eledPhiAtVtx);
   fChain->SetBranchAddress("eleSigmaIEtaIEta", treeLeaf.eleSigmaIEtaIEta, &b_eleSigmaIEtaIEta);
   fChain->SetBranchAddress("eleSigmaIEtaIPhi", treeLeaf.eleSigmaIEtaIPhi, &b_eleSigmaIEtaIPhi);
   fChain->SetBranchAddress("eleSigmaIPhiIPhi", treeLeaf.eleSigmaIPhiIPhi, &b_eleSigmaIPhiIPhi);
   fChain->SetBranchAddress("eleEmax", treeLeaf.eleEmax, &b_eleEmax);
   fChain->SetBranchAddress("eleE1x5", treeLeaf.eleE1x5, &b_eleE1x5);
   fChain->SetBranchAddress("eleE3x3", treeLeaf.eleE3x3, &b_eleE3x3);
   fChain->SetBranchAddress("eleE5x5", treeLeaf.eleE5x5, &b_eleE5x5);
   fChain->SetBranchAddress("eleE2x5Right", treeLeaf.eleE2x5Right, &b_eleE2x5Right);
   fChain->SetBranchAddress("eleE2x5Left", treeLeaf.eleE2x5Left, &b_eleE2x5Left);
   fChain->SetBranchAddress("eleE2x5Top", treeLeaf.eleE2x5Top, &b_eleE2x5Top);
   fChain->SetBranchAddress("eleE2x5Bottom", treeLeaf.eleE2x5Bottom, &b_eleE2x5Bottom);
   fChain->SetBranchAddress("eleRegrE", treeLeaf.eleRegrE, &b_eleRegrE);
   fChain->SetBranchAddress("eleRegrEerr", treeLeaf.eleRegrEerr, &b_eleRegrEerr);
   fChain->SetBranchAddress("elePhoRegrE", treeLeaf.elePhoRegrE, &b_elePhoRegrE);
   fChain->SetBranchAddress("elePhoRegrEerr", treeLeaf.elePhoRegrEerr, &b_elePhoRegrEerr);
   fChain->SetBranchAddress("eleSeedTime", treeLeaf.eleSeedTime, &b_eleSeedTime);
   fChain->SetBranchAddress("eleRecoFlag", treeLeaf.eleRecoFlag, &b_eleRecoFlag);
   fChain->SetBranchAddress("elePos", treeLeaf.elePos, &b_elePos);
   fChain->SetBranchAddress("eleGenIndex", treeLeaf.eleGenIndex, &b_eleGenIndex);
   fChain->SetBranchAddress("eleGenGMomPID", treeLeaf.eleGenGMomPID, &b_eleGenGMomPID);
   fChain->SetBranchAddress("eleGenMomPID", treeLeaf.eleGenMomPID, &b_eleGenMomPID);
   fChain->SetBranchAddress("eleGenMomPt", treeLeaf.eleGenMomPt, &b_eleGenMomPt);
   fChain->SetBranchAddress("eleIsoTrkDR03", treeLeaf.eleIsoTrkDR03, &b_eleIsoTrkDR03);
   fChain->SetBranchAddress("eleIsoEcalDR03", treeLeaf.eleIsoEcalDR03, &b_eleIsoEcalDR03);
   fChain->SetBranchAddress("eleIsoHcalDR03", treeLeaf.eleIsoHcalDR03, &b_eleIsoHcalDR03);
   fChain->SetBranchAddress("eleIsoHcalDR0312", treeLeaf.eleIsoHcalDR0312, &b_eleIsoHcalDR0312);
   fChain->SetBranchAddress("eleIsoTrkDR04", treeLeaf.eleIsoTrkDR04, &b_eleIsoTrkDR04);
   fChain->SetBranchAddress("eleIsoEcalDR04", treeLeaf.eleIsoEcalDR04, &b_eleIsoEcalDR04);
   fChain->SetBranchAddress("eleIsoHcalDR04", treeLeaf.eleIsoHcalDR04, &b_eleIsoHcalDR04);
   fChain->SetBranchAddress("eleIsoHcalDR0412", treeLeaf.eleIsoHcalDR0412, &b_eleIsoHcalDR0412);
   fChain->SetBranchAddress("eleMissHits", treeLeaf.eleMissHits, &b_eleMissHits);
   fChain->SetBranchAddress("eleConvDist", treeLeaf.eleConvDist, &b_eleConvDist);
   fChain->SetBranchAddress("eleConvDcot", treeLeaf.eleConvDcot, &b_eleConvDcot);
   fChain->SetBranchAddress("eleConvVtxFit", treeLeaf.eleConvVtxFit, &b_eleConvVtxFit);
   fChain->SetBranchAddress("eleIP3D", treeLeaf.eleIP3D, &b_eleIP3D);
   fChain->SetBranchAddress("eleIP3DErr", treeLeaf.eleIP3DErr, &b_eleIP3DErr);
   fChain->SetBranchAddress("eleIDMVANonTrig", treeLeaf.eleIDMVANonTrig, &b_eleIDMVANonTrig);
   fChain->SetBranchAddress("eleIDMVATrig", treeLeaf.eleIDMVATrig, &b_eleIDMVATrig);
   fChain->SetBranchAddress("eleIDMVATrigIDIso", treeLeaf.eleIDMVATrigIDIso, &b_eleIDMVATrigIDIso);
   fChain->SetBranchAddress("elePFChIso03", treeLeaf.elePFChIso03, &b_elePFChIso03);
   fChain->SetBranchAddress("elePFPhoIso03", treeLeaf.elePFPhoIso03, &b_elePFPhoIso03);
   fChain->SetBranchAddress("elePFNeuIso03", treeLeaf.elePFNeuIso03, &b_elePFNeuIso03);
   fChain->SetBranchAddress("elePFChIso04", treeLeaf.elePFChIso04, &b_elePFChIso04);
   fChain->SetBranchAddress("elePFPhoIso04", treeLeaf.elePFPhoIso04, &b_elePFPhoIso04);
   fChain->SetBranchAddress("elePFNeuIso04", treeLeaf.elePFNeuIso04, &b_elePFNeuIso04);
   fChain->SetBranchAddress("eleESEffSigmaRR", treeLeaf.eleESEffSigmaRR, &b_eleESEffSigmaRR);
   fChain->SetBranchAddress("nPho", &treeLeaf.nPho, &b_nPho);
   fChain->SetBranchAddress("phoTrg", treeLeaf.phoTrg, &b_phoTrg);
   fChain->SetBranchAddress("phoTrgFilter", treeLeaf.phoTrgFilter, &b_phoTrgFilter);
   fChain->SetBranchAddress("phoIsPhoton", treeLeaf.phoIsPhoton, &b_phoIsPhoton);
   fChain->SetBranchAddress("phoSCPos", treeLeaf.phoSCPos, &b_phoSCPos);
   fChain->SetBranchAddress("phoCaloPos", treeLeaf.phoCaloPos, &b_phoCaloPos);
   fChain->SetBranchAddress("phoE", treeLeaf.phoE, &b_phoE);
   fChain->SetBranchAddress("phoEt", treeLeaf.phoEt, &b_phoEt);
   fChain->SetBranchAddress("phoEta", treeLeaf.phoEta, &b_phoEta);
   fChain->SetBranchAddress("phoVtx", treeLeaf.phoVtx, &b_phoVtx);
   fChain->SetBranchAddress("phoPhi", treeLeaf.phoPhi, &b_phoPhi);
   fChain->SetBranchAddress("phoEtVtx", treeLeaf.phoEtVtx, &b_phoEtVtx);
   fChain->SetBranchAddress("phoEtaVtx", treeLeaf.phoEtaVtx, &b_phoEtaVtx);
   fChain->SetBranchAddress("phoPhiVtx", treeLeaf.phoPhiVtx, &b_phoPhiVtx);
   fChain->SetBranchAddress("phoR9", treeLeaf.phoR9, &b_phoR9);
   fChain->SetBranchAddress("phoTrkIsoHollowDR03", treeLeaf.phoTrkIsoHollowDR03, &b_phoTrkIsoHollowDR03);
   fChain->SetBranchAddress("phoEcalIsoDR03", treeLeaf.phoEcalIsoDR03, &b_phoEcalIsoDR03);
   fChain->SetBranchAddress("phoHcalIsoDR03", treeLeaf.phoHcalIsoDR03, &b_phoHcalIsoDR03);
   fChain->SetBranchAddress("phoHcalIsoDR0312", treeLeaf.phoHcalIsoDR0312, &b_phoHcalIsoDR0312);
   fChain->SetBranchAddress("phoTrkIsoHollowDR04", treeLeaf.phoTrkIsoHollowDR04, &b_phoTrkIsoHollowDR04);
   fChain->SetBranchAddress("phoCiCTrkIsoDR03", treeLeaf.phoCiCTrkIsoDR03, &b_phoCiCTrkIsoDR03);
   fChain->SetBranchAddress("phoCiCTrkIsoDR04", treeLeaf.phoCiCTrkIsoDR04, &b_phoCiCTrkIsoDR04);
   fChain->SetBranchAddress("phoCiCdRtoTrk", treeLeaf.phoCiCdRtoTrk, &b_phoCiCdRtoTrk);
   fChain->SetBranchAddress("phoEcalIsoDR04", treeLeaf.phoEcalIsoDR04, &b_phoEcalIsoDR04);
   fChain->SetBranchAddress("phoHcalIsoDR04", treeLeaf.phoHcalIsoDR04, &b_phoHcalIsoDR04);
   fChain->SetBranchAddress("phoHcalIsoDR0412", treeLeaf.phoHcalIsoDR0412, &b_phoHcalIsoDR0412);
   fChain->SetBranchAddress("phoHoverE", treeLeaf.phoHoverE, &b_phoHoverE);
   fChain->SetBranchAddress("phoHoverE12", treeLeaf.phoHoverE12, &b_phoHoverE12);
   fChain->SetBranchAddress("phoEleVeto", treeLeaf.phoEleVeto, &b_phoEleVeto);
   fChain->SetBranchAddress("phoSigmaIEtaIEta", treeLeaf.phoSigmaIEtaIEta, &b_phoSigmaIEtaIEta);
   fChain->SetBranchAddress("phoSigmaIEtaIPhi", treeLeaf.phoSigmaIEtaIPhi, &b_phoSigmaIEtaIPhi);
   fChain->SetBranchAddress("phoSigmaIPhiIPhi", treeLeaf.phoSigmaIPhiIPhi, &b_phoSigmaIPhiIPhi);
   fChain->SetBranchAddress("phoCiCPF4phopfIso03", treeLeaf.phoCiCPF4phopfIso03, &b_phoCiCPF4phopfIso03);
   fChain->SetBranchAddress("phoCiCPF4phopfIso04", treeLeaf.phoCiCPF4phopfIso04, &b_phoCiCPF4phopfIso04);
   fChain->SetBranchAddress("phoCiCPF4chgpfIso02", treeLeaf.phoCiCPF4chgpfIso02, &b_phoCiCPF4chgpfIso02);
   fChain->SetBranchAddress("phoCiCPF4chgpfIso03", treeLeaf.phoCiCPF4chgpfIso03, &b_phoCiCPF4chgpfIso03);
   fChain->SetBranchAddress("phoCiCPF4chgpfIso04", treeLeaf.phoCiCPF4chgpfIso04, &b_phoCiCPF4chgpfIso04);
   fChain->SetBranchAddress("phoEmax", treeLeaf.phoEmax, &b_phoEmax);
   fChain->SetBranchAddress("phoEtop", treeLeaf.phoEtop, &b_phoEtop);
   fChain->SetBranchAddress("phoEbottom", treeLeaf.phoEbottom, &b_phoEbottom);
   fChain->SetBranchAddress("phoEleft", treeLeaf.phoEleft, &b_phoEleft);
   fChain->SetBranchAddress("phoEright", treeLeaf.phoEright, &b_phoEright);
   fChain->SetBranchAddress("phoE3x3", treeLeaf.phoE3x3, &b_phoE3x3);
   fChain->SetBranchAddress("phoE3x1", treeLeaf.phoE3x1, &b_phoE3x1);
   fChain->SetBranchAddress("phoE1x3", treeLeaf.phoE1x3, &b_phoE1x3);
   fChain->SetBranchAddress("phoE5x5", treeLeaf.phoE5x5, &b_phoE5x5);
   fChain->SetBranchAddress("phoE1x5", treeLeaf.phoE1x5, &b_phoE1x5);
   fChain->SetBranchAddress("phoE2x2", treeLeaf.phoE2x2, &b_phoE2x2);
   fChain->SetBranchAddress("phoE2x5Max", treeLeaf.phoE2x5Max, &b_phoE2x5Max);
   fChain->SetBranchAddress("phoE2x5Right", treeLeaf.phoE2x5Right, &b_phoE2x5Right);
   fChain->SetBranchAddress("phoE2x5Left", treeLeaf.phoE2x5Left, &b_phoE2x5Left);
   fChain->SetBranchAddress("phoE2x5Top", treeLeaf.phoE2x5Top, &b_phoE2x5Top);
   fChain->SetBranchAddress("phoE2x5Bottom", treeLeaf.phoE2x5Bottom, &b_phoE2x5Bottom);
   fChain->SetBranchAddress("phoPFChIso", treeLeaf.phoPFChIso, &b_phoPFChIso);
   fChain->SetBranchAddress("phoPFPhoIso", treeLeaf.phoPFPhoIso, &b_phoPFPhoIso);
   fChain->SetBranchAddress("phoPFNeuIso", treeLeaf.phoPFNeuIso, &b_phoPFNeuIso);
   fChain->SetBranchAddress("phoRegrE", treeLeaf.phoRegrE, &b_phoRegrE);
   fChain->SetBranchAddress("phoRegrEerr", treeLeaf.phoRegrEerr, &b_phoRegrEerr);
   fChain->SetBranchAddress("phoSeedTime", treeLeaf.phoSeedTime, &b_phoSeedTime);
   fChain->SetBranchAddress("phoSeedDetId1", treeLeaf.phoSeedDetId1, &b_phoSeedDetId1);
   fChain->SetBranchAddress("phoSeedDetId2", treeLeaf.phoSeedDetId2, &b_phoSeedDetId2);
   fChain->SetBranchAddress("phoRecoFlag", treeLeaf.phoRecoFlag, &b_phoRecoFlag);
   fChain->SetBranchAddress("phoPos", treeLeaf.phoPos, &b_phoPos);
   fChain->SetBranchAddress("phoGenIndex", treeLeaf.phoGenIndex, &b_phoGenIndex);
   fChain->SetBranchAddress("phoGenGMomPID", treeLeaf.phoGenGMomPID, &b_phoGenGMomPID);
   fChain->SetBranchAddress("phoGenMomPID", treeLeaf.phoGenMomPID, &b_phoGenMomPID);
   fChain->SetBranchAddress("phoGenMomPt", treeLeaf.phoGenMomPt, &b_phoGenMomPt);
   fChain->SetBranchAddress("phoSCE", treeLeaf.phoSCE, &b_phoSCE);
   fChain->SetBranchAddress("phoSCRawE", treeLeaf.phoSCRawE, &b_phoSCRawE);
   fChain->SetBranchAddress("phoESEn", treeLeaf.phoESEn, &b_phoESEn);
   fChain->SetBranchAddress("phoSCEt", treeLeaf.phoSCEt, &b_phoSCEt);
   fChain->SetBranchAddress("phoSCEta", treeLeaf.phoSCEta, &b_phoSCEta);
   fChain->SetBranchAddress("phoSCPhi", treeLeaf.phoSCPhi, &b_phoSCPhi);
   fChain->SetBranchAddress("phoSCEtaWidth", treeLeaf.phoSCEtaWidth, &b_phoSCEtaWidth);
   fChain->SetBranchAddress("phoSCPhiWidth", treeLeaf.phoSCPhiWidth, &b_phoSCPhiWidth);
   fChain->SetBranchAddress("phoSCBrem", treeLeaf.phoSCBrem, &b_phoSCBrem);
   fChain->SetBranchAddress("phoOverlap", treeLeaf.phoOverlap, &b_phoOverlap);
   fChain->SetBranchAddress("phohasPixelSeed", treeLeaf.phohasPixelSeed, &b_phohasPixelSeed);
   fChain->SetBranchAddress("pho_hasConvPf", treeLeaf.pho_hasConvPf, &b_pho_hasConvPf);
   fChain->SetBranchAddress("pho_hasSLConvPf", treeLeaf.pho_hasSLConvPf, &b_pho_hasSLConvPf);
   fChain->SetBranchAddress("pho_pfconvVtxZ", treeLeaf.pho_pfconvVtxZ, &b_pho_pfconvVtxZ);
   fChain->SetBranchAddress("pho_pfconvVtxZErr", treeLeaf.pho_pfconvVtxZErr, &b_pho_pfconvVtxZErr);
   fChain->SetBranchAddress("pho_nSLConv", treeLeaf.pho_nSLConv, &b_pho_nSLConv);
   fChain->SetBranchAddress("pho_pfSLConvPos", treeLeaf.pho_pfSLConvPos, &b_pho_pfSLConvPos);
   fChain->SetBranchAddress("pho_pfSLConvVtxZ", treeLeaf.pho_pfSLConvVtxZ, &b_pho_pfSLConvVtxZ);
   fChain->SetBranchAddress("phoIsConv", treeLeaf.phoIsConv, &b_phoIsConv);
   fChain->SetBranchAddress("phoNConv", treeLeaf.phoNConv, &b_phoNConv);
   fChain->SetBranchAddress("phoConvInvMass", treeLeaf.phoConvInvMass, &b_phoConvInvMass);
   fChain->SetBranchAddress("phoConvCotTheta", treeLeaf.phoConvCotTheta, &b_phoConvCotTheta);
   fChain->SetBranchAddress("phoConvEoverP", treeLeaf.phoConvEoverP, &b_phoConvEoverP);
   fChain->SetBranchAddress("phoConvZofPVfromTrks", treeLeaf.phoConvZofPVfromTrks, &b_phoConvZofPVfromTrks);
   fChain->SetBranchAddress("phoConvMinDist", treeLeaf.phoConvMinDist, &b_phoConvMinDist);
   fChain->SetBranchAddress("phoConvdPhiAtVtx", treeLeaf.phoConvdPhiAtVtx, &b_phoConvdPhiAtVtx);
   fChain->SetBranchAddress("phoConvdPhiAtCalo", treeLeaf.phoConvdPhiAtCalo, &b_phoConvdPhiAtCalo);
   fChain->SetBranchAddress("phoConvdEtaAtCalo", treeLeaf.phoConvdEtaAtCalo, &b_phoConvdEtaAtCalo);
   fChain->SetBranchAddress("phoConvTrkd0", treeLeaf.phoConvTrkd0, &b_phoConvTrkd0);
   fChain->SetBranchAddress("phoConvTrkPin", treeLeaf.phoConvTrkPin, &b_phoConvTrkPin);
   fChain->SetBranchAddress("phoConvTrkPout", treeLeaf.phoConvTrkPout, &b_phoConvTrkPout);
   fChain->SetBranchAddress("phoConvTrkdz", treeLeaf.phoConvTrkdz, &b_phoConvTrkdz);
   fChain->SetBranchAddress("phoConvTrkdzErr", treeLeaf.phoConvTrkdzErr, &b_phoConvTrkdzErr);
   fChain->SetBranchAddress("phoConvChi2", treeLeaf.phoConvChi2, &b_phoConvChi2);
   fChain->SetBranchAddress("phoConvChi2Prob", treeLeaf.phoConvChi2Prob, &b_phoConvChi2Prob);
   fChain->SetBranchAddress("phoConvNTrks", treeLeaf.phoConvNTrks, &b_phoConvNTrks);
   fChain->SetBranchAddress("phoConvCharge", treeLeaf.phoConvCharge, &b_phoConvCharge);
   fChain->SetBranchAddress("phoConvValidVtx", treeLeaf.phoConvValidVtx, &b_phoConvValidVtx);
   fChain->SetBranchAddress("phoConvLikeLihood", treeLeaf.phoConvLikeLihood, &b_phoConvLikeLihood);
   fChain->SetBranchAddress("phoConvP4", treeLeaf.phoConvP4, &b_phoConvP4);
   fChain->SetBranchAddress("phoConvVtx", treeLeaf.phoConvVtx, &b_phoConvVtx);
   fChain->SetBranchAddress("phoConvVtxErr", treeLeaf.phoConvVtxErr, &b_phoConvVtxErr);
   fChain->SetBranchAddress("phoConvPairMomentum", treeLeaf.phoConvPairMomentum, &b_phoConvPairMomentum);
   fChain->SetBranchAddress("phoConvRefittedMomentum", treeLeaf.phoConvRefittedMomentum, &b_phoConvRefittedMomentum);
   fChain->SetBranchAddress("SingleLegConv", treeLeaf.SingleLegConv, &b_SingleLegConv);
   fChain->SetBranchAddress("phoPFConvVtx", treeLeaf.phoPFConvVtx, &b_phoPFConvVtx);
   fChain->SetBranchAddress("phoPFConvMom", treeLeaf.phoPFConvMom, &b_phoPFConvMom);
   fChain->SetBranchAddress("phoESEffSigmaRR", treeLeaf.phoESEffSigmaRR, &b_phoESEffSigmaRR);
   fChain->SetBranchAddress("nMu", &treeLeaf.nMu, &b_nMu);
   fChain->SetBranchAddress("muTrg", treeLeaf.muTrg, &b_muTrg);
   fChain->SetBranchAddress("muEta", treeLeaf.muEta, &b_muEta);
   fChain->SetBranchAddress("muPhi", treeLeaf.muPhi, &b_muPhi);
   fChain->SetBranchAddress("muCharge", treeLeaf.muCharge, &b_muCharge);
   fChain->SetBranchAddress("muPt", treeLeaf.muPt, &b_muPt);
   fChain->SetBranchAddress("muPz", treeLeaf.muPz, &b_muPz);
   fChain->SetBranchAddress("muVtx", treeLeaf.muVtx, &b_muVtx);
   fChain->SetBranchAddress("muVtxGlb", treeLeaf.muVtxGlb, &b_muVtxGlb);
   fChain->SetBranchAddress("muGenIndex", treeLeaf.muGenIndex, &b_muGenIndex);
   //fChain->SetBranchAddress("mucktPt_", mucktPt_, &b_mucktPt_);
   //fChain->SetBranchAddress("mucktPtErr_", mucktPtErr_, &b_mucktPtErr_);
   //fChain->SetBranchAddress("mucktdxy_", mucktdxy_, &b_mucktdxy_);
   //fChain->SetBranchAddress("mucktdz_", mucktdz_, &b_mucktdz_);
   fChain->SetBranchAddress("muIsoTrk", treeLeaf.muIsoTrk, &b_muIsoTrk);
   fChain->SetBranchAddress("muIsoCalo", treeLeaf.muIsoCalo, &b_muIsoCalo);
   fChain->SetBranchAddress("muIsoEcal", treeLeaf.muIsoEcal, &b_muIsoEcal);
   fChain->SetBranchAddress("muIsoHcal", treeLeaf.muIsoHcal, &b_muIsoHcal);
   fChain->SetBranchAddress("muChi2NDF", treeLeaf.muChi2NDF, &b_muChi2NDF);
   fChain->SetBranchAddress("muInnerChi2NDF", treeLeaf.muInnerChi2NDF, &b_muInnerChi2NDF);
   fChain->SetBranchAddress("muPFIsoR04_CH", treeLeaf.muPFIsoR04_CH, &b_muPFIsoR04_CH);
   fChain->SetBranchAddress("muPFIsoR04_NH", treeLeaf.muPFIsoR04_NH, &b_muPFIsoR04_NH);
   fChain->SetBranchAddress("muPFIsoR04_Pho", treeLeaf.muPFIsoR04_Pho, &b_muPFIsoR04_Pho);
   fChain->SetBranchAddress("muPFIsoR04_PU", treeLeaf.muPFIsoR04_PU, &b_muPFIsoR04_PU);
   fChain->SetBranchAddress("muPFIsoR04_CPart", treeLeaf.muPFIsoR04_CPart, &b_muPFIsoR04_CPart);
   fChain->SetBranchAddress("muPFIsoR04_NHHT", treeLeaf.muPFIsoR04_NHHT, &b_muPFIsoR04_NHHT);
   fChain->SetBranchAddress("muPFIsoR04_PhoHT", treeLeaf.muPFIsoR04_PhoHT, &b_muPFIsoR04_PhoHT);
   fChain->SetBranchAddress("muPFIsoR03_CH", treeLeaf.muPFIsoR03_CH, &b_muPFIsoR03_CH);
   fChain->SetBranchAddress("muPFIsoR03_NH", treeLeaf.muPFIsoR03_NH, &b_muPFIsoR03_NH);
   fChain->SetBranchAddress("muPFIsoR03_Pho", treeLeaf.muPFIsoR03_Pho, &b_muPFIsoR03_Pho);
   fChain->SetBranchAddress("muPFIsoR03_PU", treeLeaf.muPFIsoR03_PU, &b_muPFIsoR03_PU);
   fChain->SetBranchAddress("muPFIsoR03_CPart", treeLeaf.muPFIsoR03_CPart, &b_muPFIsoR03_CPart);
   fChain->SetBranchAddress("muPFIsoR03_NHHT", treeLeaf.muPFIsoR03_NHHT, &b_muPFIsoR03_NHHT);
   fChain->SetBranchAddress("muPFIsoR03_PhoHT", treeLeaf.muPFIsoR03_PhoHT, &b_muPFIsoR03_PhoHT);
   fChain->SetBranchAddress("muType", treeLeaf.muType, &b_muType);
   fChain->SetBranchAddress("muID", treeLeaf.muID, &b_muID);
   fChain->SetBranchAddress("muD0", treeLeaf.muD0, &b_muD0);
   fChain->SetBranchAddress("muDz", treeLeaf.muDz, &b_muDz);
   fChain->SetBranchAddress("muD0GV", treeLeaf.muD0GV, &b_muD0GV);
   fChain->SetBranchAddress("muDzGV", treeLeaf.muDzGV, &b_muDzGV);
   fChain->SetBranchAddress("muD0Vtx", treeLeaf.muD0Vtx, &b_muD0Vtx);
   fChain->SetBranchAddress("muDzVtx", treeLeaf.muDzVtx, &b_muDzVtx);
   fChain->SetBranchAddress("muInnerD0", treeLeaf.muInnerD0, &b_muInnerD0);
   fChain->SetBranchAddress("muInnerDz", treeLeaf.muInnerDz, &b_muInnerDz);
   fChain->SetBranchAddress("muInnerD0GV", treeLeaf.muInnerD0GV, &b_muInnerD0GV);
   fChain->SetBranchAddress("muInnerDzGV", treeLeaf.muInnerDzGV, &b_muInnerDzGV);
   fChain->SetBranchAddress("muNumberOfValidTrkLayers", treeLeaf.muNumberOfValidTrkLayers, &b_muNumberOfValidTrkLayers);
   fChain->SetBranchAddress("muNumberOfValidTrkHits", treeLeaf.muNumberOfValidTrkHits, &b_muNumberOfValidTrkHits);
   fChain->SetBranchAddress("muNumberOfValidPixelLayers", treeLeaf.muNumberOfValidPixelLayers, &b_muNumberOfValidPixelLayers);
   fChain->SetBranchAddress("muNumberOfValidPixelHits", treeLeaf.muNumberOfValidPixelHits, &b_muNumberOfValidPixelHits);
   fChain->SetBranchAddress("muNumberOfValidMuonHits", treeLeaf.muNumberOfValidMuonHits, &b_muNumberOfValidMuonHits);
   fChain->SetBranchAddress("muStations", treeLeaf.muStations, &b_muStations);
   fChain->SetBranchAddress("muChambers", treeLeaf.muChambers, &b_muChambers);
   fChain->SetBranchAddress("muIP3D", treeLeaf.muIP3D, &b_muIP3D);
   fChain->SetBranchAddress("muIP3DErr", treeLeaf.muIP3DErr, &b_muIP3DErr);
   fChain->SetBranchAddress("nPFEle_", &treeLeaf.nPFEle_, &b_nPFEle_);
   fChain->SetBranchAddress("PFElePt_", treeLeaf.PFElePt_, &b_PFElePt_);
   fChain->SetBranchAddress("PFEleEta_", treeLeaf.PFEleEta_, &b_PFEleEta_);
   fChain->SetBranchAddress("PFElePhi_", treeLeaf.PFElePhi_, &b_PFElePhi_);
   fChain->SetBranchAddress("PFEleEn_", treeLeaf.PFEleEn_, &b_PFEleEn_);
   fChain->SetBranchAddress("PFEleCharge", treeLeaf.PFEleCharge, &b_PFEleCharge);
   fChain->SetBranchAddress("rho25", &treeLeaf.rho25, &b_rho25);
   fChain->SetBranchAddress("rho25_neu", &treeLeaf.rho25_neu, &b_rho25_neu);
   fChain->SetBranchAddress("rho25_muPFiso", &treeLeaf.rho25_muPFiso, &b_rho25_muPFiso);
   fChain->SetBranchAddress("rho25_elePFiso", &treeLeaf.rho25_elePFiso, &b_rho25_elePFiso);
   fChain->SetBranchAddress("rho2011", &treeLeaf.rho2011, &b_rho2011);
   fChain->SetBranchAddress("rho2012", &treeLeaf.rho2012, &b_rho2012);
   fChain->SetBranchAddress("nJet", &treeLeaf.nJet, &b_nJet);
   fChain->SetBranchAddress("jetTrg", treeLeaf.jetTrg, &b_jetTrg);
   fChain->SetBranchAddress("jetEn", treeLeaf.jetEn, &b_jetEn);
   fChain->SetBranchAddress("jetPt", treeLeaf.jetPt, &b_jetPt);
   fChain->SetBranchAddress("jetEta", treeLeaf.jetEta, &b_jetEta);
   fChain->SetBranchAddress("jetPhi", treeLeaf.jetPhi, &b_jetPhi);
   fChain->SetBranchAddress("jetCharge", treeLeaf.jetCharge, &b_jetCharge);
   fChain->SetBranchAddress("jetEt", treeLeaf.jetEt, &b_jetEt);
   fChain->SetBranchAddress("jetRawPt", treeLeaf.jetRawPt, &b_jetRawPt);
   fChain->SetBranchAddress("jetRawEn", treeLeaf.jetRawEn, &b_jetRawEn);
   fChain->SetBranchAddress("jetArea", treeLeaf.jetArea, &b_jetArea);
   fChain->SetBranchAddress("jetCHF", treeLeaf.jetCHF, &b_jetCHF);
   fChain->SetBranchAddress("jetNHF", treeLeaf.jetNHF, &b_jetNHF);
   fChain->SetBranchAddress("jetCEF", treeLeaf.jetCEF, &b_jetCEF);
   fChain->SetBranchAddress("jetNEF", treeLeaf.jetNEF, &b_jetNEF);
   fChain->SetBranchAddress("jetNCH", treeLeaf.jetNCH, &b_jetNCH);
   fChain->SetBranchAddress("jetHFHAE", treeLeaf.jetHFHAE, &b_jetHFHAE);
   fChain->SetBranchAddress("jetHFEME", treeLeaf.jetHFEME, &b_jetHFEME);
   fChain->SetBranchAddress("jetNConstituents", treeLeaf.jetNConstituents, &b_jetNConstituents);
   fChain->SetBranchAddress("jetCombinedSecondaryVtxBJetTags", treeLeaf.jetCombinedSecondaryVtxBJetTags, &b_jetCombinedSecondaryVtxBJetTags);
   fChain->SetBranchAddress("jetCombinedSecondaryVtxMVABJetTags", treeLeaf.jetCombinedSecondaryVtxMVABJetTags, &b_jetCombinedSecondaryVtxMVABJetTags);
   fChain->SetBranchAddress("jetJetProbabilityBJetTags", treeLeaf.jetJetProbabilityBJetTags, &b_jetJetProbabilityBJetTags);
   fChain->SetBranchAddress("jetJetBProbabilityBJetTags", treeLeaf.jetJetBProbabilityBJetTags, &b_jetJetBProbabilityBJetTags);
   fChain->SetBranchAddress("jetTrackCountingHighPurBJetTags", treeLeaf.jetTrackCountingHighPurBJetTags, &b_jetTrackCountingHighPurBJetTags);
   fChain->SetBranchAddress("jetBetaStar", treeLeaf.jetBetaStar, &b_jetBetaStar);
   fChain->SetBranchAddress("jetPFLooseId", treeLeaf.jetPFLooseId, &b_jetPFLooseId);
   fChain->SetBranchAddress("jetDRMean", treeLeaf.jetDRMean, &b_jetDRMean);
   fChain->SetBranchAddress("jetDR2Mean", treeLeaf.jetDR2Mean, &b_jetDR2Mean);
   fChain->SetBranchAddress("jetDZ", treeLeaf.jetDZ, &b_jetDZ);
   fChain->SetBranchAddress("jetFrac01", treeLeaf.jetFrac01, &b_jetFrac01);
   fChain->SetBranchAddress("jetFrac02", treeLeaf.jetFrac02, &b_jetFrac02);
   fChain->SetBranchAddress("jetFrac03", treeLeaf.jetFrac03, &b_jetFrac03);
   fChain->SetBranchAddress("jetFrac04", treeLeaf.jetFrac04, &b_jetFrac04);
   fChain->SetBranchAddress("jetFrac05", treeLeaf.jetFrac05, &b_jetFrac05);
   fChain->SetBranchAddress("jetFrac06", treeLeaf.jetFrac06, &b_jetFrac06);
   fChain->SetBranchAddress("jetFrac07", treeLeaf.jetFrac07, &b_jetFrac07);
   fChain->SetBranchAddress("jetBeta", treeLeaf.jetBeta, &b_jetBeta);
   fChain->SetBranchAddress("jetBetaStarCMG", treeLeaf.jetBetaStarCMG, &b_jetBetaStarCMG);
   fChain->SetBranchAddress("jetBetaStarClassic", treeLeaf.jetBetaStarClassic, &b_jetBetaStarClassic);
   fChain->SetBranchAddress("jetBetaExt", treeLeaf.jetBetaExt, &b_jetBetaExt);
   fChain->SetBranchAddress("jetBetaStarCMGExt", treeLeaf.jetBetaStarCMGExt, &b_jetBetaStarCMGExt);
   fChain->SetBranchAddress("jetBetaStarClassicExt", treeLeaf.jetBetaStarClassicExt, &b_jetBetaStarClassicExt);
   fChain->SetBranchAddress("jetNNeutrals", treeLeaf.jetNNeutrals, &b_jetNNeutrals);
   fChain->SetBranchAddress("jetNCharged", treeLeaf.jetNCharged, &b_jetNCharged);
   fChain->SetBranchAddress("jetMVAs", treeLeaf.jetMVAs, &b_jetMVAs);
   fChain->SetBranchAddress("jetWPLevels", treeLeaf.jetWPLevels, &b_jetWPLevels);
   fChain->SetBranchAddress("jetMVAsExt", treeLeaf.jetMVAsExt, &b_jetMVAsExt);
   fChain->SetBranchAddress("jetWPLevelsExt", treeLeaf.jetWPLevelsExt, &b_jetWPLevelsExt);
   fChain->SetBranchAddress("jetPartonID", treeLeaf.jetPartonID, &b_jetPartonID);
   fChain->SetBranchAddress("jetGenJetIndex", treeLeaf.jetGenJetIndex, &b_jetGenJetIndex);
   fChain->SetBranchAddress("jetGenJetEn", treeLeaf.jetGenJetEn, &b_jetGenJetEn);
   fChain->SetBranchAddress("jetGenJetPt", treeLeaf.jetGenJetPt, &b_jetGenJetPt);
   fChain->SetBranchAddress("jetGenJetEta", treeLeaf.jetGenJetEta, &b_jetGenJetEta);
   fChain->SetBranchAddress("jetGenJetPhi", treeLeaf.jetGenJetPhi, &b_jetGenJetPhi);
   fChain->SetBranchAddress("jetGenPartonID", treeLeaf.jetGenPartonID, &b_jetGenPartonID);
   fChain->SetBranchAddress("jetGenEn", treeLeaf.jetGenEn, &b_jetGenEn);
   fChain->SetBranchAddress("jetGenPt", treeLeaf.jetGenPt, &b_jetGenPt);
   fChain->SetBranchAddress("jetGenEta", treeLeaf.jetGenEta, &b_jetGenEta);
   fChain->SetBranchAddress("jetGenPhi", treeLeaf.jetGenPhi, &b_jetGenPhi);
   fChain->SetBranchAddress("nLowPtJet", &treeLeaf.nLowPtJet, &b_nLowPtJet);
   fChain->SetBranchAddress("jetLowPtEn", treeLeaf.jetLowPtEn, &b_jetLowPtEn);
   fChain->SetBranchAddress("jetLowPtPt", treeLeaf.jetLowPtPt, &b_jetLowPtPt);
   fChain->SetBranchAddress("jetLowPtEta", treeLeaf.jetLowPtEta, &b_jetLowPtEta);
   fChain->SetBranchAddress("jetLowPtPhi", treeLeaf.jetLowPtPhi, &b_jetLowPtPhi);
   fChain->SetBranchAddress("jetLowPtCharge", treeLeaf.jetLowPtCharge, &b_jetLowPtCharge);
   fChain->SetBranchAddress("jetLowPtEt", treeLeaf.jetLowPtEt, &b_jetLowPtEt);
   fChain->SetBranchAddress("jetLowPtRawPt", treeLeaf.jetLowPtRawPt, &b_jetLowPtRawPt);
   fChain->SetBranchAddress("jetLowPtRawEn", treeLeaf.jetLowPtRawEn, &b_jetLowPtRawEn);
   fChain->SetBranchAddress("jetLowPtArea", treeLeaf.jetLowPtArea, &b_jetLowPtArea);
   fChain->SetBranchAddress("jetLowPtPartonID", treeLeaf.jetLowPtPartonID, &b_jetLowPtPartonID);
   fChain->SetBranchAddress("jetLowPtGenJetEn", treeLeaf.jetLowPtGenJetEn, &b_jetLowPtGenJetEn);
   fChain->SetBranchAddress("jetLowPtGenJetPt", treeLeaf.jetLowPtGenJetPt, &b_jetLowPtGenJetPt);
   fChain->SetBranchAddress("jetLowPtGenJetEta", treeLeaf.jetLowPtGenJetEta, &b_jetLowPtGenJetEta);
   fChain->SetBranchAddress("jetLowPtGenJetPhi", treeLeaf.jetLowPtGenJetPhi, &b_jetLowPtGenJetPhi);
   fChain->SetBranchAddress("jetLowPtGenPartonID", treeLeaf.jetLowPtGenPartonID, &b_jetLowPtGenPartonID);
   fChain->SetBranchAddress("jetLowPtGenEn", treeLeaf.jetLowPtGenEn, &b_jetLowPtGenEn);
   fChain->SetBranchAddress("jetLowPtGenPt", treeLeaf.jetLowPtGenPt, &b_jetLowPtGenPt);
   fChain->SetBranchAddress("jetLowPtGenEta", treeLeaf.jetLowPtGenEta, &b_jetLowPtGenEta);
   fChain->SetBranchAddress("jetLowPtGenPhi", treeLeaf.jetLowPtGenPhi, &b_jetLowPtGenPhi);
   fChain->SetBranchAddress("nConv", &treeLeaf.nConv, &b_nConv);
   fChain->SetBranchAddress("convP4", treeLeaf.convP4, &b_convP4);
   fChain->SetBranchAddress("convVtx", treeLeaf.convVtx, &b_convVtx);
   fChain->SetBranchAddress("convVtxErr", treeLeaf.convVtxErr, &b_convVtxErr);
   fChain->SetBranchAddress("convPairMomentum", treeLeaf.convPairMomentum, &b_convPairMomentum);
   fChain->SetBranchAddress("convRefittedMomentum", treeLeaf.convRefittedMomentum, &b_convRefittedMomentum);
   fChain->SetBranchAddress("convNTracks", treeLeaf.convNTracks, &b_convNTracks);
   fChain->SetBranchAddress("convPairInvMass", treeLeaf.convPairInvMass, &b_convPairInvMass);
   fChain->SetBranchAddress("convPairCotThetaSep", treeLeaf.convPairCotThetaSep, &b_convPairCotThetaSep);
   fChain->SetBranchAddress("convEoverP", treeLeaf.convEoverP, &b_convEoverP);
   fChain->SetBranchAddress("convDistOfMinApproach", treeLeaf.convDistOfMinApproach, &b_convDistOfMinApproach);
   fChain->SetBranchAddress("convDPhiTrksAtVtx", treeLeaf.convDPhiTrksAtVtx, &b_convDPhiTrksAtVtx);
   fChain->SetBranchAddress("convDPhiTrksAtEcal", treeLeaf.convDPhiTrksAtEcal, &b_convDPhiTrksAtEcal);
   fChain->SetBranchAddress("convDEtaTrksAtEcal", treeLeaf.convDEtaTrksAtEcal, &b_convDEtaTrksAtEcal);
   fChain->SetBranchAddress("convDxy", treeLeaf.convDxy, &b_convDxy);
   fChain->SetBranchAddress("convDz", treeLeaf.convDz, &b_convDz);
   fChain->SetBranchAddress("convLxy", treeLeaf.convLxy, &b_convLxy);
   fChain->SetBranchAddress("convLz", treeLeaf.convLz, &b_convLz);
   fChain->SetBranchAddress("convZofPrimVtxFromTrks", treeLeaf.convZofPrimVtxFromTrks, &b_convZofPrimVtxFromTrks);
   fChain->SetBranchAddress("convNHitsBeforeVtx", treeLeaf.convNHitsBeforeVtx, &b_convNHitsBeforeVtx);
   fChain->SetBranchAddress("convNSharedHits", treeLeaf.convNSharedHits, &b_convNSharedHits);
   fChain->SetBranchAddress("convValidVtx", treeLeaf.convValidVtx, &b_convValidVtx);
   fChain->SetBranchAddress("convMVALikelihood", treeLeaf.convMVALikelihood, &b_convMVALikelihood);
   fChain->SetBranchAddress("convChi2", treeLeaf.convChi2, &b_convChi2);
   fChain->SetBranchAddress("convChi2Probability", treeLeaf.convChi2Probability, &b_convChi2Probability);
   fChain->SetBranchAddress("convTk1Dz", treeLeaf.convTk1Dz, &b_convTk1Dz);
   fChain->SetBranchAddress("convTk2Dz", treeLeaf.convTk2Dz, &b_convTk2Dz);
   fChain->SetBranchAddress("convTk1DzErr", treeLeaf.convTk1DzErr, &b_convTk1DzErr);
   fChain->SetBranchAddress("convTk2DzErr", treeLeaf.convTk2DzErr, &b_convTk2DzErr);
   fChain->SetBranchAddress("convCh1Ch2", treeLeaf.convCh1Ch2, &b_convCh1Ch2);
   fChain->SetBranchAddress("convTk1D0", treeLeaf.convTk1D0, &b_convTk1D0);
   fChain->SetBranchAddress("convTk1Pout", treeLeaf.convTk1Pout, &b_convTk1Pout);
   fChain->SetBranchAddress("convTk1Pin", treeLeaf.convTk1Pin, &b_convTk1Pin);
   fChain->SetBranchAddress("convTk2D0", treeLeaf.convTk2D0, &b_convTk2D0);
   fChain->SetBranchAddress("convTk2Pout", treeLeaf.convTk2Pout, &b_convTk2Pout);
   fChain->SetBranchAddress("convTk2Pin", treeLeaf.convTk2Pin, &b_convTk2Pin);
}
