#include "TEventTree.h"
#include "TTree.h"
#include "../Configuration/TConfiguration.h"

TEventTree::TEventTree(TTree *tree)
{
   Init(tree);
 //  listOfBranches = tree->GetListOfBranches();
}

TEventTree::~TEventTree()
{
   if (!fChain) return;
   //delete fChain->GetCurrentFile();
}

void TEventTree::GetEntryNeededBranchesOnly(int channel, int sample, Long64_t entry)
{
  GetEntryCommon(entry);
  if (channel==config.MUON || channel==config.BOTH_CHANNELS) GetEntryMuoSpecific(entry);
  if (channel==config.ELECTRON || channel==config.BOTH_CHANNELS) GetEntryEleSpecific(entry);
  GetEntryRandCone(entry);
  if (sample!=config.DATA) GetEntryMCSpecific(entry);
  if (sample==config.SIGMC) GetEntrySIGMCSpecific(entry);
}

void TEventTree::GetEntryCommon(Long64_t entry)
{
   b_run->GetEntry(entry);
   b_event->GetEntry(entry);
   b_isData->GetEntry(entry);
   b_nHLT->GetEntry(entry);
   b_HLT->GetEntry(entry);
   b_HLTIndex->GetEntry(entry);
   b_IsVtxGood->GetEntry(entry);

   b_pfMET->GetEntry(entry);
   b_pfMETPhi->GetEntry(entry);
   b_metFilters->GetEntry(entry);

   b_nPho->GetEntry(entry);
   b_phoEt->GetEntry(entry);
   b_phoEta->GetEntry(entry);
   b_phoPhi->GetEntry(entry);
   b_phoR9->GetEntry(entry);
   b_phoTrkIsoHollowDR04->GetEntry(entry);
   b_phoEcalIsoDR04->GetEntry(entry);
   b_phoHcalIsoDR04->GetEntry(entry);
   b_phoHoverE->GetEntry(entry);
   b_phoHoverE12->GetEntry(entry);
   b_phoEleVeto->GetEntry(entry);
   b_phoSigmaIEtaIEta->GetEntry(entry);

   b_phoPFChIso->GetEntry(entry);
   b_phoPFPhoIso->GetEntry(entry);
   b_phoPFNeuIso->GetEntry(entry);

   b_phoSCRChIso->GetEntry(entry);
   b_phoSCRPhoIso->GetEntry(entry);
   b_phoSCRNeuIso->GetEntry(entry);

   b_phoSCRChIso04->GetEntry(entry);
   b_phoSCRPhoIso04->GetEntry(entry);
   b_phoSCRNeuIso04->GetEntry(entry);

   b_phoSCEt->GetEntry(entry);
   b_phoSCEta->GetEntry(entry);
   b_phoSCPhi->GetEntry(entry);
   b_phohasPixelSeed->GetEntry(entry);

   b_rho2011->GetEntry(entry);
   b_rho2012->GetEntry(entry);

   b_nJet->GetEntry(entry);
   b_jetPt->GetEntry(entry);
   b_jetEta->GetEntry(entry);
   b_jetPhi->GetEntry(entry);
   b_jetRawPt->GetEntry(entry);
   b_jetRawEn->GetEntry(entry);

}

void TEventTree::GetEntryMuoSpecific(Long64_t entry)
{
   b_nMu->GetEntry(entry);
   b_muTrg->GetEntry(entry);
   b_muEta->GetEntry(entry);
   b_muPhi->GetEntry(entry);
   b_muPt->GetEntry(entry);
   b_muChi2NDF->GetEntry(entry);
   b_muPFIsoR04_CH->GetEntry(entry);
   b_muPFIsoR04_NH->GetEntry(entry);
   b_muPFIsoR04_Pho->GetEntry(entry);
   b_muPFIsoR04_PU->GetEntry(entry);
   b_muType->GetEntry(entry);
   b_muD0->GetEntry(entry);
   b_muDz->GetEntry(entry);
   b_muInnerD0GV->GetEntry(entry);
   b_muInnerDzGV->GetEntry(entry);
   b_muNumberOfValidTrkLayers->GetEntry(entry);
   b_muNumberOfValidTrkHits->GetEntry(entry);
   b_muNumberOfValidPixelHits->GetEntry(entry);
   b_muNumberOfValidMuonHits->GetEntry(entry);
   b_muStations->GetEntry(entry);
   b_muIsoTrk->GetEntry(entry);
   b_muIsoEcal->GetEntry(entry);
   b_muIsoHcal->GetEntry(entry);
}

void TEventTree::GetEntryEleSpecific(Long64_t entry)
{
   b_nEle->GetEntry(entry);
   b_eleTrg->GetEntry(entry);
   b_elePt->GetEntry(entry);
   b_elePhi->GetEntry(entry);
   b_eleEta->GetEntry(entry);
   b_eleSCPhi->GetEntry(entry);
   b_eleSCEta->GetEntry(entry);
   b_eledEtaAtVtx->GetEntry(entry);
   b_eledPhiAtVtx->GetEntry(entry);
   b_eleSigmaIEtaIEta->GetEntry(entry);
   b_eleHoverE->GetEntry(entry);
   b_eleHoverE12->GetEntry(entry);
   b_elePin->GetEntry(entry);
   b_eleD0Vtx->GetEntry(entry);
   b_eleDzVtx->GetEntry(entry);
   b_eleEcalEn->GetEntry(entry);
   b_eleConvVtxFit->GetEntry(entry);
   b_eleMissHits->GetEntry(entry);
   b_elePFChIso03->GetEntry(entry);
   b_elePFPhoIso03->GetEntry(entry);
   b_elePFNeuIso03->GetEntry(entry);
}

void TEventTree::GetEntryRandCone(Long64_t entry)
{
   b_phoRandConeChIso->GetEntry(entry);   //!
   b_phoRandConePhoIso->GetEntry(entry);   //!
   b_phoRandConeNeuIso->GetEntry(entry);   //!
   b_phoRandConeChIso04->GetEntry(entry);   //!
   b_phoRandConePhoIso04->GetEntry(entry);   //!
   b_phoRandConeNeuIso04->GetEntry(entry);   //!
}

void TEventTree::GetEntryMCSpecific(Long64_t entry)
{

   b_nMC->GetEntry(entry); 
   b_mcPID->GetEntry(entry); 
   b_mcMomPID->GetEntry(entry); 
   b_mcGMomPID->GetEntry(entry); 
   b_mcPt->GetEntry(entry);
   b_mcEta->GetEntry(entry);
   b_mcPhi->GetEntry(entry);
   b_mcMomPt->GetEntry(entry);
   b_mcMomEta->GetEntry(entry);
   b_mcMomPhi->GetEntry(entry);
   b_mcE->GetEntry(entry);
   b_mcEt->GetEntry(entry);

   b_mcIndex->GetEntry(entry);
   b_mcDecayType->GetEntry(entry);
   b_mcParentage->GetEntry(entry);


   b_nPUInfo->GetEntry(entry);
   b_puTrue->GetEntry(entry);

   b_phoGenIndex->GetEntry(entry);
   b_phoGenMomPID->GetEntry(entry);

   b_jetGenJetPt->GetEntry(entry);   
   b_jetGenJetEta->GetEntry(entry);   
   b_jetGenJetPhi->GetEntry(entry); 

   b_muGenIndex->GetEntry(entry);
   b_eleGenIndex->GetEntry(entry);
}

void TEventTree::GetEntrySIGMCSpecific(Long64_t entry)
{
   b_mcStatus->GetEntry(entry);
   b_jetJECUnc->GetEntry(entry);
   b_nPU->GetEntry(entry);
}// end of GetEntrySIGMCSpecifi

void TEventTree::Init(TTree *tree)
{
   // The Init() function is called when the selector needs to initialize
   // a new tree or chain. Typically here the branch addresses and branch
   // pointers of the tree will be set.
   // It is normally not necessary to make changes to the generated
   // code, but the routine can be extended by the user if needed.
   // Init() will be called many times when running on PROOF
   // (once per file to be processed).

   // Set object pointer
//   treeLeaf.vtx_x = 0;
//   treeLeaf.vtx_y = 0;
//   treeLeaf.vtx_z = 0;
//   treeLeaf.vtxbs_x = 0;
//   treeLeaf.vtxbs_y = 0;
//   treeLeaf.vtxbs_z = 0;
   treeLeaf.mcPID = 0;
//   treeLeaf.mcVtx_x = 0;
//   treeLeaf.mcVtx_y = 0;
//   treeLeaf.mcVtx_z = 0;
   treeLeaf.mcPt = 0;
//   treeLeaf.mcMass = 0;
   treeLeaf.mcEta = 0;
   treeLeaf.mcPhi = 0;
   treeLeaf.mcE = 0;
   treeLeaf.mcEt = 0;
   treeLeaf.mcGMomPID = 0;
   treeLeaf.mcMomPID = 0;
   treeLeaf.mcMomPt = 0;
//   treeLeaf.mcMomMass = 0;
   treeLeaf.mcMomEta = 0;
   treeLeaf.mcMomPhi = 0;
   treeLeaf.mcIndex = 0;
   treeLeaf.mcDecayType = 0;
   treeLeaf.mcParentage = 0;
   treeLeaf.mcStatus = 0;
   treeLeaf.nPU = 0;
//   treeLeaf.puBX = 0;
   treeLeaf.puTrue = 0;
//   treeLeaf.trkMETx = 0;
//   treeLeaf.trkMETy = 0;
//   treeLeaf.trkMETPhi = 0;
//   treeLeaf.trkMET = 0;
   treeLeaf.eleTrg = 0;
//   treeLeaf.eleClass = 0;
//   treeLeaf.eleIsEcalDriven = 0;
//   treeLeaf.eleCharge = 0;
//   treeLeaf.eleChargeConsistent = 0;
//   treeLeaf.eleEn = 0;
   treeLeaf.eleEcalEn = 0;
//   treeLeaf.eleSCRawEn = 0;
//   treeLeaf.eleSCEn = 0;
//   treeLeaf.eleESEn = 0;
   treeLeaf.elePt = 0;
   treeLeaf.eleEta = 0;
   treeLeaf.elePhi = 0;
//   treeLeaf.eleR9 = 0;
//   treeLeaf.eleEtaVtx = 0;
//   treeLeaf.elePhiVtx = 0;
//   treeLeaf.eleEtVtx = 0;
   treeLeaf.eleSCEta = 0;
   treeLeaf.eleSCPhi = 0;
//   treeLeaf.eleSCEtaWidth = 0;
//   treeLeaf.eleSCPhiWidth = 0;
//   treeLeaf.eleVtx_x = 0;
//   treeLeaf.eleVtx_y = 0;
//   treeLeaf.eleVtx_z = 0;
//   treeLeaf.eleD0 = 0;
//   treeLeaf.eleDz = 0;
//   treeLeaf.eleD0GV = 0;
//   treeLeaf.eleDzGV = 0;
   treeLeaf.eleD0Vtx = 0;
   treeLeaf.eleDzVtx = 0;
   treeLeaf.eleHoverE = 0;
   treeLeaf.eleHoverE12 = 0;
//   treeLeaf.eleEoverP = 0;
   treeLeaf.elePin = 0;
//   treeLeaf.elePout = 0;
//   treeLeaf.eleTrkMomErr = 0;
//   treeLeaf.eleBrem = 0;
   treeLeaf.eledEtaAtVtx = 0;
   treeLeaf.eledPhiAtVtx = 0;
   treeLeaf.eleSigmaIEtaIEta = 0;
//   treeLeaf.eleSigmaIEtaIPhi = 0;
//   treeLeaf.eleSigmaIPhiIPhi = 0;
//   treeLeaf.eleEmax = 0;
//   treeLeaf.eleE2ndMax = 0;
//   treeLeaf.eleETop = 0;
//   treeLeaf.eleEBottom = 0;
//   treeLeaf.eleELeft = 0;
//   treeLeaf.eleERight = 0;
//   treeLeaf.eleE1x5 = 0;
//   treeLeaf.eleE3x3 = 0;
//   treeLeaf.eleE5x5 = 0;
//   treeLeaf.eleE2x5Max = 0;
//   treeLeaf.eleE2x5Top = 0;
//   treeLeaf.eleE2x5Bottom = 0;
//   treeLeaf.eleE2x5Left = 0;
//   treeLeaf.eleE2x5Right = 0;
//   treeLeaf.eleSeedEta = 0;
//   treeLeaf.eleSeedE = 0;
//   treeLeaf.eleSeedPhi = 0;
//   treeLeaf.eleCrysEta = 0;
//   treeLeaf.eleCrysPhi = 0;
//   treeLeaf.eleCrysIEta = 0;
//   treeLeaf.eleCrysIPhi = 0;
//   treeLeaf.eleRegrE = 0;
//   treeLeaf.eleRegrEerr = 0;
//   treeLeaf.elePhoRegrE = 0;
//   treeLeaf.elePhoRegrEerr = 0;
//   treeLeaf.eleSeedTime = 0;
//   treeLeaf.eleRecoFlag = 0;
//   treeLeaf.elePos = 0;
   treeLeaf.eleGenIndex = 0;
//   treeLeaf.eleGenGMomPID = 0;
//   treeLeaf.eleGenMomPID = 0;
//   treeLeaf.eleGenMomPt = 0;
//   treeLeaf.eleIsoTrkDR03 = 0;
//   treeLeaf.eleIsoEcalDR03 = 0;
//   treeLeaf.eleIsoHcalDR03 = 0;
//   treeLeaf.eleIsoHcalDR0312 = 0;
//   treeLeaf.eleIsoTrkDR04 = 0;
//   treeLeaf.eleIsoEcalDR04 = 0;
//   treeLeaf.eleIsoHcalDR04 = 0;
//   treeLeaf.eleIsoHcalDR0412 = 0;
//   treeLeaf.eleModIsoTrk = 0;
//   treeLeaf.eleModIsoEcal = 0;
//   treeLeaf.eleModIsoHcal = 0;
   treeLeaf.eleMissHits = 0;
//   treeLeaf.eleConvDist = 0;
//   treeLeaf.eleConvDcot = 0;
   treeLeaf.eleConvVtxFit = 0;
//   treeLeaf.eleIP3D = 0;
//   treeLeaf.eleIP3DErr = 0;
//   treeLeaf.eleIDMVANonTrig = 0;
//   treeLeaf.eleIDMVATrig = 0;
   treeLeaf.elePFChIso03 = 0;
   treeLeaf.elePFPhoIso03 = 0;
   treeLeaf.elePFNeuIso03 = 0;
//   treeLeaf.elePFChIso04 = 0;
//   treeLeaf.elePFPhoIso04 = 0;
//   treeLeaf.elePFNeuIso04 = 0;
//   treeLeaf.eleESEffSigmaRR_x = 0;
//   treeLeaf.eleESEffSigmaRR_y = 0;
//   treeLeaf.eleESEffSigmaRR_z = 0;
//   treeLeaf.phoTrg = 0;
//   treeLeaf.phoTrgFilter = 0;
//   treeLeaf.phoIsPhoton = 0;
//   treeLeaf.phoSCPos_x = 0;
//   treeLeaf.phoSCPos_y = 0;
//   treeLeaf.phoSCPos_z = 0;
//   treeLeaf.phoCaloPos_x = 0;
//   treeLeaf.phoCaloPos_y = 0;
//   treeLeaf.phoCaloPos_z = 0;
//   treeLeaf.phoE = 0;
   treeLeaf.phoEt = 0;
   treeLeaf.phoEta = 0;
//   treeLeaf.phoVtx_x = 0;
//   treeLeaf.phoVtx_y = 0;
//   treeLeaf.phoVtx_z = 0;
   treeLeaf.phoPhi = 0;
//   treeLeaf.phoEtVtx = 0;
//   treeLeaf.phoEtaVtx = 0;
//   treeLeaf.phoPhiVtx = 0;
   treeLeaf.phoR9 = 0;
//   treeLeaf.phoNClus = 0;
//   treeLeaf.phoTrkIsoHollowDR03 = 0;
//   treeLeaf.phoEcalIsoDR03 = 0;
//   treeLeaf.phoHcalIsoDR03 = 0;
//   treeLeaf.phoHcalIsoDR0312 = 0;
   treeLeaf.phoTrkIsoHollowDR04 = 0;
//   treeLeaf.phoCiCdRtoTrk = 0;
   treeLeaf.phoEcalIsoDR04 = 0;
   treeLeaf.phoHcalIsoDR04 = 0;
//   treeLeaf.phoHcalIsoDR0412 = 0;
   treeLeaf.phoHoverE = 0;
   treeLeaf.phoHoverE12 = 0;
   treeLeaf.phoEleVeto = 0;
   treeLeaf.phoSigmaIEtaIEta = 0;
//   treeLeaf.phoSigmaIEtaIPhi = 0;
//   treeLeaf.phoSigmaIPhiIPhi = 0;
//   treeLeaf.phoCiCPF4phopfIso03 = 0;
//   treeLeaf.phoCiCPF4phopfIso04 = 0;
//   treeLeaf.phoCiCPF4chgpfIso02 = 0;
//   treeLeaf.phoCiCPF4chgpfIso03 = 0;
//   treeLeaf.phoCiCPF4chgpfIso04 = 0;
//   treeLeaf.phoEmax = 0;
//   treeLeaf.phoETop = 0;
//   treeLeaf.phoEBottom = 0;
//   treeLeaf.phoELeft = 0;
//   treeLeaf.phoERight = 0;
//   treeLeaf.phoE2ndMax = 0;
//   treeLeaf.phoE3x3 = 0;
//   treeLeaf.phoE3x1 = 0;
//   treeLeaf.phoE1x3 = 0;
//   treeLeaf.phoE5x5 = 0;
//   treeLeaf.phoE1x5 = 0;
//   treeLeaf.phoE2x2 = 0;
//   treeLeaf.phoE2x5Max = 0;
//   treeLeaf.phoE2x5Top = 0;
//   treeLeaf.phoE2x5Bottom = 0;
//   treeLeaf.phoE2x5Left = 0;
//   treeLeaf.phoE2x5Right = 0;
//   treeLeaf.phoSeedE = 0;
//   treeLeaf.phoSeedEta = 0;
//   treeLeaf.phoSeedPhi = 0;
//   treeLeaf.phoCrysEta = 0;
//   treeLeaf.phoCrysPhi = 0;
//   treeLeaf.phoCrysIEta = 0;
//   treeLeaf.phoCrysIPhi = 0;
   treeLeaf.phoPFChIso = 0;
   treeLeaf.phoPFPhoIso = 0;
   treeLeaf.phoPFNeuIso = 0;
   treeLeaf.phoSCRChIso = 0;
   treeLeaf.phoSCRPhoIso = 0;
   treeLeaf.phoSCRNeuIso = 0;
   treeLeaf.phoSCRChIso04 = 0;
   treeLeaf.phoSCRPhoIso04 = 0;
   treeLeaf.phoSCRNeuIso04 = 0;
   treeLeaf.phoRandConeChIso = 0;
   treeLeaf.phoRandConePhoIso = 0;
   treeLeaf.phoRandConeNeuIso = 0;
   treeLeaf.phoRandConeChIso04 = 0;
   treeLeaf.phoRandConePhoIso04 = 0;
   treeLeaf.phoRandConeNeuIso04 = 0;
//   treeLeaf.phoRegrE = 0;
//   treeLeaf.phoRegrEerr = 0;
//   treeLeaf.phoSeedTime = 0;
//   treeLeaf.phoSeedDetId1 = 0;
//   treeLeaf.phoSeedDetId2 = 0;
//   treeLeaf.phoLICTD = 0;
//   treeLeaf.phoRecoFlag = 0;
//   treeLeaf.phoPos = 0;
   treeLeaf.phoGenIndex = 0;
//   treeLeaf.phoGenGMomPID = 0;
   treeLeaf.phoGenMomPID = 0;
//   treeLeaf.phoGenMomPt = 0;
//   treeLeaf.phoSCE = 0;
//   treeLeaf.phoSCRawE = 0;
//   treeLeaf.phoESEn = 0;
   treeLeaf.phoSCEt = 0;
   treeLeaf.phoSCEta = 0;
   treeLeaf.phoSCPhi = 0;
//   treeLeaf.phoSCEtaWidth = 0;
//   treeLeaf.phoSCPhiWidth = 0;
//   treeLeaf.phoSCBrem = 0;
//   treeLeaf.phoOverlap = 0;
   treeLeaf.phohasPixelSeed = 0;
//   treeLeaf.pho_hasConvPf = 0;
//   treeLeaf.pho_hasSLConvPf = 0;
//   treeLeaf.pho_pfconvVtxZ = 0;
//   treeLeaf.pho_pfconvVtxZErr = 0;
//   treeLeaf.pho_nSLConv = 0;
//   treeLeaf.pho_pfSLConvPos_x = 0;
//   treeLeaf.pho_pfSLConvPos_y = 0;
//   treeLeaf.pho_pfSLConvPos_z = 0;
//   treeLeaf.pho_pfSLConvVtxZ = 0;
//   treeLeaf.phoIsConv = 0;
//   treeLeaf.phoNConv = 0;
//   treeLeaf.phoConvInvMass = 0;
//   treeLeaf.phoConvCotTheta = 0;
//   treeLeaf.phoConvEoverP = 0;
//   treeLeaf.phoConvZofPVfromTrks = 0;
//   treeLeaf.phoConvMinDist = 0;
//   treeLeaf.phoConvdPhiAtVtx = 0;
//   treeLeaf.phoConvdPhiAtCalo = 0;
//   treeLeaf.phoConvdEtaAtCalo = 0;
//   treeLeaf.phoConvTrkd0_x = 0;
//   treeLeaf.phoConvTrkd0_y = 0;
//   treeLeaf.phoConvTrkPin_x = 0;
//   treeLeaf.phoConvTrkPin_y = 0;
//   treeLeaf.phoConvTrkPout_x = 0;
//   treeLeaf.phoConvTrkPout_y = 0;
//   treeLeaf.phoConvTrkdz_x = 0;
//   treeLeaf.phoConvTrkdz_y = 0;
//   treeLeaf.phoConvTrkdzErr_x = 0;
//   treeLeaf.phoConvTrkdzErr_y = 0;
//   treeLeaf.phoConvChi2 = 0;
//   treeLeaf.phoConvChi2Prob = 0;
//   treeLeaf.phoConvNTrks = 0;
//   treeLeaf.phoConvCharge1 = 0;
//   treeLeaf.phoConvCharge2 = 0;
//   treeLeaf.phoConvValidVtx = 0;
//   treeLeaf.phoConvLikeLihood = 0;
//   treeLeaf.phoConvP4_0 = 0;
//   treeLeaf.phoConvP4_1 = 0;
//   treeLeaf.phoConvP4_2 = 0;
//   treeLeaf.phoConvP4_3 = 0;
//   treeLeaf.phoConvVtx_x = 0;
//   treeLeaf.phoConvVtx_y = 0;
//   treeLeaf.phoConvVtx_z = 0;
//   treeLeaf.phoConvVtxErr_x = 0;
//   treeLeaf.phoConvVtxErr_y = 0;
//   treeLeaf.phoConvVtxErr_z = 0;
//   treeLeaf.phoConvPairMomentum_x = 0;
//   treeLeaf.phoConvPairMomentum_y = 0;
//   treeLeaf.phoConvPairMomentum_z = 0;
//   treeLeaf.phoConvRefittedMomentum_x = 0;
//   treeLeaf.phoConvRefittedMomentum_y = 0;
//   treeLeaf.phoConvRefittedMomentum_z = 0;
//   treeLeaf.SingleLegConv = 0;
//   treeLeaf.phoPFConvVtx_x = 0;
//   treeLeaf.phoPFConvVtx_y = 0;
//   treeLeaf.phoPFConvVtx_z = 0;
//   treeLeaf.phoPFConvMom_x = 0;
//   treeLeaf.phoPFConvMom_y = 0;
//   treeLeaf.phoPFConvMom_z = 0;
//   treeLeaf.phoESEffSigmaRR_x = 0;
//   treeLeaf.phoESEffSigmaRR_y = 0;
//   treeLeaf.phoESEffSigmaRR_z = 0;
   treeLeaf.muTrg = 0;
   treeLeaf.muEta = 0;
   treeLeaf.muPhi = 0;
//   treeLeaf.muCharge = 0;
   treeLeaf.muPt = 0;
//   treeLeaf.muPz = 0;
//   treeLeaf.muVtx_x = 0;
//   treeLeaf.muVtx_y = 0;
//   treeLeaf.muVtx_z = 0;
//   treeLeaf.muVtxGlb_x = 0;
//   treeLeaf.muVtxGlb_y = 0;
//   treeLeaf.muVtxGlb_z = 0;
   treeLeaf.muGenIndex = 0;
//   treeLeaf.mucktPt = 0;
//   treeLeaf.mucktPtErr = 0;
//   treeLeaf.mucktEta = 0;
//   treeLeaf.mucktPhi = 0;
//   treeLeaf.mucktdxy = 0;
//   treeLeaf.mucktdz = 0;
   treeLeaf.muIsoTrk = 0;
//   treeLeaf.muIsoCalo = 0;
   treeLeaf.muIsoEcal = 0;
   treeLeaf.muIsoHcal = 0;
   treeLeaf.muChi2NDF = 0;
//   treeLeaf.muInnerChi2NDF = 0;
   treeLeaf.muPFIsoR04_CH = 0;
   treeLeaf.muPFIsoR04_NH = 0;
   treeLeaf.muPFIsoR04_Pho = 0;
   treeLeaf.muPFIsoR04_PU = 0;
//   treeLeaf.muPFIsoR04_CPart = 0;
//   treeLeaf.muPFIsoR04_NHHT = 0;
//   treeLeaf.muPFIsoR04_PhoHT = 0;
//   treeLeaf.muPFIsoR03_CH = 0;
//   treeLeaf.muPFIsoR03_NH = 0;
//   treeLeaf.muPFIsoR03_Pho = 0;
//   treeLeaf.muPFIsoR03_PU = 0;
//   treeLeaf.muPFIsoR03_CPart = 0;
//   treeLeaf.muPFIsoR03_NHHT = 0;
//   treeLeaf.muPFIsoR03_PhoHT = 0;
   treeLeaf.muType = 0;
   treeLeaf.muD0 = 0;
   treeLeaf.muDz = 0;
//   treeLeaf.muD0GV = 0;
//   treeLeaf.muDzGV = 0;
//   treeLeaf.muD0Vtx = 0;
//   treeLeaf.muDzVtx = 0;
//   treeLeaf.muInnerD0 = 0;
//   treeLeaf.muInnerDz = 0;
   treeLeaf.muInnerD0GV = 0;
   treeLeaf.muInnerDzGV = 0;
//   treeLeaf.muInnerPt = 0;
//   treeLeaf.muInnerPtErr = 0;
   treeLeaf.muNumberOfValidTrkLayers = 0;
   treeLeaf.muNumberOfValidTrkHits = 0;
//   treeLeaf.muNumberOfValidPixelLayers = 0;
   treeLeaf.muNumberOfValidPixelHits = 0;
   treeLeaf.muNumberOfValidMuonHits = 0;
   treeLeaf.muStations = 0;
//   treeLeaf.muChambers = 0;
//   treeLeaf.muIP3D = 0;
//   treeLeaf.muIP3DErr = 0;
//   treeLeaf.tauDecayModeFinding = 0;
//   treeLeaf.tauAgainstElectronLooseMVA3 = 0;
//   treeLeaf.tauAgainstElectronMediumMVA3 = 0;
//   treeLeaf.tauAgainstElectronTightMVA3 = 0;
//   treeLeaf.tauAgainstElectronVTightMVA3 = 0;
//   treeLeaf.tauAgainstElectronDeadECAL = 0;
//   treeLeaf.tauAgainstMuonLoose2 = 0;
//   treeLeaf.tauAgainstMuonMedium2 = 0;
//   treeLeaf.tauAgainstMuonTight2 = 0;
//   treeLeaf.tauCombinedIsolationDeltaBetaCorrRaw3Hits = 0;
//   treeLeaf.tauLooseCombinedIsolationDeltaBetaCorr3Hits = 0;
//   treeLeaf.tauMediumCombinedIsolationDeltaBetaCorr3Hits = 0;
//   treeLeaf.tauTightCombinedIsolationDeltaBetaCorr3Hits = 0;
//   treeLeaf.tauEta = 0;
//   treeLeaf.tauPhi = 0;
//   treeLeaf.tauPt = 0;
//   treeLeaf.tauEt = 0;
//   treeLeaf.tauCharge = 0;
//   treeLeaf.tauDecayMode = 0;
//   treeLeaf.tauEMFraction = 0;
//   treeLeaf.tauHCAL3x3OverPLead = 0;
//   treeLeaf.tauHCALMaxOverPLead = 0;
//   treeLeaf.tauHCALTotOverPLead = 0;
//   treeLeaf.tauIsolationPFChargedHadrCandsPtSum = 0;
//   treeLeaf.tauIsolationPFGammaCandsEtSum = 0;
//   treeLeaf.tauLeadPFChargedHadrCandsignedSipt = 0;
//   treeLeaf.tauLeadChargedHadronExists = 0;
//   treeLeaf.tauLeadChargedHadronEta = 0;
//   treeLeaf.tauLeadChargedHadronPhi = 0;
//   treeLeaf.tauLeadChargedHadronPt = 0;
//   treeLeaf.CA8JetPt = 0;
//   treeLeaf.CA8JetEta = 0;
//   treeLeaf.CA8JetPhi = 0;
//   treeLeaf.CA8JetMass = 0;
//   treeLeaf.CA8JetArea = 0;
//   treeLeaf.CA8Jet_tau1 = 0;
//   treeLeaf.CA8Jet_tau2 = 0;
//   treeLeaf.CA8Jet_tau3 = 0;
//   treeLeaf.CA8JetCHF = 0;
//   treeLeaf.CA8JetNHF = 0;
//   treeLeaf.CA8JetCEF = 0;
//   treeLeaf.CA8JetNEF = 0;
//   treeLeaf.CA8JetNCH = 0;
//   treeLeaf.CA8Jetnconstituents = 0;
//   treeLeaf.CA8prunedJetMass = 0;
//   treeLeaf.CA8prunedJet_nSubJets = 0;
//   treeLeaf.CA8prunedJet_SubjetPt = 0;
//   treeLeaf.CA8prunedJet_SubjetEta = 0;
//   treeLeaf.CA8prunedJet_SubjetPhi = 0;
//   treeLeaf.CA8prunedJet_SubjetMass = 0;
//   treeLeaf.jetTrg = 0;
//   treeLeaf.jetEn = 0;
   treeLeaf.jetPt = 0;
   treeLeaf.jetEta = 0;
   treeLeaf.jetPhi = 0;
//   treeLeaf.jetCharge = 0;
//   treeLeaf.jetEt = 0;
   treeLeaf.jetRawPt = 0;
   treeLeaf.jetRawEn = 0;
//   treeLeaf.jetArea = 0;
//   treeLeaf.jetCHF = 0;
//   treeLeaf.jetNHF = 0;
//   treeLeaf.jetCEF = 0;
//   treeLeaf.jetNEF = 0;
//   treeLeaf.jetNCH = 0;
//   treeLeaf.jetHFHAE = 0;
//   treeLeaf.jetHFEME = 0;
//   treeLeaf.jetNConstituents = 0;
//   treeLeaf.jetCombinedSecondaryVtxBJetTags = 0;
//   treeLeaf.jetCombinedSecondaryVtxMVABJetTags = 0;
//   treeLeaf.jetJetProbabilityBJetTags = 0;
//   treeLeaf.jetJetBProbabilityBJetTags = 0;
//   treeLeaf.jetBetaStar = 0;
//   treeLeaf.jetPFLooseId = 0;
//   treeLeaf.jetDRMean = 0;
//   treeLeaf.jetDR2Mean = 0;
//   treeLeaf.jetDZ = 0;
//   treeLeaf.jetFrac01 = 0;
//   treeLeaf.jetFrac02 = 0;
//   treeLeaf.jetFrac03 = 0;
//   treeLeaf.jetFrac04 = 0;
//   treeLeaf.jetFrac05 = 0;
//   treeLeaf.jetFrac06 = 0;
//   treeLeaf.jetFrac07 = 0;
//   treeLeaf.jetBeta = 0;
//   treeLeaf.jetBetaStarCMG = 0;
//   treeLeaf.jetBetaStarClassic = 0;
//   treeLeaf.jetBetaExt = 0;
//   treeLeaf.jetBetaStarCMGExt = 0;
//   treeLeaf.jetBetaStarClassicExt = 0;
//   treeLeaf.jetNNeutrals = 0;
//   treeLeaf.jetNCharged = 0;
//   treeLeaf.jetMVAs = 0;
//   treeLeaf.jetWPLevels = 0;
//   treeLeaf.jetMVAsExt_simple = 0;
//  treeLeaf.jetWPLevelsExt_simple = 0;
//   treeLeaf.jetMVAsExt_full = 0;
//   treeLeaf.jetWPLevelsExt_full = 0;
//   treeLeaf.jetMVAsExt_cutBased = 0;
//   treeLeaf.jetWPLevelsExt_cutBased = 0;
//   treeLeaf.jetMVAsExt_philv1 = 0;
//   treeLeaf.jetWPLevelsExt_philv1 = 0;
//   treeLeaf.jetMt = 0;
     treeLeaf.jetJECUnc = 0;
//   treeLeaf.jetLeadTrackPt = 0;
//   treeLeaf.jetVtxPt = 0;
//   treeLeaf.jetVtxMass = 0;
//   treeLeaf.jetVtx3dL = 0;
//   treeLeaf.jetVtx3deL = 0;
//   treeLeaf.jetSoftLeptPt = 0;
//   treeLeaf.jetSoftLeptPtRel = 0;
//   treeLeaf.jetSoftLeptdR = 0;
//   treeLeaf.jetSoftLeptIdlooseMu = 0;
//   treeLeaf.jetSoftLeptIdEle95 = 0;
//   treeLeaf.jetDPhiMETJet = 0;
//   treeLeaf.jetPuJetIdL = 0;
//   treeLeaf.jetPuJetIdM = 0;
//   treeLeaf.jetPuJetIdT = 0;
//   treeLeaf.jetPartonID = 0;
//   treeLeaf.jetGenJetIndex = 0;
//   treeLeaf.jetGenJetEn = 0;
   treeLeaf.jetGenJetPt = 0;
   treeLeaf.jetGenJetEta = 0;
   treeLeaf.jetGenJetPhi = 0;
//   treeLeaf.jetGenPartonID = 0;
//   treeLeaf.jetGenEn = 0;
//   treeLeaf.jetGenPt = 0;
//   treeLeaf.jetGenEta = 0;
//   treeLeaf.jetGenPhi = 0;
//   treeLeaf.jetGenPartonMomID = 0;
//   treeLeaf.convP4_x = 0;
//   treeLeaf.convP4_y = 0;
//   treeLeaf.convP4_z = 0;
//   treeLeaf.convP4_E = 0;
//   treeLeaf.convVtx_x = 0;
//   treeLeaf.convVtx_y = 0;
//   treeLeaf.convVtx_z = 0;
//   treeLeaf.convVtxErr_x = 0;
//   treeLeaf.convVtxErr_y = 0;
//   treeLeaf.convVtxErr_z = 0;
//   treeLeaf.convPairMomentum_x = 0;
//   treeLeaf.convPairMomentum_y = 0;
//   treeLeaf.convPairMomentum_z = 0;
//   treeLeaf.convRefittedMomentum_x = 0;
//   treeLeaf.convRefittedMomentum_y = 0;
//   treeLeaf.convRefittedMomentum_z = 0;
//   treeLeaf.convNTracks = 0;
//   treeLeaf.convPairInvMass = 0;
//   treeLeaf.convPairCotThetaSep = 0;
//   treeLeaf.convEoverP = 0;
//   treeLeaf.convDistOfMinApproach = 0;
//   treeLeaf.convDPhiTrksAtVtx = 0;
//   treeLeaf.convDPhiTrksAtEcal = 0;
//   treeLeaf.convDEtaTrksAtEcal = 0;
//   treeLeaf.convDxy = 0;
//   treeLeaf.convDz = 0;
//   treeLeaf.convLxy = 0;
//   treeLeaf.convLz = 0;
//   treeLeaf.convZofPrimVtxFromTrks = 0;
//   treeLeaf.convNHitsBeforeVtx_0 = 0;
//   treeLeaf.convNHitsBeforeVtx_1 = 0;
//   treeLeaf.convNSharedHits = 0;
//   treeLeaf.convValidVtx = 0;
//   treeLeaf.convMVALikelihood = 0;
//   treeLeaf.convChi2 = 0;
//   treeLeaf.convChi2Probability = 0;
//   treeLeaf.convTk1Dz = 0;
//   treeLeaf.convTk2Dz = 0;
//   treeLeaf.convTk1DzErr = 0;
//   treeLeaf.convTk2DzErr = 0;
//   treeLeaf.convCh1Ch2 = 0;
//   treeLeaf.convTk1D0 = 0;
//   treeLeaf.convTk1Pout = 0;
//   treeLeaf.convTk1Pin = 0;
//   treeLeaf.convTk2D0 = 0;
//   treeLeaf.convTk2Pout = 0;
//   treeLeaf.convTk2Pin = 0;

   // Set branch addresses and branch pointers
   if (!tree) return;
   fChain = tree;
   fCurrent = -1;
   fChain->SetMakeClass(1);

   fChain->SetBranchAddress("run", &treeLeaf.run, &b_run);
   fChain->SetBranchAddress("event", &treeLeaf.event, &b_event);
//   fChain->SetBranchAddress("lumis", &treeLeaf.lumis, &b_lumis);
   fChain->SetBranchAddress("isData", &treeLeaf.isData, &b_isData);
   fChain->SetBranchAddress("nHLT", &treeLeaf.nHLT, &b_nHLT);
   fChain->SetBranchAddress("HLT", treeLeaf.HLT, &b_HLT);
   fChain->SetBranchAddress("HLTIndex", treeLeaf.HLTIndex, &b_HLTIndex);
//   fChain->SetBranchAddress("bspotPos", treeLeaf.bspotPos, &b_bspotPos);
//   fChain->SetBranchAddress("nVtx", &treeLeaf.nVtx, &b_nVtx);
//   fChain->SetBranchAddress("vtx_x", &treeLeaf.vtx_x, &b_vtx_x);
//   fChain->SetBranchAddress("vtx_y", &treeLeaf.vtx_y, &b_vtx_y);
//   fChain->SetBranchAddress("vtx_z", &treeLeaf.vtx_z, &b_vtx_z);
   fChain->SetBranchAddress("IsVtxGood", &treeLeaf.IsVtxGood, &b_IsVtxGood);
//   fChain->SetBranchAddress("nGoodVtx", &treeLeaf.nGoodVtx, &b_nGoodVtx);
//   fChain->SetBranchAddress("nVtxBS", &treeLeaf.nVtxBS, &b_nVtxBS);
//   fChain->SetBranchAddress("vtxbs_x", &treeLeaf.vtxbs_x, &b_vtxbs_x);
//   fChain->SetBranchAddress("vtxbs_y", &treeLeaf.vtxbs_y, &b_vtxbs_y);
//   fChain->SetBranchAddress("vtxbs_z", &treeLeaf.vtxbs_z, &b_vtxbs_z);
//   fChain->SetBranchAddress("pdf", treeLeaf.pdf, &b_pdf);
//   fChain->SetBranchAddress("pthat", &treeLeaf.pthat, &b_pthat);
//   fChain->SetBranchAddress("processID", &treeLeaf.processID, &b_processID);
   fChain->SetBranchAddress("nMC", &treeLeaf.nMC, &b_nMC);
   fChain->SetBranchAddress("mcPID", &treeLeaf.mcPID, &b_mcPID);
//   fChain->SetBranchAddress("mcVtx_x", &treeLeaf.mcVtx_x, &b_mcVtx_x);
//   fChain->SetBranchAddress("mcVtx_y", &treeLeaf.mcVtx_y, &b_mcVtx_y);
//   fChain->SetBranchAddress("mcVtx_z", &treeLeaf.mcVtx_z, &b_mcVtx_z);
   fChain->SetBranchAddress("mcPt", &treeLeaf.mcPt, &b_mcPt);
//   fChain->SetBranchAddress("mcMass", &treeLeaf.mcMass, &b_mcMass);
   fChain->SetBranchAddress("mcEta", &treeLeaf.mcEta, &b_mcEta);
   fChain->SetBranchAddress("mcPhi", &treeLeaf.mcPhi, &b_mcPhi);
   fChain->SetBranchAddress("mcE", &treeLeaf.mcE, &b_mcE);
   fChain->SetBranchAddress("mcEt", &treeLeaf.mcEt, &b_mcEt);
   fChain->SetBranchAddress("mcGMomPID", &treeLeaf.mcGMomPID, &b_mcGMomPID);
   fChain->SetBranchAddress("mcMomPID", &treeLeaf.mcMomPID, &b_mcMomPID);
   fChain->SetBranchAddress("mcMomPt", &treeLeaf.mcMomPt, &b_mcMomPt);
//   fChain->SetBranchAddress("mcMomMass", &treeLeaf.mcMomMass, &b_mcMomMass);
   fChain->SetBranchAddress("mcMomEta", &treeLeaf.mcMomEta, &b_mcMomEta);
   fChain->SetBranchAddress("mcMomPhi", &treeLeaf.mcMomPhi, &b_mcMomPhi);
   fChain->SetBranchAddress("mcIndex", &treeLeaf.mcIndex, &b_mcIndex);
   fChain->SetBranchAddress("mcDecayType", &treeLeaf.mcDecayType, &b_mcDecayType);
   fChain->SetBranchAddress("mcParentage", &treeLeaf.mcParentage, &b_mcParentage);
   fChain->SetBranchAddress("mcStatus", &treeLeaf.mcStatus, &b_mcStatus);
//   fChain->SetBranchAddress("genMET", &treeLeaf.genMET, &b_genMET);
//   fChain->SetBranchAddress("genMETPhi", &treeLeaf.genMETPhi, &b_genMETPhi);
   fChain->SetBranchAddress("nPUInfo", &treeLeaf.nPUInfo, &b_nPUInfo);
   fChain->SetBranchAddress("nPU", &treeLeaf.nPU, &b_nPU);
//   fChain->SetBranchAddress("puBX", &treeLeaf.puBX, &b_puBX);
   fChain->SetBranchAddress("puTrue", &treeLeaf.puTrue, &b_puTrue);
   fChain->SetBranchAddress("pfMET", &treeLeaf.pfMET, &b_pfMET);
   fChain->SetBranchAddress("pfMETPhi", &treeLeaf.pfMETPhi, &b_pfMETPhi);
//   fChain->SetBranchAddress("pfMETsumEt", &treeLeaf.pfMETsumEt, &b_pfMETsumEt);
//   fChain->SetBranchAddress("pfMETmEtSig", &treeLeaf.pfMETmEtSig, &b_pfMETmEtSig);
//   fChain->SetBranchAddress("pfMETSig", &treeLeaf.pfMETSig, &b_pfMETSig);
//   fChain->SetBranchAddress("pfType01MET", &treeLeaf.pfType01MET, &b_pfType01MET);
//   fChain->SetBranchAddress("pfType01METPhi", &treeLeaf.pfType01METPhi, &b_pfType01METPhi);
//   fChain->SetBranchAddress("pfType01METsumEt", &treeLeaf.pfType01METsumEt, &b_pfType01METsumEt);
//   fChain->SetBranchAddress("pfType01METmEtSig", &treeLeaf.pfType01METmEtSig, &b_pfType01METmEtSig);
//   fChain->SetBranchAddress("pfType01METSig", &treeLeaf.pfType01METSig, &b_pfType01METSig);
//   fChain->SetBranchAddress("recoPfMET", &treeLeaf.recoPfMET, &b_recoPfMET);
//   fChain->SetBranchAddress("recoPfMETPhi", &treeLeaf.recoPfMETPhi, &b_recoPfMETPhi);
//   fChain->SetBranchAddress("recoPfMETsumEt", &treeLeaf.recoPfMETsumEt, &b_recoPfMETsumEt);
//   fChain->SetBranchAddress("recoPfMETmEtSig", &treeLeaf.recoPfMETmEtSig, &b_recoPfMETmEtSig);
//   fChain->SetBranchAddress("recoPfMETSig", &treeLeaf.recoPfMETSig, &b_recoPfMETSig);
//   fChain->SetBranchAddress("trkMETxPV", &treeLeaf.trkMETxPV, &b_trkMETxPV);
//   fChain->SetBranchAddress("trkMETyPV", &treeLeaf.trkMETyPV, &b_trkMETyPV);
//   fChain->SetBranchAddress("trkMETPhiPV", &treeLeaf.trkMETPhiPV, &b_trkMETPhiPV);
//   fChain->SetBranchAddress("trkMETPV", &treeLeaf.trkMETPV, &b_trkMETPV);
//   fChain->SetBranchAddress("trkMETx", &treeLeaf.trkMETx, &b_trkMETx);
//   fChain->SetBranchAddress("trkMETy", &treeLeaf.trkMETy, &b_trkMETy);
//   fChain->SetBranchAddress("trkMETPhi", &treeLeaf.trkMETPhi, &b_trkMETPhi);
//   fChain->SetBranchAddress("trkMET", &treeLeaf.trkMET, &b_trkMET);
   fChain->SetBranchAddress("metFilters", treeLeaf.metFilters, &b_metFilters);
   fChain->SetBranchAddress("nEle", &treeLeaf.nEle, &b_nEle);
   fChain->SetBranchAddress("eleTrg", &treeLeaf.eleTrg, &b_eleTrg);
//   fChain->SetBranchAddress("eleClass", &treeLeaf.eleClass, &b_eleClass);
//   fChain->SetBranchAddress("eleIsEcalDriven", &treeLeaf.eleIsEcalDriven, &b_eleIsEcalDriven);
//   fChain->SetBranchAddress("eleCharge", &treeLeaf.eleCharge, &b_eleCharge);
//   fChain->SetBranchAddress("eleChargeConsistent", &treeLeaf.eleChargeConsistent, &b_eleChargeConsistent);
//   fChain->SetBranchAddress("eleEn", &treeLeaf.eleEn, &b_eleEn);
   fChain->SetBranchAddress("eleEcalEn", &treeLeaf.eleEcalEn, &b_eleEcalEn);
//   fChain->SetBranchAddress("eleSCRawEn", &treeLeaf.eleSCRawEn, &b_eleSCRawEn);
//   fChain->SetBranchAddress("eleSCEn", &treeLeaf.eleSCEn, &b_eleSCEn);
//   fChain->SetBranchAddress("eleESEn", &treeLeaf.eleESEn, &b_eleESEn);
   fChain->SetBranchAddress("elePt", &treeLeaf.elePt, &b_elePt);
   fChain->SetBranchAddress("eleEta", &treeLeaf.eleEta, &b_eleEta);
   fChain->SetBranchAddress("elePhi", &treeLeaf.elePhi, &b_elePhi);
//   fChain->SetBranchAddress("eleR9", &treeLeaf.eleR9, &b_eleR9);
//   fChain->SetBranchAddress("eleEtaVtx", &treeLeaf.eleEtaVtx, &b_eleEtaVtx);
//   fChain->SetBranchAddress("elePhiVtx", &treeLeaf.elePhiVtx, &b_elePhiVtx);
//   fChain->SetBranchAddress("eleEtVtx", &treeLeaf.eleEtVtx, &b_eleEtVtx);
   fChain->SetBranchAddress("eleSCEta", &treeLeaf.eleSCEta, &b_eleSCEta);
   fChain->SetBranchAddress("eleSCPhi", &treeLeaf.eleSCPhi, &b_eleSCPhi);
//   fChain->SetBranchAddress("eleSCEtaWidth", &treeLeaf.eleSCEtaWidth, &b_eleSCEtaWidth);
//   fChain->SetBranchAddress("eleSCPhiWidth", &treeLeaf.eleSCPhiWidth, &b_eleSCPhiWidth);
//   fChain->SetBranchAddress("eleVtx_x", &treeLeaf.eleVtx_x, &b_eleVtx_x);
//   fChain->SetBranchAddress("eleVtx_y", &treeLeaf.eleVtx_y, &b_eleVtx_y);
//   fChain->SetBranchAddress("eleVtx_z", &treeLeaf.eleVtx_z, &b_eleVtx_z);
//   fChain->SetBranchAddress("eleD0", &treeLeaf.eleD0, &b_eleD0);
//   fChain->SetBranchAddress("eleDz", &treeLeaf.eleDz, &b_eleDz);
//   fChain->SetBranchAddress("eleD0GV", &treeLeaf.eleD0GV, &b_eleD0GV);
//   fChain->SetBranchAddress("eleDzGV", &treeLeaf.eleDzGV, &b_eleDzGV);
   fChain->SetBranchAddress("eleD0Vtx", &treeLeaf.eleD0Vtx, &b_eleD0Vtx);
   fChain->SetBranchAddress("eleDzVtx", &treeLeaf.eleDzVtx, &b_eleDzVtx);
   fChain->SetBranchAddress("eleHoverE", &treeLeaf.eleHoverE, &b_eleHoverE);
   fChain->SetBranchAddress("eleHoverE12", &treeLeaf.eleHoverE12, &b_eleHoverE12);
//   fChain->SetBranchAddress("eleEoverP", &treeLeaf.eleEoverP, &b_eleEoverP);
   fChain->SetBranchAddress("elePin", &treeLeaf.elePin, &b_elePin);
//   fChain->SetBranchAddress("elePout", &treeLeaf.elePout, &b_elePout);
//   fChain->SetBranchAddress("eleTrkMomErr", &treeLeaf.eleTrkMomErr, &b_eleTrkMomErr);
//   fChain->SetBranchAddress("eleBrem", &treeLeaf.eleBrem, &b_eleBrem);
   fChain->SetBranchAddress("eledEtaAtVtx", &treeLeaf.eledEtaAtVtx, &b_eledEtaAtVtx);
   fChain->SetBranchAddress("eledPhiAtVtx", &treeLeaf.eledPhiAtVtx, &b_eledPhiAtVtx);
   fChain->SetBranchAddress("eleSigmaIEtaIEta", &treeLeaf.eleSigmaIEtaIEta, &b_eleSigmaIEtaIEta);
//   fChain->SetBranchAddress("eleSigmaIEtaIPhi", &treeLeaf.eleSigmaIEtaIPhi, &b_eleSigmaIEtaIPhi);
//   fChain->SetBranchAddress("eleSigmaIPhiIPhi", &treeLeaf.eleSigmaIPhiIPhi, &b_eleSigmaIPhiIPhi);
//   fChain->SetBranchAddress("eleEmax", &treeLeaf.eleEmax, &b_eleEmax);
//   fChain->SetBranchAddress("eleE2ndMax", &treeLeaf.eleE2ndMax, &b_eleE2ndMax);
//   fChain->SetBranchAddress("eleETop", &treeLeaf.eleETop, &b_eleETop);
//   fChain->SetBranchAddress("eleEBottom", &treeLeaf.eleEBottom, &b_eleEBottom);
//   fChain->SetBranchAddress("eleELeft", &treeLeaf.eleELeft, &b_eleELeft);
//   fChain->SetBranchAddress("eleERight", &treeLeaf.eleERight, &b_eleERight);
//   fChain->SetBranchAddress("eleE1x5", &treeLeaf.eleE1x5, &b_eleE1x5);
//   fChain->SetBranchAddress("eleE3x3", &treeLeaf.eleE3x3, &b_eleE3x3);
//   fChain->SetBranchAddress("eleE5x5", &treeLeaf.eleE5x5, &b_eleE5x5);
//   fChain->SetBranchAddress("eleE2x5Max", &treeLeaf.eleE2x5Max, &b_eleE2x5Max);
//   fChain->SetBranchAddress("eleE2x5Top", &treeLeaf.eleE2x5Top, &b_eleE2x5Top);
//   fChain->SetBranchAddress("eleE2x5Bottom", &treeLeaf.eleE2x5Bottom, &b_eleE2x5Bottom);
//   fChain->SetBranchAddress("eleE2x5Left", &treeLeaf.eleE2x5Left, &b_eleE2x5Left);
//   fChain->SetBranchAddress("eleE2x5Right", &treeLeaf.eleE2x5Right, &b_eleE2x5Right);
//   fChain->SetBranchAddress("eleSeedEta", &treeLeaf.eleSeedEta, &b_eleSeedEta);
//   fChain->SetBranchAddress("eleSeedE", &treeLeaf.eleSeedE, &b_eleSeedE);
//   fChain->SetBranchAddress("eleSeedPhi", &treeLeaf.eleSeedPhi, &b_eleSeedPhi);
//   fChain->SetBranchAddress("eleCrysEta", &treeLeaf.eleCrysEta, &b_eleCrysEta);
//   fChain->SetBranchAddress("eleCrysPhi", &treeLeaf.eleCrysPhi, &b_eleCrysPhi);
//   fChain->SetBranchAddress("eleCrysIEta", &treeLeaf.eleCrysIEta, &b_eleCrysIEta);
//   fChain->SetBranchAddress("eleCrysIPhi", &treeLeaf.eleCrysIPhi, &b_eleCrysIPhi);
//   fChain->SetBranchAddress("eleRegrE", &treeLeaf.eleRegrE, &b_eleRegrE);
//   fChain->SetBranchAddress("eleRegrEerr", &treeLeaf.eleRegrEerr, &b_eleRegrEerr);
//   fChain->SetBranchAddress("elePhoRegrE", &treeLeaf.elePhoRegrE, &b_elePhoRegrE);
//   fChain->SetBranchAddress("elePhoRegrEerr", &treeLeaf.elePhoRegrEerr, &b_elePhoRegrEerr);
//   fChain->SetBranchAddress("eleSeedTime", &treeLeaf.eleSeedTime, &b_eleSeedTime);
//   fChain->SetBranchAddress("eleRecoFlag", &treeLeaf.eleRecoFlag, &b_eleRecoFlag);
//   fChain->SetBranchAddress("elePos", &treeLeaf.elePos, &b_elePos);
   fChain->SetBranchAddress("eleGenIndex", &treeLeaf.eleGenIndex, &b_eleGenIndex);
//   fChain->SetBranchAddress("eleGenGMomPID", &treeLeaf.eleGenGMomPID, &b_eleGenGMomPID);
//   fChain->SetBranchAddress("eleGenMomPID", &treeLeaf.eleGenMomPID, &b_eleGenMomPID);
//   fChain->SetBranchAddress("eleGenMomPt", &treeLeaf.eleGenMomPt, &b_eleGenMomPt);
//   fChain->SetBranchAddress("eleIsoTrkDR03", &treeLeaf.eleIsoTrkDR03, &b_eleIsoTrkDR03);
//   fChain->SetBranchAddress("eleIsoEcalDR03", &treeLeaf.eleIsoEcalDR03, &b_eleIsoEcalDR03);
//   fChain->SetBranchAddress("eleIsoHcalDR03", &treeLeaf.eleIsoHcalDR03, &b_eleIsoHcalDR03);
//   fChain->SetBranchAddress("eleIsoHcalDR0312", &treeLeaf.eleIsoHcalDR0312, &b_eleIsoHcalDR0312);
//   fChain->SetBranchAddress("eleIsoTrkDR04", &treeLeaf.eleIsoTrkDR04, &b_eleIsoTrkDR04);
//   fChain->SetBranchAddress("eleIsoEcalDR04", &treeLeaf.eleIsoEcalDR04, &b_eleIsoEcalDR04);
//   fChain->SetBranchAddress("eleIsoHcalDR04", &treeLeaf.eleIsoHcalDR04, &b_eleIsoHcalDR04);
//   fChain->SetBranchAddress("eleIsoHcalDR0412", &treeLeaf.eleIsoHcalDR0412, &b_eleIsoHcalDR0412);
//   fChain->SetBranchAddress("eleModIsoTrk", &treeLeaf.eleModIsoTrk, &b_eleModIsoTrk);
//   fChain->SetBranchAddress("eleModIsoEcal", &treeLeaf.eleModIsoEcal, &b_eleModIsoEcal);
//   fChain->SetBranchAddress("eleModIsoHcal", &treeLeaf.eleModIsoHcal, &b_eleModIsoHcal);
   fChain->SetBranchAddress("eleMissHits", &treeLeaf.eleMissHits, &b_eleMissHits);
//   fChain->SetBranchAddress("eleConvDist", &treeLeaf.eleConvDist, &b_eleConvDist);
//   fChain->SetBranchAddress("eleConvDcot", &treeLeaf.eleConvDcot, &b_eleConvDcot);
   fChain->SetBranchAddress("eleConvVtxFit", &treeLeaf.eleConvVtxFit, &b_eleConvVtxFit);
//   fChain->SetBranchAddress("eleIP3D", &treeLeaf.eleIP3D, &b_eleIP3D);
//   fChain->SetBranchAddress("eleIP3DErr", &treeLeaf.eleIP3DErr, &b_eleIP3DErr);
//   fChain->SetBranchAddress("eleIDMVANonTrig", &treeLeaf.eleIDMVANonTrig, &b_eleIDMVANonTrig);
//   fChain->SetBranchAddress("eleIDMVATrig", &treeLeaf.eleIDMVATrig, &b_eleIDMVATrig);
   fChain->SetBranchAddress("elePFChIso03", &treeLeaf.elePFChIso03, &b_elePFChIso03);
   fChain->SetBranchAddress("elePFPhoIso03", &treeLeaf.elePFPhoIso03, &b_elePFPhoIso03);
   fChain->SetBranchAddress("elePFNeuIso03", &treeLeaf.elePFNeuIso03, &b_elePFNeuIso03);
//   fChain->SetBranchAddress("elePFChIso04", &treeLeaf.elePFChIso04, &b_elePFChIso04);
//   fChain->SetBranchAddress("elePFPhoIso04", &treeLeaf.elePFPhoIso04, &b_elePFPhoIso04);
//   fChain->SetBranchAddress("elePFNeuIso04", &treeLeaf.elePFNeuIso04, &b_elePFNeuIso04);
//   fChain->SetBranchAddress("eleESEffSigmaRR_x", &treeLeaf.eleESEffSigmaRR_x, &b_eleESEffSigmaRR_x);
//   fChain->SetBranchAddress("eleESEffSigmaRR_y", &treeLeaf.eleESEffSigmaRR_y, &b_eleESEffSigmaRR_y);
//   fChain->SetBranchAddress("eleESEffSigmaRR_z", &treeLeaf.eleESEffSigmaRR_z, &b_eleESEffSigmaRR_z);
   fChain->SetBranchAddress("nPho", &treeLeaf.nPho, &b_nPho);
//   fChain->SetBranchAddress("phoTrg", &treeLeaf.phoTrg, &b_phoTrg);
//   fChain->SetBranchAddress("phoTrgFilter", &treeLeaf.phoTrgFilter, &b_phoTrgFilter);
//   fChain->SetBranchAddress("phoIsPhoton", &treeLeaf.phoIsPhoton, &b_phoIsPhoton);
//   fChain->SetBranchAddress("phoSCPos_x", &treeLeaf.phoSCPos_x, &b_phoSCPos_x);
//   fChain->SetBranchAddress("phoSCPos_y", &treeLeaf.phoSCPos_y, &b_phoSCPos_y);
//   fChain->SetBranchAddress("phoSCPos_z", &treeLeaf.phoSCPos_z, &b_phoSCPos_z);
//   fChain->SetBranchAddress("phoCaloPos_x", &treeLeaf.phoCaloPos_x, &b_phoCaloPos_x);
//   fChain->SetBranchAddress("phoCaloPos_y", &treeLeaf.phoCaloPos_y, &b_phoCaloPos_y);
//   fChain->SetBranchAddress("phoCaloPos_z", &treeLeaf.phoCaloPos_z, &b_phoCaloPos_z);
//   fChain->SetBranchAddress("phoE", &treeLeaf.phoE, &b_phoE);
   fChain->SetBranchAddress("phoEt", &treeLeaf.phoEt, &b_phoEt);
   fChain->SetBranchAddress("phoEta", &treeLeaf.phoEta, &b_phoEta);
//   fChain->SetBranchAddress("phoVtx_x", &treeLeaf.phoVtx_x, &b_phoVtx_x);
//   fChain->SetBranchAddress("phoVtx_y", &treeLeaf.phoVtx_y, &b_phoVtx_y);
//   fChain->SetBranchAddress("phoVtx_z", &treeLeaf.phoVtx_z, &b_phoVtx_z);
   fChain->SetBranchAddress("phoPhi", &treeLeaf.phoPhi, &b_phoPhi);
//   fChain->SetBranchAddress("phoEtVtx", &treeLeaf.phoEtVtx, &b_phoEtVtx);
//   fChain->SetBranchAddress("phoEtaVtx", &treeLeaf.phoEtaVtx, &b_phoEtaVtx);
//   fChain->SetBranchAddress("phoPhiVtx", &treeLeaf.phoPhiVtx, &b_phoPhiVtx);
   fChain->SetBranchAddress("phoR9", &treeLeaf.phoR9, &b_phoR9);
//   fChain->SetBranchAddress("phoNClus", &treeLeaf.phoNClus, &b_phoNClus);
//   fChain->SetBranchAddress("phoTrkIsoHollowDR03", &treeLeaf.phoTrkIsoHollowDR03, &b_phoTrkIsoHollowDR03);
//   fChain->SetBranchAddress("phoEcalIsoDR03", &treeLeaf.phoEcalIsoDR03, &b_phoEcalIsoDR03);
//   fChain->SetBranchAddress("phoHcalIsoDR03", &treeLeaf.phoHcalIsoDR03, &b_phoHcalIsoDR03);
//   fChain->SetBranchAddress("phoHcalIsoDR0312", &treeLeaf.phoHcalIsoDR0312, &b_phoHcalIsoDR0312);
   fChain->SetBranchAddress("phoTrkIsoHollowDR04", &treeLeaf.phoTrkIsoHollowDR04, &b_phoTrkIsoHollowDR04);
//   fChain->SetBranchAddress("phoCiCdRtoTrk", &treeLeaf.phoCiCdRtoTrk, &b_phoCiCdRtoTrk);
   fChain->SetBranchAddress("phoEcalIsoDR04", &treeLeaf.phoEcalIsoDR04, &b_phoEcalIsoDR04);
   fChain->SetBranchAddress("phoHcalIsoDR04", &treeLeaf.phoHcalIsoDR04, &b_phoHcalIsoDR04);
//   fChain->SetBranchAddress("phoHcalIsoDR0412", &treeLeaf.phoHcalIsoDR0412, &b_phoHcalIsoDR0412);
   fChain->SetBranchAddress("phoHoverE", &treeLeaf.phoHoverE, &b_phoHoverE);
   fChain->SetBranchAddress("phoHoverE12", &treeLeaf.phoHoverE12, &b_phoHoverE12);
   fChain->SetBranchAddress("phoEleVeto", &treeLeaf.phoEleVeto, &b_phoEleVeto);
   fChain->SetBranchAddress("phoSigmaIEtaIEta", &treeLeaf.phoSigmaIEtaIEta, &b_phoSigmaIEtaIEta);
//   fChain->SetBranchAddress("phoSigmaIEtaIPhi", &treeLeaf.phoSigmaIEtaIPhi, &b_phoSigmaIEtaIPhi);
//   fChain->SetBranchAddress("phoSigmaIPhiIPhi", &treeLeaf.phoSigmaIPhiIPhi, &b_phoSigmaIPhiIPhi);
//   fChain->SetBranchAddress("phoCiCPF4phopfIso03", &treeLeaf.phoCiCPF4phopfIso03, &b_phoCiCPF4phopfIso03);
//   fChain->SetBranchAddress("phoCiCPF4phopfIso04", &treeLeaf.phoCiCPF4phopfIso04, &b_phoCiCPF4phopfIso04);
//   fChain->SetBranchAddress("phoCiCPF4chgpfIso02", &treeLeaf.phoCiCPF4chgpfIso02, &b_phoCiCPF4chgpfIso02);
//   fChain->SetBranchAddress("phoCiCPF4chgpfIso03", &treeLeaf.phoCiCPF4chgpfIso03, &b_phoCiCPF4chgpfIso03);
//   fChain->SetBranchAddress("phoCiCPF4chgpfIso04", &treeLeaf.phoCiCPF4chgpfIso04, &b_phoCiCPF4chgpfIso04);
//   fChain->SetBranchAddress("phoEmax", &treeLeaf.phoEmax, &b_phoEmax);
//   fChain->SetBranchAddress("phoETop", &treeLeaf.phoETop, &b_phoETop);
//   fChain->SetBranchAddress("phoEBottom", &treeLeaf.phoEBottom, &b_phoEBottom);
//   fChain->SetBranchAddress("phoELeft", &treeLeaf.phoELeft, &b_phoELeft);
//   fChain->SetBranchAddress("phoERight", &treeLeaf.phoERight, &b_phoERight);
//   fChain->SetBranchAddress("phoE2ndMax", &treeLeaf.phoE2ndMax, &b_phoE2ndMax);
//   fChain->SetBranchAddress("phoE3x3", &treeLeaf.phoE3x3, &b_phoE3x3);
//   fChain->SetBranchAddress("phoE3x1", &treeLeaf.phoE3x1, &b_phoE3x1);
//   fChain->SetBranchAddress("phoE1x3", &treeLeaf.phoE1x3, &b_phoE1x3);
//   fChain->SetBranchAddress("phoE5x5", &treeLeaf.phoE5x5, &b_phoE5x5);
//   fChain->SetBranchAddress("phoE1x5", &treeLeaf.phoE1x5, &b_phoE1x5);
//   fChain->SetBranchAddress("phoE2x2", &treeLeaf.phoE2x2, &b_phoE2x2);
//   fChain->SetBranchAddress("phoE2x5Max", &treeLeaf.phoE2x5Max, &b_phoE2x5Max);
//   fChain->SetBranchAddress("phoE2x5Top", &treeLeaf.phoE2x5Top, &b_phoE2x5Top);
//   fChain->SetBranchAddress("phoE2x5Bottom", &treeLeaf.phoE2x5Bottom, &b_phoE2x5Bottom);
//   fChain->SetBranchAddress("phoE2x5Left", &treeLeaf.phoE2x5Left, &b_phoE2x5Left);
//   fChain->SetBranchAddress("phoE2x5Right", &treeLeaf.phoE2x5Right, &b_phoE2x5Right);
//   fChain->SetBranchAddress("phoSeedE", &treeLeaf.phoSeedE, &b_phoSeedE);
//   fChain->SetBranchAddress("phoSeedEta", &treeLeaf.phoSeedEta, &b_phoSeedEta);
//   fChain->SetBranchAddress("phoSeedPhi", &treeLeaf.phoSeedPhi, &b_phoSeedPhi);
//   fChain->SetBranchAddress("phoCrysEta", &treeLeaf.phoCrysEta, &b_phoCrysEta);
//   fChain->SetBranchAddress("phoCrysPhi", &treeLeaf.phoCrysPhi, &b_phoCrysPhi);
//   fChain->SetBranchAddress("phoCrysIEta", &treeLeaf.phoCrysIEta, &b_phoCrysIEta);
//   fChain->SetBranchAddress("phoCrysIPhi", &treeLeaf.phoCrysIPhi, &b_phoCrysIPhi);
   fChain->SetBranchAddress("phoPFChIso", &treeLeaf.phoPFChIso, &b_phoPFChIso);
   fChain->SetBranchAddress("phoPFPhoIso", &treeLeaf.phoPFPhoIso, &b_phoPFPhoIso);
   fChain->SetBranchAddress("phoPFNeuIso", &treeLeaf.phoPFNeuIso, &b_phoPFNeuIso);
   fChain->SetBranchAddress("phoSCRChIso", &treeLeaf.phoSCRChIso, &b_phoSCRChIso);
   fChain->SetBranchAddress("phoSCRPhoIso", &treeLeaf.phoSCRPhoIso, &b_phoSCRPhoIso);
   fChain->SetBranchAddress("phoSCRNeuIso", &treeLeaf.phoSCRNeuIso, &b_phoSCRNeuIso);
   fChain->SetBranchAddress("phoSCRChIso04", &treeLeaf.phoSCRChIso04, &b_phoSCRChIso04);
   fChain->SetBranchAddress("phoSCRPhoIso04", &treeLeaf.phoSCRPhoIso04, &b_phoSCRPhoIso04);
   fChain->SetBranchAddress("phoSCRNeuIso04", &treeLeaf.phoSCRNeuIso04, &b_phoSCRNeuIso04);
   fChain->SetBranchAddress("phoRandConeChIso", &treeLeaf.phoRandConeChIso, &b_phoRandConeChIso);
   fChain->SetBranchAddress("phoRandConePhoIso", &treeLeaf.phoRandConePhoIso, &b_phoRandConePhoIso);
   fChain->SetBranchAddress("phoRandConeNeuIso", &treeLeaf.phoRandConeNeuIso, &b_phoRandConeNeuIso);
   fChain->SetBranchAddress("phoRandConeChIso04", &treeLeaf.phoRandConeChIso04, &b_phoRandConeChIso04);
   fChain->SetBranchAddress("phoRandConePhoIso04", &treeLeaf.phoRandConePhoIso04, &b_phoRandConePhoIso04);
   fChain->SetBranchAddress("phoRandConeNeuIso04", &treeLeaf.phoRandConeNeuIso04, &b_phoRandConeNeuIso04);
//   fChain->SetBranchAddress("phoRegrE", &treeLeaf.phoRegrE, &b_phoRegrE);
//   fChain->SetBranchAddress("phoRegrEerr", &treeLeaf.phoRegrEerr, &b_phoRegrEerr);
//   fChain->SetBranchAddress("phoSeedTime", &treeLeaf.phoSeedTime, &b_phoSeedTime);
//   fChain->SetBranchAddress("phoSeedDetId1", &treeLeaf.phoSeedDetId1, &b_phoSeedDetId1);
//   fChain->SetBranchAddress("phoSeedDetId2", &treeLeaf.phoSeedDetId2, &b_phoSeedDetId2);
//   fChain->SetBranchAddress("phoLICTD", &treeLeaf.phoLICTD, &b_phoLICTD);
//   fChain->SetBranchAddress("phoRecoFlag", &treeLeaf.phoRecoFlag, &b_phoRecoFlag);
//   fChain->SetBranchAddress("phoPos", &treeLeaf.phoPos, &b_phoPos);
   fChain->SetBranchAddress("phoGenIndex", &treeLeaf.phoGenIndex, &b_phoGenIndex);
//   fChain->SetBranchAddress("phoGenGMomPID", &treeLeaf.phoGenGMomPID, &b_phoGenGMomPID);
   fChain->SetBranchAddress("phoGenMomPID", &treeLeaf.phoGenMomPID, &b_phoGenMomPID);
//   fChain->SetBranchAddress("phoGenMomPt", &treeLeaf.phoGenMomPt, &b_phoGenMomPt);
//   fChain->SetBranchAddress("phoSCE", &treeLeaf.phoSCE, &b_phoSCE);
//   fChain->SetBranchAddress("phoSCRawE", &treeLeaf.phoSCRawE, &b_phoSCRawE);
//   fChain->SetBranchAddress("phoESEn", &treeLeaf.phoESEn, &b_phoESEn);
   fChain->SetBranchAddress("phoSCEt", &treeLeaf.phoSCEt, &b_phoSCEt);
   fChain->SetBranchAddress("phoSCEta", &treeLeaf.phoSCEta, &b_phoSCEta);
   fChain->SetBranchAddress("phoSCPhi", &treeLeaf.phoSCPhi, &b_phoSCPhi);
//   fChain->SetBranchAddress("phoSCEtaWidth", &treeLeaf.phoSCEtaWidth, &b_phoSCEtaWidth);
//   fChain->SetBranchAddress("phoSCPhiWidth", &treeLeaf.phoSCPhiWidth, &b_phoSCPhiWidth);
//   fChain->SetBranchAddress("phoSCBrem", &treeLeaf.phoSCBrem, &b_phoSCBrem);
//   fChain->SetBranchAddress("phoOverlap", &treeLeaf.phoOverlap, &b_phoOverlap);
   fChain->SetBranchAddress("phohasPixelSeed", &treeLeaf.phohasPixelSeed, &b_phohasPixelSeed);
//   fChain->SetBranchAddress("pho_hasConvPf", &treeLeaf.pho_hasConvPf, &b_pho_hasConvPf);
//   fChain->SetBranchAddress("pho_hasSLConvPf", &treeLeaf.pho_hasSLConvPf, &b_pho_hasSLConvPf);
//   fChain->SetBranchAddress("pho_pfconvVtxZ", &treeLeaf.pho_pfconvVtxZ, &b_pho_pfconvVtxZ);
//   fChain->SetBranchAddress("pho_pfconvVtxZErr", &treeLeaf.pho_pfconvVtxZErr, &b_pho_pfconvVtxZErr);
//   fChain->SetBranchAddress("pho_nSLConv", &treeLeaf.pho_nSLConv, &b_pho_nSLConv);
//   fChain->SetBranchAddress("pho_pfSLConvPos_x", &treeLeaf.pho_pfSLConvPos_x, &b_pho_pfSLConvPos_x);
//   fChain->SetBranchAddress("pho_pfSLConvPos_y", &treeLeaf.pho_pfSLConvPos_y, &b_pho_pfSLConvPos_y);
//   fChain->SetBranchAddress("pho_pfSLConvPos_z", &treeLeaf.pho_pfSLConvPos_z, &b_pho_pfSLConvPos_z);
//   fChain->SetBranchAddress("pho_pfSLConvVtxZ", &treeLeaf.pho_pfSLConvVtxZ, &b_pho_pfSLConvVtxZ);
//   fChain->SetBranchAddress("phoIsConv", &treeLeaf.phoIsConv, &b_phoIsConv);
//   fChain->SetBranchAddress("phoNConv", &treeLeaf.phoNConv, &b_phoNConv);
//   fChain->SetBranchAddress("phoConvInvMass", &treeLeaf.phoConvInvMass, &b_phoConvInvMass);
//   fChain->SetBranchAddress("phoConvCotTheta", &treeLeaf.phoConvCotTheta, &b_phoConvCotTheta);
//   fChain->SetBranchAddress("phoConvEoverP", &treeLeaf.phoConvEoverP, &b_phoConvEoverP);
//   fChain->SetBranchAddress("phoConvZofPVfromTrks", &treeLeaf.phoConvZofPVfromTrks, &b_phoConvZofPVfromTrks);
//   fChain->SetBranchAddress("phoConvMinDist", &treeLeaf.phoConvMinDist, &b_phoConvMinDist);
//   fChain->SetBranchAddress("phoConvdPhiAtVtx", &treeLeaf.phoConvdPhiAtVtx, &b_phoConvdPhiAtVtx);
//   fChain->SetBranchAddress("phoConvdPhiAtCalo", &treeLeaf.phoConvdPhiAtCalo, &b_phoConvdPhiAtCalo);
//   fChain->SetBranchAddress("phoConvdEtaAtCalo", &treeLeaf.phoConvdEtaAtCalo, &b_phoConvdEtaAtCalo);
//   fChain->SetBranchAddress("phoConvTrkd0_x", &treeLeaf.phoConvTrkd0_x, &b_phoConvTrkd0_x);
//   fChain->SetBranchAddress("phoConvTrkd0_y", &treeLeaf.phoConvTrkd0_y, &b_phoConvTrkd0_y);
//   fChain->SetBranchAddress("phoConvTrkPin_x", &treeLeaf.phoConvTrkPin_x, &b_phoConvTrkPin_x);
//   fChain->SetBranchAddress("phoConvTrkPin_y", &treeLeaf.phoConvTrkPin_y, &b_phoConvTrkPin_y);
//   fChain->SetBranchAddress("phoConvTrkPout_x", &treeLeaf.phoConvTrkPout_x, &b_phoConvTrkPout_x);
//   fChain->SetBranchAddress("phoConvTrkPout_y", &treeLeaf.phoConvTrkPout_y, &b_phoConvTrkPout_y);
//   fChain->SetBranchAddress("phoConvTrkdz_x", &treeLeaf.phoConvTrkdz_x, &b_phoConvTrkdz_x);
//   fChain->SetBranchAddress("phoConvTrkdz_y", &treeLeaf.phoConvTrkdz_y, &b_phoConvTrkdz_y);
//   fChain->SetBranchAddress("phoConvTrkdzErr_x", &treeLeaf.phoConvTrkdzErr_x, &b_phoConvTrkdzErr_x);
//   fChain->SetBranchAddress("phoConvTrkdzErr_y", &treeLeaf.phoConvTrkdzErr_y, &b_phoConvTrkdzErr_y);
//   fChain->SetBranchAddress("phoConvChi2", &treeLeaf.phoConvChi2, &b_phoConvChi2);
//   fChain->SetBranchAddress("phoConvChi2Prob", &treeLeaf.phoConvChi2Prob, &b_phoConvChi2Prob);
//   fChain->SetBranchAddress("phoConvNTrks", &treeLeaf.phoConvNTrks, &b_phoConvNTrks);
//   fChain->SetBranchAddress("phoConvCharge1", &treeLeaf.phoConvCharge1, &b_phoConvCharge1);
//   fChain->SetBranchAddress("phoConvCharge2", &treeLeaf.phoConvCharge2, &b_phoConvCharge2);
//   fChain->SetBranchAddress("phoConvValidVtx", &treeLeaf.phoConvValidVtx, &b_phoConvValidVtx);
//   fChain->SetBranchAddress("phoConvLikeLihood", &treeLeaf.phoConvLikeLihood, &b_phoConvLikeLihood);
//   fChain->SetBranchAddress("phoConvP4_0", &treeLeaf.phoConvP4_0, &b_phoConvP4_0);
//   fChain->SetBranchAddress("phoConvP4_1", &treeLeaf.phoConvP4_1, &b_phoConvP4_1);
//   fChain->SetBranchAddress("phoConvP4_2", &treeLeaf.phoConvP4_2, &b_phoConvP4_2);
//   fChain->SetBranchAddress("phoConvP4_3", &treeLeaf.phoConvP4_3, &b_phoConvP4_3);
//   fChain->SetBranchAddress("phoConvVtx_x", &treeLeaf.phoConvVtx_x, &b_phoConvVtx_x);
//   fChain->SetBranchAddress("phoConvVtx_y", &treeLeaf.phoConvVtx_y, &b_phoConvVtx_y);
//   fChain->SetBranchAddress("phoConvVtx_z", &treeLeaf.phoConvVtx_z, &b_phoConvVtx_z);
//   fChain->SetBranchAddress("phoConvVtxErr_x", &treeLeaf.phoConvVtxErr_x, &b_phoConvVtxErr_x);
//   fChain->SetBranchAddress("phoConvVtxErr_y", &treeLeaf.phoConvVtxErr_y, &b_phoConvVtxErr_y);
//   fChain->SetBranchAddress("phoConvVtxErr_z", &treeLeaf.phoConvVtxErr_z, &b_phoConvVtxErr_z);
//   fChain->SetBranchAddress("phoConvPairMomentum_x", &treeLeaf.phoConvPairMomentum_x, &b_phoConvPairMomentum_x);
//   fChain->SetBranchAddress("phoConvPairMomentum_y", &treeLeaf.phoConvPairMomentum_y, &b_phoConvPairMomentum_y);
//   fChain->SetBranchAddress("phoConvPairMomentum_z", &treeLeaf.phoConvPairMomentum_z, &b_phoConvPairMomentum_z);
//   fChain->SetBranchAddress("phoConvRefittedMomentum_x", &treeLeaf.phoConvRefittedMomentum_x, &b_phoConvRefittedMomentum_x);
//   fChain->SetBranchAddress("phoConvRefittedMomentum_y", &treeLeaf.phoConvRefittedMomentum_y, &b_phoConvRefittedMomentum_y);
//   fChain->SetBranchAddress("phoConvRefittedMomentum_z", &treeLeaf.phoConvRefittedMomentum_z, &b_phoConvRefittedMomentum_z);
//   fChain->SetBranchAddress("SingleLegConv", &treeLeaf.SingleLegConv, &b_SingleLegConv);
//   fChain->SetBranchAddress("phoPFConvVtx_x", &treeLeaf.phoPFConvVtx_x, &b_phoPFConvVtx_x);
//   fChain->SetBranchAddress("phoPFConvVtx_y", &treeLeaf.phoPFConvVtx_y, &b_phoPFConvVtx_y);
//   fChain->SetBranchAddress("phoPFConvVtx_z", &treeLeaf.phoPFConvVtx_z, &b_phoPFConvVtx_z);
//   fChain->SetBranchAddress("phoPFConvMom_x", &treeLeaf.phoPFConvMom_x, &b_phoPFConvMom_x);
//   fChain->SetBranchAddress("phoPFConvMom_y", &treeLeaf.phoPFConvMom_y, &b_phoPFConvMom_y);
//   fChain->SetBranchAddress("phoPFConvMom_z", &treeLeaf.phoPFConvMom_z, &b_phoPFConvMom_z);
//   fChain->SetBranchAddress("phoESEffSigmaRR_x", &treeLeaf.phoESEffSigmaRR_x, &b_phoESEffSigmaRR_x);
//   fChain->SetBranchAddress("phoESEffSigmaRR_y", &treeLeaf.phoESEffSigmaRR_y, &b_phoESEffSigmaRR_y);
//   fChain->SetBranchAddress("phoESEffSigmaRR_z", &treeLeaf.phoESEffSigmaRR_z, &b_phoESEffSigmaRR_z);
   fChain->SetBranchAddress("nMu", &treeLeaf.nMu, &b_nMu);
   fChain->SetBranchAddress("muTrg", &treeLeaf.muTrg, &b_muTrg);
   fChain->SetBranchAddress("muEta", &treeLeaf.muEta, &b_muEta);
   fChain->SetBranchAddress("muPhi", &treeLeaf.muPhi, &b_muPhi);
//   fChain->SetBranchAddress("muCharge", &treeLeaf.muCharge, &b_muCharge);
   fChain->SetBranchAddress("muPt", &treeLeaf.muPt, &b_muPt);
//   fChain->SetBranchAddress("muPz", &treeLeaf.muPz, &b_muPz);
//   fChain->SetBranchAddress("muVtx_x", &treeLeaf.muVtx_x, &b_muVtx_x);
//   fChain->SetBranchAddress("muVtx_y", &treeLeaf.muVtx_y, &b_muVtx_y);
//   fChain->SetBranchAddress("muVtx_z", &treeLeaf.muVtx_z, &b_muVtx_z);
//   fChain->SetBranchAddress("muVtxGlb_x", &treeLeaf.muVtxGlb_x, &b_muVtxGlb_x);
//   fChain->SetBranchAddress("muVtxGlb_y", &treeLeaf.muVtxGlb_y, &b_muVtxGlb_y);
//   fChain->SetBranchAddress("muVtxGlb_z", &treeLeaf.muVtxGlb_z, &b_muVtxGlb_z);
   fChain->SetBranchAddress("muGenIndex", &treeLeaf.muGenIndex, &b_muGenIndex);
//   fChain->SetBranchAddress("mucktPt", &treeLeaf.mucktPt, &b_mucktPt);
//   fChain->SetBranchAddress("mucktPtErr", &treeLeaf.mucktPtErr, &b_mucktPtErr);
//   fChain->SetBranchAddress("mucktEta", &treeLeaf.mucktEta, &b_mucktEta);
//   fChain->SetBranchAddress("mucktPhi", &treeLeaf.mucktPhi, &b_mucktPhi);
//   fChain->SetBranchAddress("mucktdxy", &treeLeaf.mucktdxy, &b_mucktdxy);
//   fChain->SetBranchAddress("mucktdz", &treeLeaf.mucktdz, &b_mucktdz);
   fChain->SetBranchAddress("muIsoTrk", &treeLeaf.muIsoTrk, &b_muIsoTrk);
//   fChain->SetBranchAddress("muIsoCalo", &treeLeaf.muIsoCalo, &b_muIsoCalo);
   fChain->SetBranchAddress("muIsoEcal", &treeLeaf.muIsoEcal, &b_muIsoEcal);
   fChain->SetBranchAddress("muIsoHcal", &treeLeaf.muIsoHcal, &b_muIsoHcal);
   fChain->SetBranchAddress("muChi2NDF", &treeLeaf.muChi2NDF, &b_muChi2NDF);
//   fChain->SetBranchAddress("muInnerChi2NDF", &treeLeaf.muInnerChi2NDF, &b_muInnerChi2NDF);
   fChain->SetBranchAddress("muPFIsoR04_CH", &treeLeaf.muPFIsoR04_CH, &b_muPFIsoR04_CH);
   fChain->SetBranchAddress("muPFIsoR04_NH", &treeLeaf.muPFIsoR04_NH, &b_muPFIsoR04_NH);
   fChain->SetBranchAddress("muPFIsoR04_Pho", &treeLeaf.muPFIsoR04_Pho, &b_muPFIsoR04_Pho);
   fChain->SetBranchAddress("muPFIsoR04_PU", &treeLeaf.muPFIsoR04_PU, &b_muPFIsoR04_PU);
//   fChain->SetBranchAddress("muPFIsoR04_CPart", &treeLeaf.muPFIsoR04_CPart, &b_muPFIsoR04_CPart);
//   fChain->SetBranchAddress("muPFIsoR04_NHHT", &treeLeaf.muPFIsoR04_NHHT, &b_muPFIsoR04_NHHT);
//   fChain->SetBranchAddress("muPFIsoR04_PhoHT", &treeLeaf.muPFIsoR04_PhoHT, &b_muPFIsoR04_PhoHT);
//   fChain->SetBranchAddress("muPFIsoR03_CH", &treeLeaf.muPFIsoR03_CH, &b_muPFIsoR03_CH);
//   fChain->SetBranchAddress("muPFIsoR03_NH", &treeLeaf.muPFIsoR03_NH, &b_muPFIsoR03_NH);
//   fChain->SetBranchAddress("muPFIsoR03_Pho", &treeLeaf.muPFIsoR03_Pho, &b_muPFIsoR03_Pho);
//   fChain->SetBranchAddress("muPFIsoR03_PU", &treeLeaf.muPFIsoR03_PU, &b_muPFIsoR03_PU);
//   fChain->SetBranchAddress("muPFIsoR03_CPart", &treeLeaf.muPFIsoR03_CPart, &b_muPFIsoR03_CPart);
//   fChain->SetBranchAddress("muPFIsoR03_NHHT", &treeLeaf.muPFIsoR03_NHHT, &b_muPFIsoR03_NHHT);
//   fChain->SetBranchAddress("muPFIsoR03_PhoHT", &treeLeaf.muPFIsoR03_PhoHT, &b_muPFIsoR03_PhoHT);
   fChain->SetBranchAddress("muType", &treeLeaf.muType, &b_muType);
   fChain->SetBranchAddress("muD0", &treeLeaf.muD0, &b_muD0);
   fChain->SetBranchAddress("muDz", &treeLeaf.muDz, &b_muDz);
//   fChain->SetBranchAddress("muD0GV", &treeLeaf.muD0GV, &b_muD0GV);
//   fChain->SetBranchAddress("muDzGV", &treeLeaf.muDzGV, &b_muDzGV);
//   fChain->SetBranchAddress("muD0Vtx", &treeLeaf.muD0Vtx, &b_muD0Vtx);
//   fChain->SetBranchAddress("muDzVtx", &treeLeaf.muDzVtx, &b_muDzVtx);
//   fChain->SetBranchAddress("muInnerD0", &treeLeaf.muInnerD0, &b_muInnerD0);
//   fChain->SetBranchAddress("muInnerDz", &treeLeaf.muInnerDz, &b_muInnerDz);
   fChain->SetBranchAddress("muInnerD0GV", &treeLeaf.muInnerD0GV, &b_muInnerD0GV);
   fChain->SetBranchAddress("muInnerDzGV", &treeLeaf.muInnerDzGV, &b_muInnerDzGV);
//   fChain->SetBranchAddress("muInnerPt", &treeLeaf.muInnerPt, &b_muInnerPt);
//   fChain->SetBranchAddress("muInnerPtErr", &treeLeaf.muInnerPtErr, &b_muInnerPtErr);
   fChain->SetBranchAddress("muNumberOfValidTrkLayers", &treeLeaf.muNumberOfValidTrkLayers, &b_muNumberOfValidTrkLayers);
   fChain->SetBranchAddress("muNumberOfValidTrkHits", &treeLeaf.muNumberOfValidTrkHits, &b_muNumberOfValidTrkHits);
//   fChain->SetBranchAddress("muNumberOfValidPixelLayers", &treeLeaf.muNumberOfValidPixelLayers, &b_muNumberOfValidPixelLayers);
   fChain->SetBranchAddress("muNumberOfValidPixelHits", &treeLeaf.muNumberOfValidPixelHits, &b_muNumberOfValidPixelHits);
   fChain->SetBranchAddress("muNumberOfValidMuonHits", &treeLeaf.muNumberOfValidMuonHits, &b_muNumberOfValidMuonHits);
   fChain->SetBranchAddress("muStations", &treeLeaf.muStations, &b_muStations);
//   fChain->SetBranchAddress("muChambers", &treeLeaf.muChambers, &b_muChambers);
//   fChain->SetBranchAddress("muIP3D", &treeLeaf.muIP3D, &b_muIP3D);
//   fChain->SetBranchAddress("muIP3DErr", &treeLeaf.muIP3DErr, &b_muIP3DErr);
//   fChain->SetBranchAddress("nTau", &treeLeaf.nTau, &b_nTau);
//   fChain->SetBranchAddress("tauDecayModeFinding", &treeLeaf.tauDecayModeFinding, &b_tauDecayModeFinding);
//   fChain->SetBranchAddress("tauAgainstElectronLooseMVA3", &treeLeaf.tauAgainstElectronLooseMVA3, &b_tauAgainstElectronLooseMVA3);
//   fChain->SetBranchAddress("tauAgainstElectronMediumMVA3", &treeLeaf.tauAgainstElectronMediumMVA3, &b_tauAgainstElectronMediumMVA3);
//   fChain->SetBranchAddress("tauAgainstElectronTightMVA3", &treeLeaf.tauAgainstElectronTightMVA3, &b_tauAgainstElectronTightMVA3);
//   fChain->SetBranchAddress("tauAgainstElectronVTightMVA3", &treeLeaf.tauAgainstElectronVTightMVA3, &b_tauAgainstElectronVTightMVA3);
//   fChain->SetBranchAddress("tauAgainstElectronDeadECAL", &treeLeaf.tauAgainstElectronDeadECAL, &b_tauAgainstElectronDeadECAL);
//   fChain->SetBranchAddress("tauAgainstMuonLoose2", &treeLeaf.tauAgainstMuonLoose2, &b_tauAgainstMuonLoose2);
//   fChain->SetBranchAddress("tauAgainstMuonMedium2", &treeLeaf.tauAgainstMuonMedium2, &b_tauAgainstMuonMedium2);
//   fChain->SetBranchAddress("tauAgainstMuonTight2", &treeLeaf.tauAgainstMuonTight2, &b_tauAgainstMuonTight2);
//   fChain->SetBranchAddress("tauCombinedIsolationDeltaBetaCorrRaw3Hits", &treeLeaf.tauCombinedIsolationDeltaBetaCorrRaw3Hits, &b_tauCombinedIsolationDeltaBetaCorrRaw3Hits);
//   fChain->SetBranchAddress("tauLooseCombinedIsolationDeltaBetaCorr3Hits", &treeLeaf.tauLooseCombinedIsolationDeltaBetaCorr3Hits, &b_tauLooseCombinedIsolationDeltaBetaCorr3Hits);
//   fChain->SetBranchAddress("tauMediumCombinedIsolationDeltaBetaCorr3Hits", &treeLeaf.tauMediumCombinedIsolationDeltaBetaCorr3Hits, &b_tauMediumCombinedIsolationDeltaBetaCorr3Hits);
//   fChain->SetBranchAddress("tauTightCombinedIsolationDeltaBetaCorr3Hits", &treeLeaf.tauTightCombinedIsolationDeltaBetaCorr3Hits, &b_tauTightCombinedIsolationDeltaBetaCorr3Hits);
//   fChain->SetBranchAddress("tauEta", &treeLeaf.tauEta, &b_tauEta);
//   fChain->SetBranchAddress("tauPhi", &treeLeaf.tauPhi, &b_tauPhi);
//   fChain->SetBranchAddress("tauPt", &treeLeaf.tauPt, &b_tauPt);
//   fChain->SetBranchAddress("tauEt", &treeLeaf.tauEt, &b_tauEt);
//   fChain->SetBranchAddress("tauCharge", &treeLeaf.tauCharge, &b_tauCharge);
//   fChain->SetBranchAddress("tauDecayMode", &treeLeaf.tauDecayMode, &b_tauDecayMode);
//   fChain->SetBranchAddress("tauEMFraction", &treeLeaf.tauEMFraction, &b_tauEMFraction);
//   fChain->SetBranchAddress("tauHCAL3x3OverPLead", &treeLeaf.tauHCAL3x3OverPLead, &b_tauHCAL3x3OverPLead);
//   fChain->SetBranchAddress("tauHCALMaxOverPLead", &treeLeaf.tauHCALMaxOverPLead, &b_tauHCALMaxOverPLead);
//   fChain->SetBranchAddress("tauHCALTotOverPLead", &treeLeaf.tauHCALTotOverPLead, &b_tauHCALTotOverPLead);
//   fChain->SetBranchAddress("tauIsolationPFChargedHadrCandsPtSum", &treeLeaf.tauIsolationPFChargedHadrCandsPtSum, &b_tauIsolationPFChargedHadrCandsPtSum);
//   fChain->SetBranchAddress("tauIsolationPFGammaCandsEtSum", &treeLeaf.tauIsolationPFGammaCandsEtSum, &b_tauIsolationPFGammaCandsEtSum);
//   fChain->SetBranchAddress("tauLeadPFChargedHadrCandsignedSipt", &treeLeaf.tauLeadPFChargedHadrCandsignedSipt, &b_tauLeadPFChargedHadrCandsignedSipt);
//   fChain->SetBranchAddress("tauLeadChargedHadronExists", &treeLeaf.tauLeadChargedHadronExists, &b_tauLeadChargedHadronExists);
//   fChain->SetBranchAddress("tauLeadChargedHadronEta", &treeLeaf.tauLeadChargedHadronEta, &b_tauLeadChargedHadronEta);
//   fChain->SetBranchAddress("tauLeadChargedHadronPhi", &treeLeaf.tauLeadChargedHadronPhi, &b_tauLeadChargedHadronPhi);
//   fChain->SetBranchAddress("tauLeadChargedHadronPt", &treeLeaf.tauLeadChargedHadronPt, &b_tauLeadChargedHadronPt);
//   fChain->SetBranchAddress("rho25", &treeLeaf.rho25, &b_rho25);
//   fChain->SetBranchAddress("rho25_neu", &treeLeaf.rho25_neu, &b_rho25_neu);
//   fChain->SetBranchAddress("rho25_muPFiso", &treeLeaf.rho25_muPFiso, &b_rho25_muPFiso);
//   fChain->SetBranchAddress("rho25_elePFiso", &treeLeaf.rho25_elePFiso, &b_rho25_elePFiso);
   fChain->SetBranchAddress("rho2011", &treeLeaf.rho2011, &b_rho2011);
   fChain->SetBranchAddress("rho2012", &treeLeaf.rho2012, &b_rho2012);
//   fChain->SetBranchAddress("QGTag_MLP", &treeLeaf.QGTag_MLP, &b_QGTag_MLP);
//   fChain->SetBranchAddress("QGTag_likelihood", &treeLeaf.QGTag_likelihood, &b_QGTag_likelihood);
//   fChain->SetBranchAddress("nCA8Jet", &treeLeaf.nCA8Jet, &b_nCA8Jet);
//   fChain->SetBranchAddress("CA8JetPt", &treeLeaf.CA8JetPt, &b_CA8JetPt);
//   fChain->SetBranchAddress("CA8JetEta", &treeLeaf.CA8JetEta, &b_CA8JetEta);
//   fChain->SetBranchAddress("CA8JetPhi", &treeLeaf.CA8JetPhi, &b_CA8JetPhi);
//   fChain->SetBranchAddress("CA8JetMass", &treeLeaf.CA8JetMass, &b_CA8JetMass);
//   fChain->SetBranchAddress("CA8JetArea", &treeLeaf.CA8JetArea, &b_CA8JetArea);
//   fChain->SetBranchAddress("CA8Jet_tau1", &treeLeaf.CA8Jet_tau1, &b_CA8Jet_tau1);
//   fChain->SetBranchAddress("CA8Jet_tau2", &treeLeaf.CA8Jet_tau2, &b_CA8Jet_tau2);
//   fChain->SetBranchAddress("CA8Jet_tau3", &treeLeaf.CA8Jet_tau3, &b_CA8Jet_tau3);
//   fChain->SetBranchAddress("CA8JetCHF", &treeLeaf.CA8JetCHF, &b_CA8JetCHF);
//   fChain->SetBranchAddress("CA8JetNHF", &treeLeaf.CA8JetNHF, &b_CA8JetNHF);
//   fChain->SetBranchAddress("CA8JetCEF", &treeLeaf.CA8JetCEF, &b_CA8JetCEF);
//   fChain->SetBranchAddress("CA8JetNEF", &treeLeaf.CA8JetNEF, &b_CA8JetNEF);
//   fChain->SetBranchAddress("CA8JetNCH", &treeLeaf.CA8JetNCH, &b_CA8JetNCH);
//   fChain->SetBranchAddress("CA8Jetnconstituents", &treeLeaf.CA8Jetnconstituents, &b_CA8Jetnconstituents);
//   fChain->SetBranchAddress("CA8prunedJetMass", &treeLeaf.CA8prunedJetMass, &b_CA8prunedJetMass);
//   fChain->SetBranchAddress("CA8prunedJet_nSubJets", &treeLeaf.CA8prunedJet_nSubJets, &b_CA8prunedJet_nSubJets);
//   fChain->SetBranchAddress("CA8prunedJet_SubjetPt", &treeLeaf.CA8prunedJet_SubjetPt, &b_CA8prunedJet_SubjetPt);
//   fChain->SetBranchAddress("CA8prunedJet_SubjetEta", &treeLeaf.CA8prunedJet_SubjetEta, &b_CA8prunedJet_SubjetEta);
//   fChain->SetBranchAddress("CA8prunedJet_SubjetPhi", &treeLeaf.CA8prunedJet_SubjetPhi, &b_CA8prunedJet_SubjetPhi);
//   fChain->SetBranchAddress("CA8prunedJet_SubjetMass", &treeLeaf.CA8prunedJet_SubjetMass, &b_CA8prunedJet_SubjetMass);
   fChain->SetBranchAddress("nJet", &treeLeaf.nJet, &b_nJet);
//   fChain->SetBranchAddress("jetTrg", &treeLeaf.jetTrg, &b_jetTrg);
//   fChain->SetBranchAddress("jetEn", &treeLeaf.jetEn, &b_jetEn);
   fChain->SetBranchAddress("jetPt", &treeLeaf.jetPt, &b_jetPt);
   fChain->SetBranchAddress("jetEta", &treeLeaf.jetEta, &b_jetEta);
   fChain->SetBranchAddress("jetPhi", &treeLeaf.jetPhi, &b_jetPhi);
//   fChain->SetBranchAddress("jetCharge", &treeLeaf.jetCharge, &b_jetCharge);
//   fChain->SetBranchAddress("jetEt", &treeLeaf.jetEt, &b_jetEt);
   fChain->SetBranchAddress("jetRawPt", &treeLeaf.jetRawPt, &b_jetRawPt);
   fChain->SetBranchAddress("jetRawEn", &treeLeaf.jetRawEn, &b_jetRawEn);
//   fChain->SetBranchAddress("jetArea", &treeLeaf.jetArea, &b_jetArea);
//   fChain->SetBranchAddress("jetCHF", &treeLeaf.jetCHF, &b_jetCHF);
//   fChain->SetBranchAddress("jetNHF", &treeLeaf.jetNHF, &b_jetNHF);
//   fChain->SetBranchAddress("jetCEF", &treeLeaf.jetCEF, &b_jetCEF);
//   fChain->SetBranchAddress("jetNEF", &treeLeaf.jetNEF, &b_jetNEF);
//   fChain->SetBranchAddress("jetNCH", &treeLeaf.jetNCH, &b_jetNCH);
//   fChain->SetBranchAddress("jetHFHAE", &treeLeaf.jetHFHAE, &b_jetHFHAE);
//   fChain->SetBranchAddress("jetHFEME", &treeLeaf.jetHFEME, &b_jetHFEME);
//   fChain->SetBranchAddress("jetNConstituents", &treeLeaf.jetNConstituents, &b_jetNConstituents);
//   fChain->SetBranchAddress("jetCombinedSecondaryVtxBJetTags", &treeLeaf.jetCombinedSecondaryVtxBJetTags, &b_jetCombinedSecondaryVtxBJetTags);
//   fChain->SetBranchAddress("jetCombinedSecondaryVtxMVABJetTags", &treeLeaf.jetCombinedSecondaryVtxMVABJetTags, &b_jetCombinedSecondaryVtxMVABJetTags);
//   fChain->SetBranchAddress("jetJetProbabilityBJetTags", &treeLeaf.jetJetProbabilityBJetTags, &b_jetJetProbabilityBJetTags);
//   fChain->SetBranchAddress("jetJetBProbabilityBJetTags", &treeLeaf.jetJetBProbabilityBJetTags, &b_jetJetBProbabilityBJetTags);
//   fChain->SetBranchAddress("jetBetaStar", &treeLeaf.jetBetaStar, &b_jetBetaStar);
//   fChain->SetBranchAddress("jetPFLooseId", &treeLeaf.jetPFLooseId, &b_jetPFLooseId);
//   fChain->SetBranchAddress("jetDRMean", &treeLeaf.jetDRMean, &b_jetDRMean);
//   fChain->SetBranchAddress("jetDR2Mean", &treeLeaf.jetDR2Mean, &b_jetDR2Mean);
//   fChain->SetBranchAddress("jetDZ", &treeLeaf.jetDZ, &b_jetDZ);
//   fChain->SetBranchAddress("jetFrac01", &treeLeaf.jetFrac01, &b_jetFrac01);
//   fChain->SetBranchAddress("jetFrac02", &treeLeaf.jetFrac02, &b_jetFrac02);
//   fChain->SetBranchAddress("jetFrac03", &treeLeaf.jetFrac03, &b_jetFrac03);
//   fChain->SetBranchAddress("jetFrac04", &treeLeaf.jetFrac04, &b_jetFrac04);
//   fChain->SetBranchAddress("jetFrac05", &treeLeaf.jetFrac05, &b_jetFrac05);
//   fChain->SetBranchAddress("jetFrac06", &treeLeaf.jetFrac06, &b_jetFrac06);
//   fChain->SetBranchAddress("jetFrac07", &treeLeaf.jetFrac07, &b_jetFrac07);
//   fChain->SetBranchAddress("jetBeta", &treeLeaf.jetBeta, &b_jetBeta);
//   fChain->SetBranchAddress("jetBetaStarCMG", &treeLeaf.jetBetaStarCMG, &b_jetBetaStarCMG);
//   fChain->SetBranchAddress("jetBetaStarClassic", &treeLeaf.jetBetaStarClassic, &b_jetBetaStarClassic);
//   fChain->SetBranchAddress("jetBetaExt", &treeLeaf.jetBetaExt, &b_jetBetaExt);
//   fChain->SetBranchAddress("jetBetaStarCMGExt", &treeLeaf.jetBetaStarCMGExt, &b_jetBetaStarCMGExt);
//   fChain->SetBranchAddress("jetBetaStarClassicExt", &treeLeaf.jetBetaStarClassicExt, &b_jetBetaStarClassicExt);
//   fChain->SetBranchAddress("jetNNeutrals", &treeLeaf.jetNNeutrals, &b_jetNNeutrals);
//   fChain->SetBranchAddress("jetNCharged", &treeLeaf.jetNCharged, &b_jetNCharged);
//   fChain->SetBranchAddress("jetMVAs", &treeLeaf.jetMVAs, &b_jetMVAs);
//   fChain->SetBranchAddress("jetWPLevels", &treeLeaf.jetWPLevels, &b_jetWPLevels);
//   fChain->SetBranchAddress("jetMVAsExt_simple", &treeLeaf.jetMVAsExt_simple, &b_jetMVAsExt_simple);
//   fChain->SetBranchAddress("jetWPLevelsExt_simple", &treeLeaf.jetWPLevelsExt_simple, &b_jetWPLevelsExt_simple);
//   fChain->SetBranchAddress("jetMVAsExt_full", &treeLeaf.jetMVAsExt_full, &b_jetMVAsExt_full);
//   fChain->SetBranchAddress("jetWPLevelsExt_full", &treeLeaf.jetWPLevelsExt_full, &b_jetWPLevelsExt_full);
//   fChain->SetBranchAddress("jetMVAsExt_cutBased", &treeLeaf.jetMVAsExt_cutBased, &b_jetMVAsExt_cutBased);
//   fChain->SetBranchAddress("jetWPLevelsExt_cutBased", &treeLeaf.jetWPLevelsExt_cutBased, &b_jetWPLevelsExt_cutBased);
//   fChain->SetBranchAddress("jetMVAsExt_philv1", &treeLeaf.jetMVAsExt_philv1, &b_jetMVAsExt_philv1);
//   fChain->SetBranchAddress("jetWPLevelsExt_philv1", &treeLeaf.jetWPLevelsExt_philv1, &b_jetWPLevelsExt_philv1);
//   fChain->SetBranchAddress("jetMt", &treeLeaf.jetMt, &b_jetMt);
   fChain->SetBranchAddress("jetJECUnc", &treeLeaf.jetJECUnc, &b_jetJECUnc);
//   fChain->SetBranchAddress("jetLeadTrackPt", &treeLeaf.jetLeadTrackPt, &b_jetLeadTrackPt);
//   fChain->SetBranchAddress("jetVtxPt", &treeLeaf.jetVtxPt, &b_jetVtxPt);
//   fChain->SetBranchAddress("jetVtxMass", &treeLeaf.jetVtxMass, &b_jetVtxMass);
//   fChain->SetBranchAddress("jetVtx3dL", &treeLeaf.jetVtx3dL, &b_jetVtx3dL);
//   fChain->SetBranchAddress("jetVtx3deL", &treeLeaf.jetVtx3deL, &b_jetVtx3deL);
//   fChain->SetBranchAddress("jetSoftLeptPt", &treeLeaf.jetSoftLeptPt, &b_jetSoftLeptPt);
//   fChain->SetBranchAddress("jetSoftLeptPtRel", &treeLeaf.jetSoftLeptPtRel, &b_jetSoftLeptPtRel);
//   fChain->SetBranchAddress("jetSoftLeptdR", &treeLeaf.jetSoftLeptdR, &b_jetSoftLeptdR);
//   fChain->SetBranchAddress("jetSoftLeptIdlooseMu", &treeLeaf.jetSoftLeptIdlooseMu, &b_jetSoftLeptIdlooseMu);
//   fChain->SetBranchAddress("jetSoftLeptIdEle95", &treeLeaf.jetSoftLeptIdEle95, &b_jetSoftLeptIdEle95);
//   fChain->SetBranchAddress("jetDPhiMETJet", &treeLeaf.jetDPhiMETJet, &b_jetDPhiMETJet);
//   fChain->SetBranchAddress("jetPuJetIdL", &treeLeaf.jetPuJetIdL, &b_jetPuJetIdL);
//   fChain->SetBranchAddress("jetPuJetIdM", &treeLeaf.jetPuJetIdM, &b_jetPuJetIdM);
//   fChain->SetBranchAddress("jetPuJetIdT", &treeLeaf.jetPuJetIdT, &b_jetPuJetIdT);
//   fChain->SetBranchAddress("jetPartonID", &treeLeaf.jetPartonID, &b_jetPartonID);
//   fChain->SetBranchAddress("jetGenJetIndex", &treeLeaf.jetGenJetIndex, &b_jetGenJetIndex);
//   fChain->SetBranchAddress("jetGenJetEn", &treeLeaf.jetGenJetEn, &b_jetGenJetEn);
   fChain->SetBranchAddress("jetGenJetPt", &treeLeaf.jetGenJetPt, &b_jetGenJetPt);
   fChain->SetBranchAddress("jetGenJetEta", &treeLeaf.jetGenJetEta, &b_jetGenJetEta);
   fChain->SetBranchAddress("jetGenJetPhi", &treeLeaf.jetGenJetPhi, &b_jetGenJetPhi);
//   fChain->SetBranchAddress("jetGenPartonID", &treeLeaf.jetGenPartonID, &b_jetGenPartonID);
//   fChain->SetBranchAddress("jetGenEn", &treeLeaf.jetGenEn, &b_jetGenEn);
//   fChain->SetBranchAddress("jetGenPt", &treeLeaf.jetGenPt, &b_jetGenPt);
//   fChain->SetBranchAddress("jetGenEta", &treeLeaf.jetGenEta, &b_jetGenEta);
//   fChain->SetBranchAddress("jetGenPhi", &treeLeaf.jetGenPhi, &b_jetGenPhi);
//   fChain->SetBranchAddress("jetGenPartonMomID", &treeLeaf.jetGenPartonMomID, &b_jetGenPartonMomID);
/*
   fChain->SetBranchAddress("nConv", &treeLeaf.nConv, &b_nConv);
   fChain->SetBranchAddress("convP4_x", &treeLeaf.convP4_x, &b_convP4_x);
   fChain->SetBranchAddress("convP4_y", &treeLeaf.convP4_y, &b_convP4_y);
   fChain->SetBranchAddress("convP4_z", &treeLeaf.convP4_z, &b_convP4_z);
   fChain->SetBranchAddress("convP4_E", &treeLeaf.convP4_E, &b_convP4_E);
   fChain->SetBranchAddress("convVtx_x", &treeLeaf.convVtx_x, &b_convVtx_x);
   fChain->SetBranchAddress("convVtx_y", &treeLeaf.convVtx_y, &b_convVtx_y);
   fChain->SetBranchAddress("convVtx_z", &treeLeaf.convVtx_z, &b_convVtx_z);
   fChain->SetBranchAddress("convVtxErr_x", &treeLeaf.convVtxErr_x, &b_convVtxErr_x);
   fChain->SetBranchAddress("convVtxErr_y", &treeLeaf.convVtxErr_y, &b_convVtxErr_y);
   fChain->SetBranchAddress("convVtxErr_z", &treeLeaf.convVtxErr_z, &b_convVtxErr_z);
   fChain->SetBranchAddress("convPairMomentum_x", &treeLeaf.convPairMomentum_x, &b_convPairMomentum_x);
   fChain->SetBranchAddress("convPairMomentum_y", &treeLeaf.convPairMomentum_y, &b_convPairMomentum_y);
   fChain->SetBranchAddress("convPairMomentum_z", &treeLeaf.convPairMomentum_z, &b_convPairMomentum_z);
   fChain->SetBranchAddress("convRefittedMomentum_x", &treeLeaf.convRefittedMomentum_x, &b_convRefittedMomentum_x);
   fChain->SetBranchAddress("convRefittedMomentum_y", &treeLeaf.convRefittedMomentum_y, &b_convRefittedMomentum_y);
   fChain->SetBranchAddress("convRefittedMomentum_z", &treeLeaf.convRefittedMomentum_z, &b_convRefittedMomentum_z);
   fChain->SetBranchAddress("convNTracks", &treeLeaf.convNTracks, &b_convNTracks);
   fChain->SetBranchAddress("convPairInvMass", &treeLeaf.convPairInvMass, &b_convPairInvMass);
   fChain->SetBranchAddress("convPairCotThetaSep", &treeLeaf.convPairCotThetaSep, &b_convPairCotThetaSep);
   fChain->SetBranchAddress("convEoverP", &treeLeaf.convEoverP, &b_convEoverP);
   fChain->SetBranchAddress("convDistOfMinApproach", &treeLeaf.convDistOfMinApproach, &b_convDistOfMinApproach);
   fChain->SetBranchAddress("convDPhiTrksAtVtx", &treeLeaf.convDPhiTrksAtVtx, &b_convDPhiTrksAtVtx);
   fChain->SetBranchAddress("convDPhiTrksAtEcal", &treeLeaf.convDPhiTrksAtEcal, &b_convDPhiTrksAtEcal);
   fChain->SetBranchAddress("convDEtaTrksAtEcal", &treeLeaf.convDEtaTrksAtEcal, &b_convDEtaTrksAtEcal);
   fChain->SetBranchAddress("convDxy", &treeLeaf.convDxy, &b_convDxy);
   fChain->SetBranchAddress("convDz", &treeLeaf.convDz, &b_convDz);
   fChain->SetBranchAddress("convLxy", &treeLeaf.convLxy, &b_convLxy);
   fChain->SetBranchAddress("convLz", &treeLeaf.convLz, &b_convLz);
   fChain->SetBranchAddress("convZofPrimVtxFromTrks", &treeLeaf.convZofPrimVtxFromTrks, &b_convZofPrimVtxFromTrks);
   fChain->SetBranchAddress("convNHitsBeforeVtx_0", &treeLeaf.convNHitsBeforeVtx_0, &b_convNHitsBeforeVtx_0);
   fChain->SetBranchAddress("convNHitsBeforeVtx_1", &treeLeaf.convNHitsBeforeVtx_1, &b_convNHitsBeforeVtx_1);
   fChain->SetBranchAddress("convNSharedHits", &treeLeaf.convNSharedHits, &b_convNSharedHits);
   fChain->SetBranchAddress("convValidVtx", &treeLeaf.convValidVtx, &b_convValidVtx);
   fChain->SetBranchAddress("convMVALikelihood", &treeLeaf.convMVALikelihood, &b_convMVALikelihood);
   fChain->SetBranchAddress("convChi2", &treeLeaf.convChi2, &b_convChi2);
   fChain->SetBranchAddress("convChi2Probability", &treeLeaf.convChi2Probability, &b_convChi2Probability);
   fChain->SetBranchAddress("convTk1Dz", &treeLeaf.convTk1Dz, &b_convTk1Dz);
   fChain->SetBranchAddress("convTk2Dz", &treeLeaf.convTk2Dz, &b_convTk2Dz);
   fChain->SetBranchAddress("convTk1DzErr", &treeLeaf.convTk1DzErr, &b_convTk1DzErr);
   fChain->SetBranchAddress("convTk2DzErr", &treeLeaf.convTk2DzErr, &b_convTk2DzErr);
   fChain->SetBranchAddress("convCh1Ch2", &treeLeaf.convCh1Ch2, &b_convCh1Ch2);
   fChain->SetBranchAddress("convTk1D0", &treeLeaf.convTk1D0, &b_convTk1D0);
   fChain->SetBranchAddress("convTk1Pout", &treeLeaf.convTk1Pout, &b_convTk1Pout);
   fChain->SetBranchAddress("convTk1Pin", &treeLeaf.convTk1Pin, &b_convTk1Pin);
   fChain->SetBranchAddress("convTk2D0", &treeLeaf.convTk2D0, &b_convTk2D0);
   fChain->SetBranchAddress("convTk2Pout", &treeLeaf.convTk2Pout, &b_convTk2Pout);
   fChain->SetBranchAddress("convTk2Pin", &treeLeaf.convTk2Pin, &b_convTk2Pin);
*/
}
