#define TInputOutputTree_cxx
#include "TInputOutputTree.h"
#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>

TInputOutputTree::TInputOutputTree()
{
   
}

TInputOutputTree::~TInputOutputTree()
{

}

void TInputOutputTree::InitOutputTree(TTree* outputTree)
{
   outputTree->Branch("run", &treeLeaf.run, "run/I");
   outputTree->Branch("event", &treeLeaf.event, "event/L");
//   outputTree->Branch("lumis", &treeLeaf.lumis, "lumis/I");
   outputTree->Branch("isData", &treeLeaf.isData, "isData/O");//Bool_t
   outputTree->Branch("nHLT", &treeLeaf.nHLT, "nHLT/I");
   outputTree->Branch("HLT", &treeLeaf.HLT, "HLT[nHLT]/I");
   outputTree->Branch("HLTIndex", &treeLeaf.HLTIndex, "HLTIndex[70]/I");
//   outputTree->Branch("bspotPos", &treeLeaf.bspotPos, "bspotPos[3]/F");
//   outputTree->Branch("nVtx", &treeLeaf.nVtx, "nVtx/I");
//   outputTree->Branch("vtx_x","vector<float>", &treeLeaf.vtx_x);
//   outputTree->Branch("vtx_y", "vector<float>",&treeLeaf.vtx_y);
//   outputTree->Branch("vtx_z", "vector<float>",&treeLeaf.vtx_z);
   outputTree->Branch("IsVtxGood", &treeLeaf.IsVtxGood, "IsVtxGood/I");
//   outputTree->Branch("nGoodVtx", &treeLeaf.nGoodVtx, "nGoodVtx/I");
//   outputTree->Branch("nVtxBS", &treeLeaf.nVtxBS, "nVtxBS/I");
//   outputTree->Branch("vtxbs_x", "vector<float>",&treeLeaf.vtxbs_x);
//   outputTree->Branch("vtxbs_y", "vector<float>",&treeLeaf.vtxbs_y);
//   outputTree->Branch("vtxbs_z", "vector<float>",&treeLeaf.vtxbs_z);
//   outputTree->Branch("pdf", treeLeaf.pdf, "pdf[7]/F");
//   outputTree->Branch("pthat", &treeLeaf.pthat, "pthat/F");
//   outputTree->Branch("processID", &treeLeaf.processID, "processID/F");
   outputTree->Branch("nMC", &treeLeaf.nMC, "nMC/I");
   outputTree->Branch("mcPID", &treeLeaf.mcPID);
//   outputTree->Branch("mcVtx_x", "vector<float>", &treeLeaf.mcVtx_x);
//   outputTree->Branch("mcVtx_y", "vector<float>", &treeLeaf.mcVtx_y);
//   outputTree->Branch("mcVtx_z", "vector<float>", &treeLeaf.mcVtx_z);
   outputTree->Branch("mcPt", "vector<float>", &treeLeaf.mcPt);
//   outputTree->Branch("mcMass", "vector<float>", &treeLeaf.mcMass);
   outputTree->Branch("mcEta", "vector<float>", &treeLeaf.mcEta);
   outputTree->Branch("mcPhi", "vector<float>", &treeLeaf.mcPhi);
   outputTree->Branch("mcE",  "vector<float>",&treeLeaf.mcE);
   outputTree->Branch("mcEt",  "vector<float>",&treeLeaf.mcEt);
//   outputTree->Branch("mcGMomPID", "vector<int>",&treeLeaf.mcGMomPID);
//   outputTree->Branch("mcMomPID","vector<int>", &treeLeaf.mcMomPID);
//   outputTree->Branch("mcMomPt", "vector<float>", &treeLeaf.mcMomPt);
//   outputTree->Branch("mcMomMass", "vector<float>", &treeLeaf.mcMomMass);
//   outputTree->Branch("mcMomEta",  "vector<float>",&treeLeaf.mcMomEta);
//   outputTree->Branch("mcMomPhi", "vector<float>", &treeLeaf.mcMomPhi);
   outputTree->Branch("mcIndex","vector<int>", &treeLeaf.mcIndex);
   outputTree->Branch("mcDecayType", "vector<int>",&treeLeaf.mcDecayType);
//   outputTree->Branch("mcParentage", "vector<int>",&treeLeaf.mcParentage);
//   outputTree->Branch("mcStatus", "vector<int>",&treeLeaf.mcStatus);
//   outputTree->Branch("genMET", &treeLeaf.genMET, "genMET/F");
//   outputTree->Branch("genMETPhi", &treeLeaf.genMETPhi, "genMETPhi/F");
   outputTree->Branch("nPUInfo", &treeLeaf.nPUInfo, "nPUInfo/I");
//   outputTree->Branch("nPU", "vector<int>",&treeLeaf.nPU);
//   outputTree->Branch("puBX", "vector<int>",&treeLeaf.puBX);
   outputTree->Branch("puTrue", "vector<float>",&treeLeaf.puTrue);
   outputTree->Branch("pfMET", &treeLeaf.pfMET, "pfMET/F");
   outputTree->Branch("pfMETPhi", &treeLeaf.pfMETPhi, "pfMETPhi/F");
//   outputTree->Branch("pfMETsumEt", &treeLeaf.pfMETsumEt, "pfMETsumEt/F");
//   outputTree->Branch("pfMETmEtSig", &treeLeaf.pfMETmEtSig, "pfMETmEtSig/F");
//   outputTree->Branch("pfMETSig", &treeLeaf.pfMETSig, "pfMETSig/F");
//   outputTree->Branch("pfType01MET", &treeLeaf.pfType01MET, "pfType01MET/F");
//   outputTree->Branch("pfType01METPhi", &treeLeaf.pfType01METPhi, "pfType01METPhi/F");
//   outputTree->Branch("pfType01METsumEt", &treeLeaf.pfType01METsumEt, "pfType01METsumEt/F");
//   outputTree->Branch("pfType01METmEtSig", &treeLeaf.pfType01METmEtSig, "pfType01METmEtSig/F");
//   outputTree->Branch("pfType01METSig", &treeLeaf.pfType01METSig, "pfType01METSig/F");
//   outputTree->Branch("recoPfMET", &treeLeaf.recoPfMET, "recoPfMET/F");
//   outputTree->Branch("recoPfMETPhi", &treeLeaf.recoPfMETPhi, "recoPfMETPhi/F");
//   outputTree->Branch("recoPfMETsumEt", &treeLeaf.recoPfMETsumEt, "recoPfMETsumEt/F");
//   outputTree->Branch("recoPfMETmEtSig", &treeLeaf.recoPfMETmEtSig, "recoPfMETmEtSig/F");
//   outputTree->Branch("recoPfMETSig", &treeLeaf.recoPfMETSig, "recoPfMETSig/F");
//   outputTree->Branch("trkMETxPV", &treeLeaf.trkMETxPV, "trkMETxPV/F");
//   outputTree->Branch("trkMETyPV", &treeLeaf.trkMETyPV, "trkMETyPV/F");
//   outputTree->Branch("trkMETPhiPV", &treeLeaf.trkMETPhiPV, "trkMETPhiPV/F");
//   outputTree->Branch("trkMETPV", &treeLeaf.trkMETPV, "trkMETPV/F");
//   outputTree->Branch("trkMETx",  "vector<float>", &treeLeaf.trkMETx);
//   outputTree->Branch("trkMETy",  "vector<float>", &treeLeaf.trkMETy);
//   outputTree->Branch("trkMETPhi",  "vector<float>", &treeLeaf.trkMETPhi);
//   outputTree->Branch("trkMET",  "vector<float>", &treeLeaf.trkMET);
   outputTree->Branch("metFilters", treeLeaf.metFilters, "metFilters[10]/I");
   outputTree->Branch("nEle", &treeLeaf.nEle, "nEle/I");
//   outputTree->Branch("eleTrg", "vector<unsigned long>", &treeLeaf.eleTrg);
     //unsigned long 
//   outputTree->Branch("eleClass", "vector<int>", &treeLeaf.eleClass);
//   outputTree->Branch("eleIsEcalDriven", "vector<int>", &treeLeaf.eleIsEcalDriven);
//   outputTree->Branch("eleCharge", "vector<int>", &treeLeaf.eleCharge);
//   outputTree->Branch("eleChargeConsistent", "vector<int>", &treeLeaf.eleChargeConsistent);
//   outputTree->Branch("eleEn", "vector<float>", &treeLeaf.eleEn);
//   outputTree->Branch("eleEcalEn", "vector<float>",&treeLeaf.eleEcalEn);
//   outputTree->Branch("eleSCRawEn", "vector<float>",&treeLeaf.eleSCRawEn);
//   outputTree->Branch("eleSCEn", "vector<float>",&treeLeaf.eleSCEn);
//   outputTree->Branch("eleESEn", "vector<float>",&treeLeaf.eleESEn);
   outputTree->Branch("elePt", "vector<float>",&treeLeaf.elePt);
//   outputTree->Branch("eleEta", "vector<float>",&treeLeaf.eleEta);
//   outputTree->Branch("elePhi", "vector<float>",&treeLeaf.elePhi);
//   outputTree->Branch("eleR9", "vector<float>",&treeLeaf.eleR9);
//   outputTree->Branch("eleEtaVtx", "vector<vector<float>>",&treeLeaf.eleEtaVtx);
//   outputTree->Branch("elePhiVtx", "vector<vector<float>>",&treeLeaf.elePhiVtx);
//   outputTree->Branch("eleEtVtx", "vector<vector<float>>",&treeLeaf.eleEtVtx);
//   outputTree->Branch("eleSCEta", "vector<float>",&treeLeaf.eleSCEta);
//   outputTree->Branch("eleSCPhi", "vector<float>",&treeLeaf.eleSCPhi);
//   outputTree->Branch("eleSCEtaWidth", "vector<float>",&treeLeaf.eleSCEtaWidth);
//   outputTree->Branch("eleSCPhiWidth", "vector<float>",&treeLeaf.eleSCPhiWidth);
//   outputTree->Branch("eleVtx_x", "vector<float>",&treeLeaf.eleVtx_x);
//   outputTree->Branch("eleVtx_y", "vector<float>",&treeLeaf.eleVtx_y);
//   outputTree->Branch("eleVtx_z", "vector<float>",&treeLeaf.eleVtx_z);
//   outputTree->Branch("eleD0", "vector<float>",&treeLeaf.eleD0);
//   outputTree->Branch("eleDz", "vector<float>",&treeLeaf.eleDz);
//   outputTree->Branch("eleD0GV", "vector<float>",&treeLeaf.eleD0GV);
//   outputTree->Branch("eleDzGV", "vector<float>",&treeLeaf.eleDzGV);
//   outputTree->Branch("eleD0Vtx", "vector<vector<float>>",&treeLeaf.eleD0Vtx);
//   outputTree->Branch("eleDzVtx", "vector<vector<float>>",&treeLeaf.eleDzVtx);
//   outputTree->Branch("eleHoverE", "vector<float>",&treeLeaf.eleHoverE);
//   outputTree->Branch("eleHoverE12", "vector<float>",&treeLeaf.eleHoverE12);
//   outputTree->Branch("eleEoverP", "vector<float>",&treeLeaf.eleEoverP);
//   outputTree->Branch("elePin", "vector<float>",&treeLeaf.elePin);
//   outputTree->Branch("elePout", "vector<float>",&treeLeaf.elePout);
//   outputTree->Branch("eleTrkMomErr", "vector<float>",&treeLeaf.eleTrkMomErr);
//   outputTree->Branch("eleBrem", "vector<float>",&treeLeaf.eleBrem);
//   outputTree->Branch("eledEtaAtVtx", "vector<float>",&treeLeaf.eledEtaAtVtx);
//   outputTree->Branch("eledPhiAtVtx", "vector<float>",&treeLeaf.eledPhiAtVtx);
//   outputTree->Branch("eleSigmaIEtaIEta", "vector<float>",&treeLeaf.eleSigmaIEtaIEta);
//   outputTree->Branch("eleSigmaIEtaIPhi", "vector<float>",&treeLeaf.eleSigmaIEtaIPhi);
//   outputTree->Branch("eleSigmaIPhiIPhi", "vector<float>",&treeLeaf.eleSigmaIPhiIPhi);
//   outputTree->Branch("eleEmax", "vector<float>",&treeLeaf.eleEmax);
//   outputTree->Branch("eleE2ndMax", "vector<float>",&treeLeaf.eleE2ndMax);
//   outputTree->Branch("eleETop", "vector<float>",&treeLeaf.eleETop);
//   outputTree->Branch("eleEBottom", "vector<float>",&treeLeaf.eleEBottom);
//   outputTree->Branch("eleELeft", "vector<float>",&treeLeaf.eleELeft);
//   outputTree->Branch("eleERight", "vector<float>",&treeLeaf.eleERight);
//   outputTree->Branch("eleE1x5", "vector<float>",&treeLeaf.eleE1x5);
//   outputTree->Branch("eleE3x3","vector<float>", &treeLeaf.eleE3x3);
//   outputTree->Branch("eleE5x5","vector<float>", &treeLeaf.eleE5x5);
//   outputTree->Branch("eleE2x5Max","vector<float>", &treeLeaf.eleE2x5Max);
//   outputTree->Branch("eleE2x5Top","vector<float>", &treeLeaf.eleE2x5Top);
//   outputTree->Branch("eleE2x5Bottom", "vector<float>",&treeLeaf.eleE2x5Bottom);
//   outputTree->Branch("eleE2x5Left", "vector<float>",&treeLeaf.eleE2x5Left);
//   outputTree->Branch("eleE2x5Right","vector<float>", &treeLeaf.eleE2x5Right);
//   outputTree->Branch("eleSeedEta","vector<float>", &treeLeaf.eleSeedEta);
//   outputTree->Branch("eleSeedE","vector<float>", &treeLeaf.eleSeedE);
//   outputTree->Branch("eleSeedPhi","vector<float>", &treeLeaf.eleSeedPhi);
//   outputTree->Branch("eleCrysEta","vector<float>", &treeLeaf.eleCrysEta);
//   outputTree->Branch("eleCrysPhi","vector<float>", &treeLeaf.eleCrysPhi);
//   outputTree->Branch("eleCrysIEta","vector<int>", &treeLeaf.eleCrysIEta);
//   outputTree->Branch("eleCrysIPhi","vector<int>", &treeLeaf.eleCrysIPhi);
//   outputTree->Branch("eleRegrE", "vector<float>",&treeLeaf.eleRegrE);
//   outputTree->Branch("eleRegrEerr", "vector<float>",&treeLeaf.eleRegrEerr);
//   outputTree->Branch("elePhoRegrE", "vector<float>",&treeLeaf.elePhoRegrE);
//   outputTree->Branch("elePhoRegrEerr", "vector<float>",&treeLeaf.elePhoRegrEerr);
//   outputTree->Branch("eleSeedTime", "vector<float>",&treeLeaf.eleSeedTime);
//   outputTree->Branch("eleRecoFlag", "vector<int>",&treeLeaf.eleRecoFlag);
//   outputTree->Branch("elePos", "vector<int>",&treeLeaf.elePos);
   outputTree->Branch("eleGenIndex", "vector<int>",&treeLeaf.eleGenIndex);
//   outputTree->Branch("eleGenGMomPID", "vector<int>",&treeLeaf.eleGenGMomPID);
//   outputTree->Branch("eleGenMomPID", "vector<int>",&treeLeaf.eleGenMomPID);
//   outputTree->Branch("eleGenMomPt", "vector<float>",&treeLeaf.eleGenMomPt);
//   outputTree->Branch("eleIsoTrkDR03", "vector<float>",&treeLeaf.eleIsoTrkDR03);
//   outputTree->Branch("eleIsoEcalDR03", "vector<float>",&treeLeaf.eleIsoEcalDR03);
//   outputTree->Branch("eleIsoHcalDR03", "vector<float>",&treeLeaf.eleIsoHcalDR03);
//   outputTree->Branch("eleIsoHcalDR0312", "vector<float>",&treeLeaf.eleIsoHcalDR0312);
//   outputTree->Branch("eleIsoTrkDR04", "vector<float>",&treeLeaf.eleIsoTrkDR04);
//   outputTree->Branch("eleIsoEcalDR04", "vector<float>",&treeLeaf.eleIsoEcalDR04);
//   outputTree->Branch("eleIsoHcalDR04", "vector<float>",&treeLeaf.eleIsoHcalDR04);
//   outputTree->Branch("eleIsoHcalDR0412", "vector<float>",&treeLeaf.eleIsoHcalDR0412);
//   outputTree->Branch("eleModIsoTrk", "vector<float>",&treeLeaf.eleModIsoTrk);
//   outputTree->Branch("eleModIsoEcal", "vector<float>",&treeLeaf.eleModIsoEcal);
//   outputTree->Branch("eleModIsoHcal", "vector<float>",&treeLeaf.eleModIsoHcal);
//   outputTree->Branch("eleMissHits", "vector<int>",&treeLeaf.eleMissHits);
//   outputTree->Branch("eleConvDist", "vector<float>",&treeLeaf.eleConvDist);
//   outputTree->Branch("eleConvDcot", "vector<float>",&treeLeaf.eleConvDcot);
//   outputTree->Branch("eleConvVtxFit", "vector<int>", &treeLeaf.eleConvVtxFit);
//   outputTree->Branch("eleIP3D", "vector<float>", &treeLeaf.eleIP3D);
//   outputTree->Branch("eleIP3DErr", "vector<float>", &treeLeaf.eleIP3DErr);
//   outputTree->Branch("eleIDMVANonTrig", "vector<float>", &treeLeaf.eleIDMVANonTrig);
//   outputTree->Branch("eleIDMVATrig", "vector<float>", &treeLeaf.eleIDMVATrig);
//   outputTree->Branch("elePFChIso03", "vector<float>", &treeLeaf.elePFChIso03);
//   outputTree->Branch("elePFPhoIso03",  "vector<float>",&treeLeaf.elePFPhoIso03);
//   outputTree->Branch("elePFNeuIso03",  "vector<float>",&treeLeaf.elePFNeuIso03);
//   outputTree->Branch("elePFChIso04",  "vector<float>",&treeLeaf.elePFChIso04);
//   outputTree->Branch("elePFPhoIso04",  "vector<float>",&treeLeaf.elePFPhoIso04);
//   outputTree->Branch("elePFNeuIso04",  "vector<float>",&treeLeaf.elePFNeuIso04);
//   outputTree->Branch("eleESEffSigmaRR_x",  "vector<float>",&treeLeaf.eleESEffSigmaRR_x);
//   outputTree->Branch("eleESEffSigmaRR_y",  "vector<float>",&treeLeaf.eleESEffSigmaRR_y);
//   outputTree->Branch("eleESEffSigmaRR_z",  "vector<float>",&treeLeaf.eleESEffSigmaRR_z);
   outputTree->Branch("nPho", &treeLeaf.nPho, "nPho/I");
//   outputTree->Branch("phoTrg", "vector<unsigned long>",&treeLeaf.phoTrg);
//   outputTree->Branch("phoTrgFilter", "vector<unsigned long>",&treeLeaf.phoTrgFilter);
//   outputTree->Branch("phoIsPhoton", "vector<bool>", &treeLeaf.phoIsPhoton);
//   outputTree->Branch("phoSCPos_x", "vector<float>",&treeLeaf.phoSCPos_x);
//   outputTree->Branch("phoSCPos_y", "vector<float>",&treeLeaf.phoSCPos_y);
//   outputTree->Branch("phoSCPos_z", "vector<float>",&treeLeaf.phoSCPos_z);
//   outputTree->Branch("phoCaloPos_x", "vector<float>",&treeLeaf.phoCaloPos_x);
//   outputTree->Branch("phoCaloPos_y", "vector<float>",&treeLeaf.phoCaloPos_y);
//   outputTree->Branch("phoCaloPos_z", "vector<float>",&treeLeaf.phoCaloPos_z);
 //  outputTree->Branch("phoE", "vector<float>",&treeLeaf.phoE);
   outputTree->Branch("phoEt", "vector<float>",&treeLeaf.phoEt);
   outputTree->Branch("phoEta", "vector<float>",&treeLeaf.phoEta);
//   outputTree->Branch("phoVtx_x", "vector<float>",&treeLeaf.phoVtx_x);
//   outputTree->Branch("phoVtx_y", "vector<float>",&treeLeaf.phoVtx_y);
//   outputTree->Branch("phoVtx_z", "vector<float>",&treeLeaf.phoVtx_z);
   outputTree->Branch("phoPhi", "vector<float>",&treeLeaf.phoPhi);
//   outputTree->Branch("phoEtVtx", "vector<vector<float>>",&treeLeaf.phoEtVtx);
//   outputTree->Branch("phoEtaVtx", "vector<vector<float>>",&treeLeaf.phoEtaVtx);
//   outputTree->Branch("phoPhiVtx", "vector<vector<float>>",&treeLeaf.phoPhiVtx);
   outputTree->Branch("phoR9", "vector<float>",&treeLeaf.phoR9);
//   outputTree->Branch("phoNClus", "vector<int>",&treeLeaf.phoNClus);
//   outputTree->Branch("phoTrkIsoHollowDR03","vector<float>", &treeLeaf.phoTrkIsoHollowDR03);
//   outputTree->Branch("phoEcalIsoDR03", "vector<float>",&treeLeaf.phoEcalIsoDR03);
//   outputTree->Branch("phoHcalIsoDR03", "vector<float>",&treeLeaf.phoHcalIsoDR03);
//   outputTree->Branch("phoHcalIsoDR0312", "vector<float>",&treeLeaf.phoHcalIsoDR0312);
//   outputTree->Branch("phoTrkIsoHollowDR04", "vector<float>",&treeLeaf.phoTrkIsoHollowDR04);
//   outputTree->Branch("phoCiCdRtoTrk", "vector<float>",&treeLeaf.phoCiCdRtoTrk);
//   outputTree->Branch("phoEcalIsoDR04", "vector<float>",&treeLeaf.phoEcalIsoDR04);
//   outputTree->Branch("phoHcalIsoDR04", "vector<float>",&treeLeaf.phoHcalIsoDR04);
//   outputTree->Branch("phoHcalIsoDR0412", "vector<float>",&treeLeaf.phoHcalIsoDR0412);
   outputTree->Branch("phoHoverE", "vector<float>",&treeLeaf.phoHoverE);
   outputTree->Branch("phoHoverE12", "vector<float>",&treeLeaf.phoHoverE12);
   outputTree->Branch("phoEleVeto",  "vector<int>",&treeLeaf.phoEleVeto);
   outputTree->Branch("phoSigmaIEtaIEta", "vector<float>",&treeLeaf.phoSigmaIEtaIEta);
//   outputTree->Branch("phoSigmaIEtaIPhi", "vector<float>",&treeLeaf.phoSigmaIEtaIPhi);
//   outputTree->Branch("phoSigmaIPhiIPhi", "vector<float>",&treeLeaf.phoSigmaIPhiIPhi);
//   outputTree->Branch("phoCiCPF4phopfIso03", "vector<float>",&treeLeaf.phoCiCPF4phopfIso03);
//   outputTree->Branch("phoCiCPF4phopfIso04", "vector<float>",&treeLeaf.phoCiCPF4phopfIso04);
//   outputTree->Branch("phoCiCPF4chgpfIso02", "vector<vector<float>>", &treeLeaf.phoCiCPF4chgpfIso02);
//   outputTree->Branch("phoCiCPF4chgpfIso03", "vector<vector<float>>", &treeLeaf.phoCiCPF4chgpfIso03);
//   outputTree->Branch("phoCiCPF4chgpfIso04", "vector<vector<float>>", &treeLeaf.phoCiCPF4chgpfIso04);
//   outputTree->Branch("phoEmax", "vector<float>", &treeLeaf.phoEmax);
//   outputTree->Branch("phoETop", "vector<float>", &treeLeaf.phoETop);
//   outputTree->Branch("phoEBottom", "vector<float>", &treeLeaf.phoEBottom);
//   outputTree->Branch("phoELeft", "vector<float>", &treeLeaf.phoELeft);
//   outputTree->Branch("phoERight", "vector<float>", &treeLeaf.phoERight);
//   outputTree->Branch("phoE2ndMax", "vector<float>", &treeLeaf.phoE2ndMax);
//   outputTree->Branch("phoE3x3", "vector<float>", &treeLeaf.phoE3x3);
//   outputTree->Branch("phoE3x1", "vector<float>", &treeLeaf.phoE3x1);
//   outputTree->Branch("phoE1x3", "vector<float>", &treeLeaf.phoE1x3);
//   outputTree->Branch("phoE5x5", "vector<float>", &treeLeaf.phoE5x5);
//   outputTree->Branch("phoE1x5", "vector<float>", &treeLeaf.phoE1x5);
//   outputTree->Branch("phoE2x2", "vector<float>", &treeLeaf.phoE2x2);
//   outputTree->Branch("phoE2x5Max", "vector<float>", &treeLeaf.phoE2x5Max);
//   outputTree->Branch("phoE2x5Top", "vector<float>", &treeLeaf.phoE2x5Top);
//   outputTree->Branch("phoE2x5Bottom", "vector<float>", &treeLeaf.phoE2x5Bottom);
//   outputTree->Branch("phoE2x5Left", "vector<float>", &treeLeaf.phoE2x5Left);
//   outputTree->Branch("phoE2x5Right", "vector<float>", &treeLeaf.phoE2x5Right);
//   outputTree->Branch("phoSeedE", "vector<float>", &treeLeaf.phoSeedE);
//   outputTree->Branch("phoSeedEta", "vector<float>", &treeLeaf.phoSeedEta);
//   outputTree->Branch("phoSeedPhi", "vector<float>", &treeLeaf.phoSeedPhi);
//   outputTree->Branch("phoCrysEta", "vector<float>", &treeLeaf.phoCrysEta);
//   outputTree->Branch("phoCrysPhi", "vector<float>", &treeLeaf.phoCrysPhi);
//   outputTree->Branch("phoCrysIEta", "vector<int>", &treeLeaf.phoCrysIEta);
//   outputTree->Branch("phoCrysIPhi", "vector<int>", &treeLeaf.phoCrysIPhi);
   outputTree->Branch("phoPFChIso", "vector<float>",&treeLeaf.phoPFChIso);
   outputTree->Branch("phoPFPhoIso", "vector<float>",&treeLeaf.phoPFPhoIso);
   outputTree->Branch("phoPFNeuIso", "vector<float>",&treeLeaf.phoPFNeuIso);
   outputTree->Branch("phoSCRChIso", "vector<float>",&treeLeaf.phoSCRChIso);
   outputTree->Branch("phoSCRPhoIso", "vector<float>",&treeLeaf.phoSCRPhoIso);
   outputTree->Branch("phoSCRNeuIso", "vector<float>",&treeLeaf.phoSCRNeuIso);
   outputTree->Branch("phoSCRChIso04", "vector<float>",&treeLeaf.phoSCRChIso04);
   outputTree->Branch("phoSCRPhoIso04", "vector<float>",&treeLeaf.phoSCRPhoIso04);
   outputTree->Branch("phoSCRNeuIso04", "vector<float>",&treeLeaf.phoSCRNeuIso04);
//   outputTree->Branch("phoRandConeChIso", "vector<float>",&treeLeaf.phoRandConeChIso);
//  outputTree->Branch("phoRandConePhoIso", "vector<float>",&treeLeaf.phoRandConePhoIso);
//   outputTree->Branch("phoRandConeNeuIso", "vector<float>",&treeLeaf.phoRandConeNeuIso);
//   outputTree->Branch("phoRandConeChIso04", "vector<float>",&treeLeaf.phoRandConeChIso04);
//   outputTree->Branch("phoRandConePhoIso04", "vector<float>",&treeLeaf.phoRandConePhoIso04);
//   outputTree->Branch("phoRandConeNeuIso04", "vector<float>",&treeLeaf.phoRandConeNeuIso04);
//   outputTree->Branch("phoRegrE", "vector<float>",&treeLeaf.phoRegrE);
//   outputTree->Branch("phoRegrEerr", "vector<float>",&treeLeaf.phoRegrEerr);
//   outputTree->Branch("phoSeedTime", "vector<float>",&treeLeaf.phoSeedTime);
//   outputTree->Branch("phoSeedDetId1", "vector<int>",&treeLeaf.phoSeedDetId1);
//   outputTree->Branch("phoSeedDetId2", "vector<int>",&treeLeaf.phoSeedDetId2);
//   outputTree->Branch("phoLICTD", "vector<float>",&treeLeaf.phoLICTD);
//   outputTree->Branch("phoRecoFlag", "vector<int>",&treeLeaf.phoRecoFlag);
//   outputTree->Branch("phoPos", "vector<int>",&treeLeaf.phoPos);
   outputTree->Branch("phoGenIndex","vector<int>", &treeLeaf.phoGenIndex);
//   outputTree->Branch("phoGenGMomPID", "vector<int>",&treeLeaf.phoGenGMomPID);
   outputTree->Branch("phoGenMomPID", "vector<int>",&treeLeaf.phoGenMomPID);
//   outputTree->Branch("phoGenMomPt", "vector<float>",&treeLeaf.phoGenMomPt);
//   outputTree->Branch("phoSCE","vector<float>" ,&treeLeaf.phoSCE);
//   outputTree->Branch("phoSCRawE", "vector<float>",&treeLeaf.phoSCRawE);
//   outputTree->Branch("phoESEn", "vector<float>",&treeLeaf.phoESEn);
   outputTree->Branch("phoSCEt", "vector<float>",&treeLeaf.phoSCEt);
   outputTree->Branch("phoSCEta", "vector<float>",&treeLeaf.phoSCEta);
   outputTree->Branch("phoSCPhi", "vector<float>",&treeLeaf.phoSCPhi);
//   outputTree->Branch("phoSCEtaWidth", "vector<float>",&treeLeaf.phoSCEtaWidth);
//   outputTree->Branch("phoSCPhiWidth","vector<float>" ,&treeLeaf.phoSCPhiWidth);
//   outputTree->Branch("phoSCBrem", "vector<float>",&treeLeaf.phoSCBrem);
//   outputTree->Branch("phoOverlap", "vector<int>",&treeLeaf.phoOverlap);
//   outputTree->Branch("phohasPixelSeed", "vector<int>",&treeLeaf.phohasPixelSeed);
//   outputTree->Branch("pho_hasConvPf", "vector<int>",&treeLeaf.pho_hasConvPf);
//   outputTree->Branch("pho_hasSLConvPf", "vector<int>",&treeLeaf.pho_hasSLConvPf);
//   outputTree->Branch("pho_pfconvVtxZ", "vector<float>",&treeLeaf.pho_pfconvVtxZ);
//   outputTree->Branch("pho_pfconvVtxZErr", "vector<float>",&treeLeaf.pho_pfconvVtxZErr);
//   outputTree->Branch("pho_nSLConv", "vector<int>",&treeLeaf.pho_nSLConv);
//   outputTree->Branch("pho_pfSLConvPos_x", "vector<vector<float>>",&treeLeaf.pho_pfSLConvPos_x);
//   outputTree->Branch("pho_pfSLConvPos_y", "vector<vector<float>>",&treeLeaf.pho_pfSLConvPos_y);
//   outputTree->Branch("pho_pfSLConvPos_z", "vector<vector<float>>",&treeLeaf.pho_pfSLConvPos_z);
//   outputTree->Branch("pho_pfSLConvVtxZ", "vector<vector<float>>",&treeLeaf.pho_pfSLConvVtxZ);
 //  outputTree->Branch("phoIsConv", "vector<int>",&treeLeaf.phoIsConv);
//   outputTree->Branch("phoNConv", "vector<int>",&treeLeaf.phoNConv);
//   outputTree->Branch("phoConvInvMass",  "vector<float>",&treeLeaf.phoConvInvMass);
//   outputTree->Branch("phoConvCotTheta",  "vector<float>",&treeLeaf.phoConvCotTheta);
//   outputTree->Branch("phoConvEoverP",  "vector<float>",&treeLeaf.phoConvEoverP);
//   outputTree->Branch("phoConvZofPVfromTrks",  "vector<float>",&treeLeaf.phoConvZofPVfromTrks);
//   outputTree->Branch("phoConvMinDist",  "vector<float>",&treeLeaf.phoConvMinDist);
//   outputTree->Branch("phoConvdPhiAtVtx",  "vector<float>",&treeLeaf.phoConvdPhiAtVtx);
//   outputTree->Branch("phoConvdPhiAtCalo",  "vector<float>",&treeLeaf.phoConvdPhiAtCalo);
//   outputTree->Branch("phoConvdEtaAtCalo",  "vector<float>",&treeLeaf.phoConvdEtaAtCalo);
//   outputTree->Branch("phoConvTrkd0_x",  "vector<float>",&treeLeaf.phoConvTrkd0_x);
//   outputTree->Branch("phoConvTrkd0_y",  "vector<float>",&treeLeaf.phoConvTrkd0_y);
//   outputTree->Branch("phoConvTrkPin_x", "vector<float>", &treeLeaf.phoConvTrkPin_x);
//   outputTree->Branch("phoConvTrkPin_y",  "vector<float>",&treeLeaf.phoConvTrkPin_y);
//   outputTree->Branch("phoConvTrkPout_x",  "vector<float>",&treeLeaf.phoConvTrkPout_x);
//   outputTree->Branch("phoConvTrkPout_y",  "vector<float>",&treeLeaf.phoConvTrkPout_y);
//   outputTree->Branch("phoConvTrkdz_x",  "vector<float>",&treeLeaf.phoConvTrkdz_x);
//   outputTree->Branch("phoConvTrkdz_y",  "vector<float>",&treeLeaf.phoConvTrkdz_y);
//   outputTree->Branch("phoConvTrkdzErr_x",  "vector<float>",&treeLeaf.phoConvTrkdzErr_x);
//   outputTree->Branch("phoConvTrkdzErr_y",  "vector<float>",&treeLeaf.phoConvTrkdzErr_y);
//   outputTree->Branch("phoConvChi2",  "vector<float>",&treeLeaf.phoConvChi2);
//   outputTree->Branch("phoConvChi2Prob",  "vector<float>",&treeLeaf.phoConvChi2Prob);
//   outputTree->Branch("phoConvNTrks",  "vector<int>",&treeLeaf.phoConvNTrks);
//   outputTree->Branch("phoConvCharge1", "vector<float>",&treeLeaf.phoConvCharge1);
//   outputTree->Branch("phoConvCharge2", "vector<float>",&treeLeaf.phoConvCharge2);
//   outputTree->Branch("phoConvValidVtx", "vector<int>",&treeLeaf.phoConvValidVtx);
 //  outputTree->Branch("phoConvLikeLihood",   "vector<float>",&treeLeaf.phoConvLikeLihood);
//   outputTree->Branch("phoConvP4_0",   "vector<float>",&treeLeaf.phoConvP4_0);
//   outputTree->Branch("phoConvP4_1",  "vector<float>", &treeLeaf.phoConvP4_1);
//   outputTree->Branch("phoConvP4_2",   "vector<float>",&treeLeaf.phoConvP4_2);
//   outputTree->Branch("phoConvP4_3",   "vector<float>",&treeLeaf.phoConvP4_3);
//   outputTree->Branch("phoConvVtx_x",  "vector<float>", &treeLeaf.phoConvVtx_x);
//   outputTree->Branch("phoConvVtx_y",  "vector<float>", &treeLeaf.phoConvVtx_y);
//   outputTree->Branch("phoConvVtx_z",  "vector<float>", &treeLeaf.phoConvVtx_z);
////   outputTree->Branch("phoConvVtxErr_x",  "vector<float>", &treeLeaf.phoConvVtxErr_x);
//  outputTree->Branch("phoConvVtxErr_y",  "vector<float>", &treeLeaf.phoConvVtxErr_y);
 //  outputTree->Branch("phoConvVtxErr_z",  "vector<float>", &treeLeaf.phoConvVtxErr_z);
//   outputTree->Branch("phoConvPairMomentum_x",  "vector<float>", &treeLeaf.phoConvPairMomentum_x);
//   outputTree->Branch("phoConvPairMomentum_y",  "vector<float>", &treeLeaf.phoConvPairMomentum_y);
//   outputTree->Branch("phoConvPairMomentum_z",  "vector<float>", &treeLeaf.phoConvPairMomentum_z);
//   outputTree->Branch("phoConvRefittedMomentum_x",  "vector<float>", &treeLeaf.phoConvRefittedMomentum_x);
 //  outputTree->Branch("phoConvRefittedMomentum_y",  "vector<float>", &treeLeaf.phoConvRefittedMomentum_y);
//   outputTree->Branch("phoConvRefittedMomentum_z",  "vector<float>", &treeLeaf.phoConvRefittedMomentum_z);
 //  outputTree->Branch("SingleLegConv", "vector<int>", &treeLeaf.SingleLegConv);
//   outputTree->Branch("phoPFConvVtx_x", "vector<vector<float>>",&treeLeaf.phoPFConvVtx_x);
//   outputTree->Branch("phoPFConvVtx_y", "vector<vector<float>>",&treeLeaf.phoPFConvVtx_y);
 //  outputTree->Branch("phoPFConvVtx_z", "vector<vector<float>>",&treeLeaf.phoPFConvVtx_z);
 //  outputTree->Branch("phoPFConvMom_x", "vector<vector<float>>",&treeLeaf.phoPFConvMom_x);
 //  outputTree->Branch("phoPFConvMom_y", "vector<vector<float>>",&treeLeaf.phoPFConvMom_y);
 //  outputTree->Branch("phoPFConvMom_z", "vector<vector<float>>",&treeLeaf.phoPFConvMom_z);
//   outputTree->Branch("phoESEffSigmaRR_x","vector<float>", &treeLeaf.phoESEffSigmaRR_x);
 //  outputTree->Branch("phoESEffSigmaRR_y","vector<float>", &treeLeaf.phoESEffSigmaRR_y);
//   outputTree->Branch("phoESEffSigmaRR_z","vector<float>", &treeLeaf.phoESEffSigmaRR_z);
   outputTree->Branch("nMu", &treeLeaf.nMu, "nMu/I");
   outputTree->Branch("muTrg", "vector<unsigned long>",&treeLeaf.muTrg);
   outputTree->Branch("muEta", "vector<float>",&treeLeaf.muEta);
   outputTree->Branch("muPhi", "vector<float>",&treeLeaf.muPhi);
//   outputTree->Branch("muCharge", "vector<int>", &treeLeaf.muCharge);
   outputTree->Branch("muPt", "vector<float>",&treeLeaf.muPt);
//   outputTree->Branch("muPz", "vector<float>",&treeLeaf.muPz);
//   outputTree->Branch("muVtx_x","vector<float>", &treeLeaf.muVtx_x);
//   outputTree->Branch("muVtx_y","vector<float>", &treeLeaf.muVtx_y);
//   outputTree->Branch("muVtx_z","vector<float>", &treeLeaf.muVtx_z);
//   outputTree->Branch("muVtxGlb_x", "vector<float>",&treeLeaf.muVtxGlb_x);
//   outputTree->Branch("muVtxGlb_y", "vector<float>",&treeLeaf.muVtxGlb_y);
//   outputTree->Branch("muVtxGlb_z", "vector<float>",&treeLeaf.muVtxGlb_z);
   outputTree->Branch("muGenIndex", "vector<int>", &treeLeaf.muGenIndex);
//   outputTree->Branch("mucktPt", "vector<float>",&treeLeaf.mucktPt);
//   outputTree->Branch("mucktPtErr", "vector<float>",&treeLeaf.mucktPtErr);
//   outputTree->Branch("mucktEta", "vector<float>",&treeLeaf.mucktEta);
//   outputTree->Branch("mucktPhi", "vector<float>",&treeLeaf.mucktPhi);
//   outputTree->Branch("mucktdxy", "vector<float>",&treeLeaf.mucktdxy);
//   outputTree->Branch("mucktdz", "vector<float>",&treeLeaf.mucktdz);
//   outputTree->Branch("muIsoTrk", "vector<float>",&treeLeaf.muIsoTrk);
//   outputTree->Branch("muIsoCalo", "vector<float>",&treeLeaf.muIsoCalo);
//   outputTree->Branch("muIsoEcal", "vector<float>",&treeLeaf.muIsoEcal);
//   outputTree->Branch("muIsoHcal", "vector<float>",&treeLeaf.muIsoHcal);
   outputTree->Branch("muChi2NDF", "vector<float>",&treeLeaf.muChi2NDF);
//   outputTree->Branch("muInnerChi2NDF", "vector<float>",&treeLeaf.muInnerChi2NDF);
   outputTree->Branch("muPFIsoR04_CH", "vector<float>",&treeLeaf.muPFIsoR04_CH);
   outputTree->Branch("muPFIsoR04_NH", "vector<float>",&treeLeaf.muPFIsoR04_NH);
   outputTree->Branch("muPFIsoR04_Pho", "vector<float>",&treeLeaf.muPFIsoR04_Pho);
   outputTree->Branch("muPFIsoR04_PU", "vector<float>",&treeLeaf.muPFIsoR04_PU);
//   outputTree->Branch("muPFIsoR04_CPart", "vector<float>",&treeLeaf.muPFIsoR04_CPart);
//   outputTree->Branch("muPFIsoR04_NHHT", "vector<float>",&treeLeaf.muPFIsoR04_NHHT);
//   outputTree->Branch("muPFIsoR04_PhoHT", "vector<float>",&treeLeaf.muPFIsoR04_PhoHT);
//   outputTree->Branch("muPFIsoR03_CH", "vector<float>",&treeLeaf.muPFIsoR03_CH);
//   outputTree->Branch("muPFIsoR03_NH", "vector<float>",&treeLeaf.muPFIsoR03_NH);
//   outputTree->Branch("muPFIsoR03_Pho", "vector<float>",&treeLeaf.muPFIsoR03_Pho);
 //  outputTree->Branch("muPFIsoR03_PU", "vector<float>",&treeLeaf.muPFIsoR03_PU);
//   outputTree->Branch("muPFIsoR03_CPart", "vector<float>",&treeLeaf.muPFIsoR03_CPart);
//   outputTree->Branch("muPFIsoR03_NHHT", "vector<float>",&treeLeaf.muPFIsoR03_NHHT);
//   outputTree->Branch("muPFIsoR03_PhoHT", "vector<float>",&treeLeaf.muPFIsoR03_PhoHT);
//   outputTree->Branch("muType", "vector<int>", &treeLeaf.muType);
   outputTree->Branch("muD0",  "vector<float>",&treeLeaf.muD0);
   outputTree->Branch("muDz",  "vector<float>",&treeLeaf.muDz);
//   outputTree->Branch("muD0GV", "vector<float>",&treeLeaf.muD0GV);
//   outputTree->Branch("muDzGV", "vector<float>",&treeLeaf.muDzGV);
//   outputTree->Branch("muD0Vtx", "vector<vector<float>>",&treeLeaf.muD0Vtx);
//   outputTree->Branch("muDzVtx", "vector<vector<float>>",&treeLeaf.muDzVtx);
//   outputTree->Branch("muInnerD0","vector<float>", &treeLeaf.muInnerD0);
//   outputTree->Branch("muInnerDz","vector<float>", &treeLeaf.muInnerDz);
//   outputTree->Branch("muInnerD0GV","vector<float>", &treeLeaf.muInnerD0GV);
//   outputTree->Branch("muInnerDzGV","vector<float>", &treeLeaf.muInnerDzGV);
//   outputTree->Branch("muInnerPt","vector<float>", &treeLeaf.muInnerPt);
//   outputTree->Branch("muInnerPtErr","vector<float>", &treeLeaf.muInnerPtErr);
   outputTree->Branch("muNumberOfValidTrkLayers","vector<int>", 
&treeLeaf.muNumberOfValidTrkLayers);
   outputTree->Branch("muNumberOfValidTrkHits","vector<int>",  &treeLeaf.muNumberOfValidTrkHits);
//   outputTree->Branch("muNumberOfValidPixelLayers","vector<int>",  &treeLeaf.muNumberOfValidPixelLayers);
   outputTree->Branch("muNumberOfValidPixelHits","vector<int>",  &treeLeaf.muNumberOfValidPixelHits);
   outputTree->Branch("muNumberOfValidMuonHits","vector<int>",  &treeLeaf.muNumberOfValidMuonHits);
   outputTree->Branch("muStations", "vector<int>", &treeLeaf.muStations);
//   outputTree->Branch("muChambers", "vector<int>", &treeLeaf.muChambers);
//   outputTree->Branch("muIP3D", "vector<float>",&treeLeaf.muIP3D);
//   outputTree->Branch("muIP3DErr", "vector<float>",&treeLeaf.muIP3DErr);
 
   //nTau and taus are missed

//   outputTree->Branch("rho25", &treeLeaf.rho25, "rho25/F");
//   outputTree->Branch("rho25_neu", &treeLeaf.rho25_neu, "rho25_neu/F");
//   outputTree->Branch("rho25_muPFiso", &treeLeaf.rho25_muPFiso, "rho25_muPFiso/F");
//   outputTree->Branch("rho25_elePFiso", &treeLeaf.rho25_elePFiso, "rho25_elePFiso/F");
//   outputTree->Branch("rho2011", &treeLeaf.rho2011, "rho2011/F");
   outputTree->Branch("rho2012", &treeLeaf.rho2012, "rho2012/F");
//   outputTree->Branch("QGTag_MLP", &treeLeaf.QGTag_MLP, "QGTag_MLP/F");
//   outputTree->Branch("QGTag_likelihood", &treeLeaf.QGTag_likelihood, "QGTag_likelihood/F");
//   outputTree->Branch("nCA8Jet",&treeLeaf.nCA8Jet, "nCA8Jet/I");
//   outputTree->Branch("CA8JetPt","vector<float>", &treeLeaf.CA8JetPt);
//   outputTree->Branch("CA8JetEta","vector<float>", &treeLeaf.CA8JetEta);
//   outputTree->Branch("CA8JetPhi","vector<float>", &treeLeaf.CA8JetPhi);
//   outputTree->Branch("CA8JetMass","vector<float>", &treeLeaf.CA8JetMass);
//   outputTree->Branch("CA8JetArea","vector<float>", &treeLeaf.CA8JetArea);
//   outputTree->Branch("CA8Jet_tau1","vector<float>", &treeLeaf.CA8Jet_tau1);
//   outputTree->Branch("CA8Jet_tau2","vector<float>", &treeLeaf.CA8Jet_tau2);
//   outputTree->Branch("CA8Jet_tau3","vector<float>", &treeLeaf.CA8Jet_tau3);
//   outputTree->Branch("CA8JetCHF","vector<float>", &treeLeaf.CA8JetCHF);
//   outputTree->Branch("CA8JetNHF","vector<float>", &treeLeaf.CA8JetNHF);
//   outputTree->Branch("CA8JetCEF","vector<float>", &treeLeaf.CA8JetCEF);
//   outputTree->Branch("CA8JetNEF","vector<float>", &treeLeaf.CA8JetNEF);
//   outputTree->Branch("CA8JetNCH","vector<int>", &treeLeaf.CA8JetNCH);
//   outputTree->Branch("CA8Jetnconstituents","vector<int>", &treeLeaf.CA8Jetnconstituents);
//   outputTree->Branch("CA8prunedJetMass", "vector<float>", &treeLeaf.CA8prunedJetMass);
 //  outputTree->Branch("CA8prunedJet_nSubJets","vector<int>", &treeLeaf.CA8prunedJet_nSubJets);
//   outputTree->Branch("CA8prunedJet_SubjetPt","vector<vector<float>>", &treeLeaf.CA8prunedJet_SubjetPt);
//   outputTree->Branch("CA8prunedJet_SubjetEta","vector<vector<float>>", &treeLeaf.CA8prunedJet_SubjetEta);
//   outputTree->Branch("CA8prunedJet_SubjetPhi","vector<vector<float>>", &treeLeaf.CA8prunedJet_SubjetPhi);
//   outputTree->Branch("CA8prunedJet_SubjetMass","vector<vector<float>>", &treeLeaf.CA8prunedJet_SubjetMass);
   outputTree->Branch("nJet", &treeLeaf.nJet, "nJet/I");
//   outputTree->Branch("jetTrg", "vector<unsigned long>", &treeLeaf.jetTrg);
//   outputTree->Branch("jetEn", "vector<float>",&treeLeaf.jetEn);
   outputTree->Branch("jetPt", "vector<float>",&treeLeaf.jetPt);
   outputTree->Branch("jetEta", "vector<float>",&treeLeaf.jetEta);
   outputTree->Branch("jetPhi", "vector<float>",&treeLeaf.jetPhi);
//   outputTree->Branch("jetCharge", "vector<float>",&treeLeaf.jetCharge);
//   outputTree->Branch("jetEt", "vector<float>",&treeLeaf.jetEt);
   outputTree->Branch("jetRawPt", "vector<float>",&treeLeaf.jetRawPt);
   outputTree->Branch("jetRawEn", "vector<float>",&treeLeaf.jetRawEn);
//   outputTree->Branch("jetArea", "vector<float>",&treeLeaf.jetArea);
//   outputTree->Branch("jetCHF", "vector<float>",&treeLeaf.jetCHF);
//   outputTree->Branch("jetNHF", "vector<float>",&treeLeaf.jetNHF);
//   outputTree->Branch("jetCEF", "vector<float>",&treeLeaf.jetCEF);
//   outputTree->Branch("jetNEF", "vector<float>",&treeLeaf.jetNEF);
//   outputTree->Branch("jetNCH", "vector<int>",&treeLeaf.jetNCH);
//   outputTree->Branch("jetHFHAE", "vector<float>",&treeLeaf.jetHFHAE);
//   outputTree->Branch("jetHFEME", "vector<float>",&treeLeaf.jetHFEME);
//   outputTree->Branch("jetNConstituents", "vector<int>",&treeLeaf.jetNConstituents);
//   outputTree->Branch("jetCombinedSecondaryVtxBJetTags", "vector<float>", &treeLeaf.jetCombinedSecondaryVtxBJetTags);
 //  outputTree->Branch("jetCombinedSecondaryVtxMVABJetTags", "vector<float>", &treeLeaf.jetCombinedSecondaryVtxMVABJetTags);
//   outputTree->Branch("jetJetProbabilityBJetTags", "vector<float>", &treeLeaf.jetJetProbabilityBJetTags);
//   outputTree->Branch("jetJetBProbabilityBJetTags", "vector<float>", &treeLeaf.jetJetBProbabilityBJetTags);
 //  outputTree->Branch("jetBetaStar", "vector<vector<float>>", &treeLeaf.jetBetaStar);
 //  outputTree->Branch("jetPFLooseId", "vector<bool>", &treeLeaf.jetPFLooseId);
 //  outputTree->Branch("jetDRMean", "vector<float>",&treeLeaf.jetDRMean);
 //  outputTree->Branch("jetDR2Mean", "vector<float>",&treeLeaf.jetDR2Mean);
 //  outputTree->Branch("jetDZ", "vector<float>",&treeLeaf.jetDZ);
 //  outputTree->Branch("jetFrac01", "vector<float>",&treeLeaf.jetFrac01);
 //  outputTree->Branch("jetFrac02", "vector<float>",&treeLeaf.jetFrac02);
 //  outputTree->Branch("jetFrac03", "vector<float>",&treeLeaf.jetFrac03);
 //  outputTree->Branch("jetFrac04", "vector<float>",&treeLeaf.jetFrac04);
 //  outputTree->Branch("jetFrac05", "vector<float>",&treeLeaf.jetFrac05);
 //  outputTree->Branch("jetFrac06", "vector<float>",&treeLeaf.jetFrac06);
 //  outputTree->Branch("jetFrac07", "vector<float>",&treeLeaf.jetFrac07);
 //  outputTree->Branch("jetBeta", "vector<float>",&treeLeaf.jetBeta);
 //  outputTree->Branch("jetBetaStarCMG", "vector<float>",&treeLeaf.jetBetaStarCMG);
 //  outputTree->Branch("jetBetaStarClassic", "vector<float>",&treeLeaf.jetBetaStarClassic);
 //  outputTree->Branch("jetBetaExt","vector<vector<float>>", &treeLeaf.jetBetaExt);
 //  outputTree->Branch("jetBetaStarCMGExt", "vector<vector<float>>",&treeLeaf.jetBetaStarCMGExt);
 //  outputTree->Branch("jetBetaStarClassicExt", "vector<vector<float>>", &treeLeaf.jetBetaStarClassicExt);
 //  outputTree->Branch("jetNNeutrals", "vector<float>",&treeLeaf.jetNNeutrals);
 //  outputTree->Branch("jetNCharged", "vector<float>",&treeLeaf.jetNCharged);
 //  outputTree->Branch("jetMVAs", "vector<vector<float>>",&treeLeaf.jetMVAs);
 //  outputTree->Branch("jetWPLevels", "vector<vector<int>>",&treeLeaf.jetWPLevels);
 //  outputTree->Branch("jetMVAsExt_simple", "vector<vector<float>>",&treeLeaf.jetMVAsExt_simple);
 //  outputTree->Branch("jetWPLevelsExt_simple","vector<vector<int>>", &treeLeaf.jetWPLevelsExt_simple);
 //  outputTree->Branch("jetMVAsExt_full", "vector<vector<float>>",&treeLeaf.jetMVAsExt_full);
 //  outputTree->Branch("jetWPLevelsExt_full","vector<vector<int>>", &treeLeaf.jetWPLevelsExt_full);
 //  outputTree->Branch("jetMVAsExt_cutBased","vector<vector<float>>", &treeLeaf.jetMVAsExt_cutBased);
 //  outputTree->Branch("jetWPLevelsExt_cutBased","vector<vector<int>>", &treeLeaf.jetWPLevelsExt_cutBased);
 //  outputTree->Branch("jetMVAsExt_philv1", "vector<vector<float>>",&treeLeaf.jetMVAsExt_philv1);
 //  outputTree->Branch("jetWPLevelsExt_philv1","vector<vector<int>>", &treeLeaf.jetWPLevelsExt_philv1);
 //  outputTree->Branch("jetMt", "vector<float>", &treeLeaf.jetMt);
 //  outputTree->Branch("jetJECUnc", "vector<float>", &treeLeaf.jetJECUnc);
 //  outputTree->Branch("jetLeadTrackPt", "vector<float>", &treeLeaf.jetLeadTrackPt);
 //  outputTree->Branch("jetVtxPt", "vector<float>", &treeLeaf.jetVtxPt);
 //  outputTree->Branch("jetVtxMass", "vector<float>", &treeLeaf.jetVtxMass);
 //  outputTree->Branch("jetVtx3dL", "vector<float>", &treeLeaf.jetVtx3dL);
 //  outputTree->Branch("jetVtx3deL", "vector<float>", &treeLeaf.jetVtx3deL);
 //  outputTree->Branch("jetSoftLeptPt", "vector<float>",  &treeLeaf.jetSoftLeptPt);
 //  outputTree->Branch("jetSoftLeptPtRel", "vector<float>", &treeLeaf.jetSoftLeptPtRel);
 //  outputTree->Branch("jetSoftLeptdR", "vector<float>", &treeLeaf.jetSoftLeptdR);
 //  outputTree->Branch("jetSoftLeptIdlooseMu", "vector<float>",  &treeLeaf.jetSoftLeptIdlooseMu);
 //  outputTree->Branch("jetSoftLeptIdEle95", "vector<float>",  &treeLeaf.jetSoftLeptIdEle95);
 //  outputTree->Branch("jetDPhiMETJet", "vector<float>", &treeLeaf.jetDPhiMETJet);
  // outputTree->Branch("jetPuJetIdL", "vector<float>", &treeLeaf.jetPuJetIdL);
 //  outputTree->Branch("jetPuJetIdM", "vector<float>", &treeLeaf.jetPuJetIdM);
//   outputTree->Branch("jetPuJetIdT", "vector<float>", &treeLeaf.jetPuJetIdT);
  // outputTree->Branch("jetPartonID", "vector<int>", &treeLeaf.jetPartonID);
 //  outputTree->Branch("jetGenJetIndex", "vector<int>", &treeLeaf.jetGenJetIndex);
   //outputTree->Branch("jetGenJetEn", "vector<float>",&treeLeaf.jetGenJetEn);
   outputTree->Branch("jetGenJetPt", "vector<float>",&treeLeaf.jetGenJetPt);
   outputTree->Branch("jetGenJetEta", "vector<float>",&treeLeaf.jetGenJetEta);
   outputTree->Branch("jetGenJetPhi", "vector<float>",&treeLeaf.jetGenJetPhi);
   //outputTree->Branch("jetGenPartonID", "vector<int>", &treeLeaf.jetGenPartonID);
   //outputTree->Branch("jetGenEn", "vector<float>",&treeLeaf.jetGenEn);
   //outputTree->Branch("jetGenPt", "vector<float>",&treeLeaf.jetGenPt);
   //outputTree->Branch("jetGenEta", "vector<float>",&treeLeaf.jetGenEta);
   //outputTree->Branch("jetGenPhi", "vector<float>",&treeLeaf.jetGenPhi);
   //outputTree->Branch("jetGenPartonMomID", vector<int>",&treeLeaf.jetGenPartonMomID);
}
